### ISSUE TITLE
Change initialization method for swagger-tools to be more inline with other express middleware.

### ISSUE THREAD

**Issue by codeHatcher** [apigee-127/swagger-tools#105]
Currently, swagger-tools using an initializeMiddleware method as such:
```javascript
swaggerTools.initializeMiddleware(swaggerDoc, function (middleware) {
  // Interpret Swagger resources and attach metadata to request - must be first in swagger-tools middleware chain
  app.use(middleware.swaggerMetadata());

  // Validate Swagger requests
  app.use(middleware.swaggerValidator());

  // Route validated requests to appropriate controller
  app.use(middleware.swaggerRouter(options));

  // Serve the Swagger documents and Swagger UI
  app.use(middleware.swaggerUi());

  // Start the server
  http.createServer(app).listen(serverPort, function () {
    console.log('Your server is listening on port %d (http://localhost:%d)', serverPort, serverPort);
  });
});
```
Although this is 'ok' it is not the convention for the middleware. I think something more like this would be more inline with convention and reduce the cognitive overhead for new users. I don't know feasibility but I am sure we could figure something out.

(psuedo-code)
```javascript
// all initialization/validation here
var swagger-tools = require('swagger-tools').init(swaggerDoc);
app.use(swagger-tools.swaggerMetaData());
```

another alternative I have seen (I think passportjs does something like this)
```javascript
var swagger-tools = require('swagger-tools');
// init/validate at this point
swagger-tools.use(swaggerDoc, otherFncIfYouNeedIt);
app.use(swagger-tools.swaggerMetaData());
```

Obviously this is me making a suggestions based on what I have seen with every other express middleware that needed some sort of separate initialization phase.

I'll float around IRC but this way others can chime in with their opinion as well. I am speaking from a purely consistent user experience for this middleware in comparison to a lot of the other middleware I have used.

**Comment by bebraw** [comment]
What if you had something like this instead?

```javascript
var swagger = require('swagger-tools');

// ...

// Interpret Swagger resources and attach metadata to request - must be first in swagger-tools middleware chain
app.use(middleware.metadata());

// Validate Swagger requests
app.use(middleware.validator());

// Route validated requests to appropriate controller
app.use(swagger.router(options));

// Serve the Swagger documents and Swagger UI
app.use(swagger.ui());

// Start the server
swagger.load(swaggerDoc, function() {
  http.createServer(app).listen(serverPort, function () {
    console.log('Your server is listening on port %d (http://localhost:%d)', serverPort, serverPort);
  });
});
```

This would keep the API a little tidier.

**Comment by whitlockjc** [comment]
That's not possible.  `swaggerMetadata`, and all subsequent middleware, require the validation phase to complete.  This is the reason it is as it is right now.  Having an async requirement sucks but not having it is equally crappy.  I'm not saying we couldn't work with it like we did before but when I asked about async middleware initialization in the community, it seemed to be something people were doing themselves already using the approach above.

**Comment by bebraw** [comment]
Ok, here's my next go at it then:

```
var swagger = require('swagger-tools');

// ...

// init dummy doc for middlewares to refer. this will be populated later
var swaggerDoc = swagger.doc();

// Interpret Swagger resources and attach metadata to request - must be first in swagger-tools middleware chain
app.use(swagger.metadata(swaggerDoc));

// Validate Swagger requests
app.use(swagger.validator(swaggerDoc));

// Route validated requests to appropriate controller
app.use(swagger.router(swaggerDoc, options));

// Serve the Swagger documents and Swagger UI
app.use(swagger.ui(swaggerDoc));

// Start the server
swagger.load(doc, swaggerDoc, function() { // doc == swagger json
  // swaggerDoc should contain correct data now  

  http.createServer(app).listen(serverPort, function () {
    console.log('Your server is listening on port %d (http://localhost:%d)', serverPort, serverPort);
  });
});
```

I wonder if it would be possible like this? Now you have explicit control over the contents of `swaggerDoc` and will be able to modify its contents on the fly.

That said I'm ok with the current solution. Just thought to point out perhaps an alternative.

**Comment by whitlockjc** [comment]
That still doesn't fix the problem.  `swaggerMetadata` requires a valid Swagger document, an asynchronous process to do.  _(`Specification#validate` is asynchronous)_  All other middlewares, except `swaggerUi`, require `swaggerMetadata` and also require a valid Swagger document.  So for the case you've shown, it's no different than the first case.

I'm really not sure there is a good answer for this.  If we keep things the way they are, people will continue to think that we've broken some Node.js best practice or what not, which we haven't.  On the other hand, making the user have to write the boilerplate to do Swagger document validation prior to using `app.use` on all of the middlewares is equally painful just to make it where we no longer have asynchronous middleware initialization.  _(Look at the [pre-asynchronous API Quick Start](https://github.com/apigee-127/swagger-tools/blob/692d05848d4691a7d8de7321e82ce71f3cbeb8f5/docs/QuickStart.md#creating-our-server) to see what I'm talking about.  Every single application author would have to pre-validate their Swagger document(s) prior to using `swaggerMetadata` and the other middlewares.)_

In the end, I personally think we have to choose the lesser of evils on this one.  If someone has a better idea, I'm all ears.  :)

**Comment by whitlockjc** [comment]
Anymore thought on this?  I am not sure there is a satisfactory solution.  Going back to the way things were doesn't seem like an option because even if you remove the pre-validation this initializer does, you still have to do the resolution of JSON References for Swagger 2.0 to ensure things get wired up properly, which is asynchronous as well so we'd be back at square one.

After doing this for a few months, I'm not so sure it's an issue and I really can't find a place where a **real** answer is given to asynchronous middleware initialization.  Heck, if you look at [apigee-127/swagger-tools/blob/master/examples/2.0/index.js](https://github.com/apigee-127/swagger-tools/blob/master/examples/2.0/index.js), it doesn't even look bad.

**Comment by bebraw** [comment]
@whitlockjc Have you tried asking the Express guys about this? I think they might be able to provide some insight to the issue. Apart from that I'm ok with the current syntax.

**Comment by whitlockjc** [comment]
I'll ask them today.  I did find numerous places online that showed doing something like this.  There was a common `If it's async, why pretend it's not` response.  I'll ask around and if I don't get any new, I'll close this.  Also, the more I think about this, this could be a non-issues as if you really wanted to avoid the pre-validation, the main part of `initializeMetadata`, you could just use the middleware directly:

```js
// ...
var swaggerMetadata = require('swagger-tools/middleware/swagger-metadata');

// ...

// Swagger 1.2
// app.use(swaggerMetadata(rlJson, [petJson, storeJson, userJson));

// Swagger 2.0
app.use(swaggerMetadata(swaggerObject));
```

**Comment by whitlockjc** [comment]
Actually, I think I've convinced myself.  What I will do is document that `initializeMetadata` is the preferred way to do things because it validates the Swagger documents prior to the server starting.  But I will also document that you can use the middleware directly as long as you've either pre-validated it yourself or you take responsibility for things not working in the event you pass it invalid Swagger documents.  Thoughts?

**Comment by bebraw** [comment]
> Actually, I think I've convinced myself. What I will do is document that initializeMetadata is the preferred way to do things because it validates the Swagger documents prior to the server starting. But I will also document that you can use the middleware directly as long as you've either pre-validated it yourself or you take responsibility for things not working in the event you pass it invalid Swagger documents. Thoughts?

Sounds good. :+1:
