### ISSUE TITLE
Specify what failed response validation when swaggerValidator:true is set.

### ISSUE THREAD

**Issue by avishaan** [apigee-127/swagger-tools#108]
Currently I have a failure which says the following in my server console:
`POST /api/v1/reviews 500 176734.546 ms - 5202
Error: Response validation failed: failed schema validation`

Ideally, it should tell me what about the schema failed validation which would be helpful especially for non-trivial schema schemes. If you are setting swaggerValidator to 'true'. You will definitely want to know all the detail regarding the error since you are probably in dev exploring the nature of the failure.

In the meantime you can catch the error with a little of your own custom middleware for anyone that experiences this.

**Comment by dkhanal** [comment]
Unfortunately, swagger_tools (validators.js) completely masks the original reason for validation failure and throws a generic error (see code below). This makes the error thrown pretty much useless. If the reason for validation failure (at least what data item failed validation) could  be provided in the error payload or message, that would be very helpful. 

I am having to completely turn off response validation because of this issue.

```javascript
  var valid = validator.validate(data, schema);

  if (!valid) {
    try {
      throwErrorWithCode('SCHEMA_VALIDATION_FAILED', 'Failed schema validation');
    } catch (err) {
      err.results = {
        errors: _.map(validator.getLastErrors(), function (err) {
          removeParams(err);

          return err;
        }),
        warnings: []
      };

      throw err;
    }
  }
````

**Comment by whitlockjc** [comment]
No it doesn't: https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#validation-errors  All errors that swagger-tools middleware creates is sent downstream via `next` and the documentation linked before shows the structure for getting access to the details.

**Comment by dkhanal** [comment]
The code snippet I pasted above is from swagger-tools (validators.js). Are
you suggesting that this is not the latest code?

**Comment by whitlockjc** [comment]
I'm suggesting you try it.  The code in `lib/validators.js` is some of the most heavily tested code in swagger-tools.  The API, CLI and Middleware all have tests that show that things are not masked at all.

Now, I've been wrong so if I am, please give me a way to reproduce it.

**Comment by whitlockjc** [comment]
Also, there was no tone in the previous message.  If it reads that way, it's just the nature of text-based communication.  :)

**Comment by dkhanal** [comment]
Understood, and thanks for the prompt response. I do have a reproducible scenario. I get a 505 logged on console on response validation errors. I do not have any handlers. So not sure who is logging it... (perhaps express?) and I'm ok with it being logged -- just would have liked the error to state which field failed the validation.

**Comment by whitlockjc** [comment]
Yeah, swagger-tools doesn't return a 505 anywhere.  This might help: https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swagger-middleware-debugging

**Comment by whitlockjc** [comment]
Also, swagger-tools does have a lot of tests for this: https://github.com/apigee-127/swagger-tools/blob/master/test/2.0/test-middleware-swagger-validator.js#L203  That's just one example but we have tests for all types of request/response validation which end up be verified using error handlers like you would have to do.

**Comment by dkhanal** [comment]
I was able to reproduce this error with a very simple set of steps, which you should be able to follow on your side, as well. Try this:

`$ swagger project create swagger-error-test`
Select Express as the framework
`$ cd swagger-error-test`
`$ gedit api/controllers/hello_world.js` You can use an editor of your choice to open this. Change the last statement in `api/controllers/hello_world.js` from `res.json(hello);` to `res.json({field1:hello});`
```
function hello(req, res) {
  // variables defined in the Swagger document can be referenced using req.swagger.params.{parameter_name}
  var name = req.swagger.params.name.value || 'stranger';
  var hello = util.format('Hello, %s!', name);

  // this sends back a JSON response which is a single string
  // res.json(hello); Change this to the following (will cause schema validation failure):
  res.json({field1:hello});
}
```
Then:
`$ swagger project start`
You will see the standard message on the console with a URL. Pull up a browser window and access the resource stated in the message. i.e. `http://127.0.0.1:10010/hello?name=Scott`

You will see the `Error: Response validation failed: failed schema validation` message on the Browser with a stack pointing to the code I pasted a couple posts above.

In the meantime, back on the the console, you will also see the same error logged.

Please let me know if you need further information to reproduce this.

**Comment by whitlockjc** [comment]
This is because you are using the default error handler which does not return the details.  The default error handler in Connect/Express/... will take the error message and the stack and return that to the user.  It will not introspect the error properties and provide them.  I assure you the details of the failure are in the error but your error handler is not using them.

**Comment by whitlockjc** [comment]
I just created a project via `swagger project create testing`.  I changed the `type` from `string` to `integer` for the `name` parameter.  I was able to reproduce your problem.  I then threw in the error handler I've been telling you about and it worked as expected, with details:

**app.js (connect) with the added error handler**

```js
'use strict';

var SwaggerConnect = require('swagger-connect');
var app = require('connect')();
module.exports = app; // for testing

var config = {
  appRoot: __dirname // required config
};

SwaggerConnect.create(config, function(err, swaggerConnect) {
  if (err) { throw err; }

  // install middleware
  swaggerConnect.register(app);

  // Custom error handler that returns JSON
  app.use(function(err, req, res, next) {
    if (typeof err !== 'object') {
      // If the object is not an Error, create a representation that appears to be
      err = {
        message: String(err) // Coerce to string
      };
    } else {
      // Ensure that err.message is enumerable (It is not by default)
      Object.defineProperty(err, 'message', { enumerable: true });
    }

    // Return a JSON representation of #/definitions/ErrorResponse
    res.setHeader('Content-Type', 'application/json');
    res.end(JSON.stringify(err));
  });

  var port = process.env.PORT || 10010;
  app.listen(port);

  console.log('try this:\ncurl http://127.0.0.1:' + port + '/hello?name=Scott');
});

```

**Error response**

```js
{
  "code": "INVALID_TYPE",
  "failedValidation": true,
  "message": "Parameter (name) is not a valid integer: Scott",
  "paramName": "name",
  "path": [
    "paths",
    "/hello",
    "get",
    "parameters",
    "0"
  ]
}
```

Also, the tip I gave you to use `DEBUG=swagger-tools* swagger project start` produces output like this:

```
Starting: /private/tmp/testing/app.js...
  project started here: http://localhost:10010/
  project will restart on changes.
  to restart at any time, enter `rs`
try this:
curl http://127.0.0.1:10010/hello?name=Scott

  swagger-tools:middleware Initializing middleware +0ms
  swagger-tools:middleware   Identified Swagger version: 2.0 +2ms
  swagger-tools:middleware   Validation: succeeded +20ms
  swagger-tools:middleware:metadata Initializing swagger-metadata middleware +87ms
  swagger-tools:middleware:metadata   Identified Swagger version: 2.0 +0ms
  swagger-tools:middleware:metadata   Found Path: /hello +1ms
  swagger-tools:middleware:security Initializing swagger-security middleware +1ms
  swagger-tools:middleware:security   Security handlers: 0 +0ms
  swagger-tools:middleware:validator Initializing swagger-validator middleware +0ms
  swagger-tools:middleware:validator   Response validation: enabled +0ms
  swagger-tools:middleware:router Initializing swagger-router middleware +0ms
  swagger-tools:middleware:router   Mock mode: disabled +0ms
  swagger-tools:middleware:router   Controllers: +1ms
  swagger-tools:middleware:router     /private/tmp/testing/api/controllers/hello_world.js: +0ms
  swagger-tools:middleware:router       hello_world_hello +0ms
  swagger-tools:middleware:metadata GET /hello?name=Scott +2s
  swagger-tools:middleware:metadata   Is a Swagger path: true +1ms
  swagger-tools:middleware:metadata   Is a Swagger operation: true +0ms
  swagger-tools:middleware:metadata   Processing Parameters +0ms
  swagger-tools:middleware:metadata     name +2ms
  swagger-tools:middleware:metadata       Type: integer +0ms
  swagger-tools:middleware:metadata       Value provided: true +0ms
  swagger-tools:middleware:metadata       Value: NaN +0ms
  swagger-tools:middleware:security GET /hello?name=Scott +0ms
  swagger-tools:middleware:security   Will process: yes +0ms
  swagger-tools:middleware:validator GET /hello?name=Scott +0ms
  swagger-tools:middleware:validator   Will process: yes +0ms
  swagger-tools:middleware:validator Failed validation: Not a valid integer: Scott +1ms
  swagger-tools:middleware:validator   Error: Not a valid integer: Scott +1ms
  swagger-tools:middleware:validator       at throwErrorWithCode (/private/tmp/testing/node_modules/swagger-connect/node_modules/swagger-node-runner/node_modules/swagger-tools/lib/validators.js:97:13) +0ms
  swagger-tools:middleware:validator       at validateTypeAndFormat (/private/tmp/testing/node_modules/swagger-connect/node_modules/swagger-node-runner/node_modules/swagger-tools/lib/validators.js:461:7) +0ms
  swagger-tools:middleware:validator       at Object.validateSchemaConstraints (/private/tmp/testing/node_modules/swagger-connect/node_modules/swagger-node-runner/node_modules/swagger-tools/lib/validators.js:548:7) +0ms
  swagger-tools:middleware:validator       at validateValue (/private/tmp/testing/node_modules/swagger-connect/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-validator.js:95:16) +0ms
  swagger-tools:middleware:validator       at /private/tmp/testing/node_modules/swagger-connect/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-validator.js:298:21 +0ms
  swagger-tools:middleware:validator       at /private/tmp/testing/node_modules/swagger-connect/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:246:17 +0ms
  swagger-tools:middleware:validator       at /private/tmp/testing/node_modules/swagger-connect/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:122:13 +0ms
  swagger-tools:middleware:validator       at _each (/private/tmp/testing/node_modules/swagger-connect/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:46:13) +0ms
  swagger-tools:middleware:validator       at async.each (/private/tmp/testing/node_modules/swagger-connect/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:121:9) +0ms
  swagger-tools:middleware:validator       at _asyncMap (/private/tmp/testing/node_modules/swagger-connect/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:245:13) +0ms
```

**Comment by dkhanal** [comment]
I understand Connect/Express may be doing this, but could you please tell me what I can do to prevent this? I tried injecting a handler even before SwaggerExpress is created, but the handler never executes.

```
'use strict';

var SwaggerExpress = require('swagger-express-mw');
var app = require('express')();
module.exports = app; // for testing

var config = {
  appRoot: __dirname // required config
};

app.use(function(err, req, res, next) {
  console.log('original response: ' + err.originalResponse);
});

SwaggerExpress.create(config, function(err, swaggerExpress) {
  if (err) { throw err; }

  // install middleware
  swaggerExpress.register(app);

  var port = process.env.PORT || 10010;
  app.listen(port);

  console.log('try this:\ncurl http://127.0.0.1:' + port + '/hello?name=Scott');
});

```

So can you tell me what I should do to prevent Connect/Express from returning the stack? Where can I inject a handler? As far as I know, I'm following your documentation for a Swagger+Express project and running into this issue without any setup/configuration change on my part. I'd appreciate if you had a workaround (hopefully, its not 'Don't use Express!').

**Comment by whitlockjc** [comment]
The order of the handlers matter.  Add the handler after you install the middleware, just like in the example I showed you.  If you write your own error handler, you control how much information is exposed.  If you notice, the stack is not returned in my working example above.

**Comment by whitlockjc** [comment]
The problem you're running into is a Connect/Express issue and has nothing to do with the swagger module, or the swagger-tools module it's using.  Out of the box, Connect/Express will return an HTML stacktrace of any unhandled errors.

**Comment by dkhanal** [comment]
Thanks very much for this! The issue was the placement of the handler. Turns out you have to inject the handler after 
```
swaggerConnect.register(app);
```
I placed it before just before this line, and even before:
```
SwaggerConnect.create(config, function(err, swaggerConnect) {
...
```
and neither had an effect.

**Comment by whitlockjc** [comment]
Yep, the order matters.  Glad you got it sorted.

**Comment by davidbath** [comment]
Firstly apologies for hijacking this thread. If it's more than a one-time response I'll move it somewhere else.

I stumbled upon this, and it helped tremendously to speed up debugging a number of clumsy errors on my part. It's also helping me to generalize some error handling, and I've expanded the snippet to do some basic error type and http status matching. So far so good. 

However, there's an interesting interaction I can't quite track down and I wonder if you knew off-hand where I was going wrong. If I set:

```
res.statusCode = 500;
```

then I get effectively the stack trace pushed back in JSON. As I've got no code attempting to do that, and the error handler is the last in the stack, I presume something has already jumped in.

Any ideas where I should look?

Thank you.

**Comment by whitlockjc** [comment]
swagger-tools does not render any errors itself, all errors it creates *(or encounters)* are pushed downstream via the `next` function.  Without more details as to what server environment you're using, I don't know if I'll be able to help but I'm pretty sure swagger-tools is not involved.

**Comment by davidbath** [comment]
Thank you for such a quick reply. Sorry, I agree that was very poorly described. I'm using swagger-express-mw, I assume in a very similar way to the original poster, as swaggerexpress and swaggerconnect appear to share mostly the same API here. . I've hooked in a variant of the error handling middleware above after the:

```
swaggerConnect.register(app);
````

But as soon as I add:

``` 
res.statusCode = 500;
```

then the response I get back is not the one created by the custom error handler but instead a stack trace.

I guess I really should have raised this against swagger-node but I hope you might point me in the right direction.

Thanks!

**Comment by whitlockjc** [comment]
Do you mind sharing your `app.js` or at least the part related to `swaggerConnect.register(app)` and your error handler?  Without seeing those, I can't tell what is going on.

**Comment by davidbath** [comment]
Of course. Thank you for your help. I think the pertinent bits are here:

```
SwaggerExpress.create(config, function(err, swaggerExpress) {
  if (err) { throw err; }

  // Add swagger-ui
  app.use(SwaggerUi(swaggerExpress.runner.swagger,swaggerUiConfig));

  // install all the swagger middleware
  swaggerExpress.register(app);

  // Custom error handler that returns JSON
  app.use(function(err, req, res, next) {
    if (typeof err !== 'object') {
      // If the object is not an Error, create a representation that appears to be
      err = {
        message: String(err) // Coerce to string
      };
    } else {
      // Ensure that err.message is enumerable (It is not by default)
      Object.defineProperty(err, 'message', { enumerable: true });
    }
    res.statusCode = 500;
    res.json(err);
  });

  var port = process.env.PORT || 10123;
  app.listen(port);
});
```

I notice (by having played around with a few of the codes) that it's not just 500 that has other effects. If I set it to 304 then err seems to be dropped from the response entirely (although a console.log in the function above shows it's definitely there right before resp.json() is called.

Sorry for the very basic questions.

**Comment by davidbath** [comment]
I should add, this is the simplest test case; the idea is to have a little more sensible processing around the response code messages and codes. I know this snippet looks like I'm just setting every error to response code 500 - that's just to reproduce the behaviour. Not the intended final implementation!

**Comment by davidbath** [comment]
Sorry - have answered my own question on 304. The HTTP spec says that there must be no body, so presumably express is protecting me from myself there!

**Comment by whitlockjc** [comment]
Happy to hear you figured this out.

**Comment by davidbath** [comment]
Well frustratingly I only got part of it. In the sense that I understand why some piece of the stack I can't identify would be dropping the body on the 304 status code, as it's doing exactly what the http/1.1 spec says. 

However, I still haven't managed to work out which bit of the stack is fiddling with the response after I set it here, and there why 500 errors, are for example, handled quite differently than 404 or 200s. So any guidance on what happens after that last `res.json()` would still be incredibly helpful.

Thanks!

**Comment by whitlockjc** [comment]
It could be response validation where your error handler attempts to send a response, the response is invalid based on your Swagger document and then the response validation stuff then creates a new error.  Try running with debug on to see if you're seeing response validation failing: https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swagger-middleware-debugging
