### ISSUE TITLE
Allow use of custom swagger - ui with the swagger - ui middleware

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/swagger-tools#111]
There are many reasons this makes sense.

**Comment by whitlockjc** [comment]
This should be taken care of.  If you pass in `options.swaggerUiDir` to point to the directory where your custom swagger-ui resources are, they should be served instead of the swagger-ui distribution bundle with swagger-tools.

**Comment by anovstrup** [comment]
Does the swaggerUiDir have to contain all the resources, or is it possible to just replace individual resources as needed?

**Comment by whitlockjc** [comment]
You need to serve the full swagger-ui.  I don't want to get into the business of merging trees together if possible.
