### ISSUE TITLE
mock mode expects a schema property to exist when generating mockResponse

### ISSUE THREAD

**Issue by borisirota** [apigee-127/swagger-tools#112]
Hi,

I'm implementing restful API and after successful entity creation I'm returning 201 code with empty response.

The mock mode expects the schema property to exist when [returning 201 code](https://github.com/apigee-127/swagger-tools/blob/master/middleware/helpers.js#L277) and [in general](https://github.com/apigee-127/swagger-tools/blob/master/middleware/helpers.js#L305) when calling the `getMockValue` function (in my case, undefined is passed) so an error is thrown:
```
Error: Callback was already called.
    at /node_modules/a127-magic/node_modules/swagger-tools/node_modules/async/lib/async.js:30:31
    at /node_modules/a127-magic/node_modules/swagger-tools/node_modules/async/lib/async.js:251:21
    at /node_modules/a127-magic/node_modules/swagger-tools/middleware/helpers.js:576:13
    at /node_modules/a127-magic/node_modules/swagger-tools/node_modules/async/lib/async.js:249:17
    at /node_modules/a127-magic/node_modules/swagger-tools/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/node_modules/a127-magic/node_modules/swagger-tools/node_modules/async/lib/async.js:46:24)
    at async.each (/node_modules/a127-magic/node_modules/swagger-tools/node_modules/async/lib/async.js:124:9)
    at _asyncMap (/node_modules/a127-magic/node_modules/swagger-tools/node_modules/async/lib/async.js:248:13)
    at Object.map (/node_modules/a127-magic/node_modules/swagger-tools/node_modules/async/lib/async.js:219:23)
```

I guess that the schema property doesn't have to exist.

Thanks,
Boris

**Comment by borisirota** [comment]
In my case it requires duplication of schema existence. First in the [assignment](https://github.com/apigee-127/swagger-tools/blob/master/middleware/helpers.js#L278) and then when calling the [`getMockValue` function](https://github.com/apigee-127/swagger-tools/blob/master/middleware/helpers.js#L305)

**Comment by whitlockjc** [comment]
I just added support for the `void` response so I must had missed mock mode support when implementing it.  Thanks for the report.
