### ISSUE TITLE
Swagger UI gives `no zlib library` and `no iconv library` warnings

### ISSUE THREAD

**Issue by bebraw** [apigee-127/swagger-tools#114]
To repro:

1. git clone git@github.com:apigee-127/swagger-tools.git
2. cd swagger-tools/examples/2.0
3. npm install
4. node index.js
5. Surf to `http://localhost:3000/docs/`

You should get something along

```
 base is http://localhost:3000/docs/
shred.bundle.js:1726 no zlib library
shred.bundle.js:1734 no iconv library
swagger-ui.js:71 Loaded SwaggerUI
```

Tested in Chrome and Firefox.

The UI runs but it might be nice to have the warnings fixed as they might hide some issues.

**Comment by whitlockjc** [comment]
This should be reported in the [swagger-ui](https://github.com/swagger-api/swagger-ui) project as those lines are logged from it.
