### ISSUE TITLE
Are there standard ways to deal with databases?

### ISSUE THREAD

**Issue by bebraw** [apigee-127/swagger-tools#115]
Is it possible to benefit from the Swagger definition on database level? In the worst case I would have to write out database definitions by hand. I was wondering if there are neater ways to deal with that. How are you doing it?

I know changes to data model and migrations will be an issue. Maybe there should be a generator for the initial schema and then something to generate migrations based on JSON diff.

**Comment by whitlockjc** [comment]
There isn't.  Right now, swagger-tools isn't intended to be a full blow web application framework but I can see how it could be done and why it might be beneficial.  I know [Apigee 127](http://apigee.com/docs/api-services/content/apigee-127) has discussed this and there are others already working on more of a Swagger-based web framework but swagger-tools is intended to be more lower level right now.

This can change at any time of course.

**Comment by bebraw** [comment]
Ok, having it as a separate project would make sense. I guess I'll have to try to write a little something for my purposes. Just having that JSON schema to initial database bridge sort of think available would help a lot I think.
