### ISSUE TITLE
How to make `swaggerUi` middleware work with header based auth + jwt?

### ISSUE THREAD

**Issue by bebraw** [apigee-127/swagger-tools#118]
As I updated my [Swagger Todo example](https://github.com/bebraw/swagger-todo) to use jwt for auth (version 0.3.0), I realized it's not possible to modify `swaggerUi` middleware to work with this type of scheme.

It looks like `swagger-ui` supports header parameters, through. See https://github.com/swagger-api/swagger-ui#header-parameters . That's half the solution.

In order to get that authentication token, `/authenticate` step needs to be performed. In a demo environment that would be quite simple. Just `POST /authenticate` and stash the token or something like that.

The question is, would it be possible to extend `swaggerUi` middleware to support this type of scenario? It would have to become pluggable somehow to make this sort of customizations possible.

**Comment by whitlockjc** [comment]
I already have #111 which would make it where the user could use their custom version of swagger-ui with the swaggerUi middleware.  If that issue were complete, you'd be able to customize swagger-ui to meet your needs and then deploy it with swagger-tools.  If that would work for you, feel free to close this.  If not, let me know what else would be required and we'll get it sorted.

**Comment by bebraw** [comment]
Yeah, #111 is enough. In fact if I want to resolve this now, I can just implement a custom version of your `swaggerUi` and go with that. :)

**Comment by whitlockjc** [comment]
That's good to hear.  I'll get #111 completed in the `0.7.5` release.

**Comment by whitlockjc** [comment]
Well, the `0.8.0` release since a fix to swagger-security made a breaking change.
