### ISSUE TITLE
Multiple Swagger 2.0 specs

### ISSUE THREAD

**Issue by mangvlad** [apigee-127/swagger-tools#126]
Is there a way to "serve" service1.json and service2.json (swagger version 2) specs from the same server? 

Also, is there a way to add/remove specs and routes dynamically (after server already started)?

Thanks!

**Comment by whitlockjc** [comment]
The answer to both questions is "no".  While neither of these features are available, I am sure we could come up with something for sure.  The second to me sounds like more of a development feature and in that case there are a number of good tools out there to restart a server when sources change.  _(If you don't need this as a development feature and more as a feature of a server/service/tool/..., let me know.)_

Either way, I need to know more about what you want for each.  Be as detailed as you can as to how you'd expect these to be configured/initialized, how they'd work, etc.

**Comment by mangvlad** [comment]
I am looking to be able to start my http server as API gateway and to allow new (remote) services to be added/removed while its running. 
Each remote service, once started, will attempt to register itself with the "gateway" by providing its Swagger 2.0 spec file. Once, registered, the gateway will be able to "proxy" all requests to appropriate server (after validating input and enforcing other rules).

I think I can "solve" dynamic routing issue by adding "x-swagger-router-controller" to each spec dynamically before adding it to the server and sending all requests to the same "handler". Once "handler" gets the actual request it can look at the Swagger metadata and do proper routing to the remote server, but for this to work I need to be able to add new specs while server already running...

**Comment by whitlockjc** [comment]
I need to think about this more.  Serving multiple APIs via multiple separate Swagger API documents makes sense to me.  Altering or adding/removing APIs at runtime seems more like a product built around swagger-tools.  I'm open to suggestions.

**Comment by whitlockjc** [comment]
I'm going to close this for now since it was two issues/requests in one.  I will create a new issue, and reference this one for posterity, for serving multiple distinct APIs and see where that gets us.  Thoughts?

If I don't hear back some time today, I will go through with my suggestion.

**Comment by mangvlad** [comment]
Sounds good!
As for "dynamic" loading, I am thinking now that maybe making changes to specs should always require restarts but if I want to add a new spec/endpoint/API I should be able to do it dynamically?

So maybe implementing multiple specs loading can be implemented as a function call (one at a time) that can be done after connect is initialized and running?

**Comment by whitlockjc** [comment]
I'm not sure the best way to handle the adding of new specs and their resulting endpoints at runtime.  I'm not saying it's impossible and from an implementation perspective I have a few ideas already.  My worry is that these middlewares to this point have been very lightweight and solve a specific need while what you're proposing is more of a framework with lifecycles, overhead for state, ...  I'm not saying that's not useful, I just wonder if it belongs in the low-level middleware or in a layer on top that is more of a framework.  I'm all ears.  :)

**Comment by whitlockjc** [comment]
The more I think about this, the more I realize that you could probably do this now.  I know the API doesn't support it but nothing is stopping you from having multiple `initializeMetadata` invocations with different Swagger documents.  I might try this Monday.

**Comment by whitlockjc** [comment]
I have verified that you can in fact serve multiple Swagger documents/APIs within one server.  As mentioned above, you can use `initializeMetadata` N different times with N different Swagger documents.  It is unlikely that `initializeMetadata` will be updated to support one invocation with N different Swagger documents, other than Swagger 1.2 of course.

**Comment by michael-jonas** [comment]
@whitlockjc I can't seem to find an initializeMetadata method anywhere. Are you referring to initializeMiddleware or perhaps middleware.swaggerMetadata()?

**Comment by whitlockjc** [comment]
Right, [initializeMetadata](https://github.com/apigee-127/swagger-tools/blob/master/index.js#L31)...I will update the previous comment.

**Comment by michael-jonas** [comment]
Any idea how this might work for the UI? Kind of stuck right now trying to serve multiple Swagger documents to the Interactive Docs.

**Comment by whitlockjc** [comment]
You'd probably want to do all of this using different mount points:

```js
var swaggerTools = require('swagger-tools');
var swaggerDoc1 = require('apis/api1.json');
var swaggerDoc2 = require('apis/api2.json');

// Validate the first Swagger document
initializeSwagger(swaggerDoc1, function (api1Middleware) {
  // Validate the second Swagger document
  // Yes nesting these sucks but there's no other way.
  initializeSwagger(swaggerDoc2, function (api2Middleware) {
    // Wire up the first API
    app.use('/api1', api1Middleware.swaggerMetadata());
    // ...
    app.use('/api1', api1Middlware.swaggerUi());

    // Wire up the second API
    app.use('/api2', api2Middleware.swaggerMetadata());
    // ...
    app.use('/api2', api2Middlware.swaggerUi());
  });
});
```

I think this is the only way it could work because if you tried to use multiple versions of the middleware without specific mount points, the different instances of the same middleware could trip each other up.

**Comment by michael-jonas** [comment]
Okay that's what I was thinking as well, although the nesting does suck and can/will get messy real fast. 

Just a thought; what about combining multiple swagger docs into one giant object and feeding that to `initializeMiddleware`?

**Comment by whitlockjc** [comment]
I'm not against it.

**Comment by michael-jonas** [comment]
I haven't really had time to think through it all that much but could you see that working? Really not too sure on the details but I'll try some stuff out.

**Comment by whitlockjc** [comment]
I could see it working but I too need to think a little more.

**Comment by michael-jonas** [comment]
Report back if any you've any revelations!
