### ISSUE TITLE
Make swagger-tools even more awesome

### ISSUE THREAD

**Issue by webron** [apigee-127/swagger-tools#134]
Should provide a *warning* when the example property of a response uses mime types that are not part of the consumes property of the operation (directly or inherited).

**Comment by whitlockjc** [comment]
I just checked the 1.2 spec and couldn't see any support for examples in 1.2.  Can you confirm this request is only for 2.0?

**Comment by webron** [comment]
Yes, this is a 2.0 feature only.

**Comment by whitlockjc** [comment]
Thanks Ron, you're a gentleman and a scholar.

**Comment by webron** [comment]
/*sigh/*

**Comment by whitlockjc** [comment]
This will be handled in #145 which will validate this situation and more.
