### ISSUE TITLE
Documentation for semantic validation rules

### ISSUE THREAD

**Issue by maxlinc** [apigee-127/swagger-tools#139]
Semantic validation is awesome, but I think it would be useful to have documentation on what validations swagger-tools performs. I think that would be useful for:
- Helping people decide to use Swagger in the first place. OpenStack is considering a transition from WADL to Swagger, and seeing what kinds of validation are built into the tools would be useful.
- Helping API designers/documenters write better docs. The rules would be a good reference document for them.
- Feature requests / pull requests. Knowing what semantic validation is already done makes it easier to see opportunities for new or improved rules.
- Portability. I'm working on a Ruby parser for Swagger. Right now I suggest people use it alongside swagger-tools since you've got the most complete validator, but it would be nice to have a pure Ruby solution that validates most, if not all, of the same rules.

A few examples of how it could be documented:
- [Rubocop](https://github.com/bbatsov/rubocop)'s rules mostly correspond to the [Ruby style guide](https://github.com/bbatsov/ruby-style-guide). That guide shows examples of mistakes ("bad") along with suggested fixes (ranked "ok", "good" and "better").
- [Foodcritic](http://acrmp.github.io/foodcritic/) lists rules on their site, also with examples of "wrong" and "correct" ways to do things.

**Comment by whitlockjc** [comment]
This is an excellent idea.  I am currently working on #8 so I'll be scanning the code.  I bet I can go ahead and do that at the same time.

**Comment by maxlinc** [comment]
Awesome.

I could only find markdown documentation for swagger-tools, but I saw that the code is also documented via comments. Is there a site where I could see what the rendered documentation looks like, or a command I can run to build it locally? I'm curious if you think you'll be able to create documentation straight from the source or if it needs to be written and maintained as markdown.

**Comment by whitlockjc** [comment]
I do not have any annotated sources but I could create some.  I think documenting this via Markdown would be ideal.  As for building/running locally, do this:

```
# Install Gulp
npm install -g gulp

# Clone This Project
git clone https://github.com/apigee-127/swagger-tools.git

# Change Directory
cd swagger-tools

# Install Dependencies
npm install -d

# Run tests
gulp test-node
```

My plan is to have a document up soon, by end of week, that explains the validation I'm doing.  At that point, you should have what you need.

**Comment by whitlockjc** [comment]
Here is the first pass: https://github.com/apigee-127/swagger-tools/blob/master/docs/Swagger_Validation.md

I have created issue #143 to keep track of the changes in validation for the existing validations so if you disagree with some of the validations in any way, please update that ticket.
