### ISSUE TITLE
Throw an error if a route handler is not found when not in mock mode.

### ISSUE THREAD

**Issue by Nepoxx** [apigee-127/swagger-tools#155]
I believe it would be a good idea if swagger-tools (more specifically swaggerRouter) threw an error during initialization if a route handler is missing. If there's a typo in my controller or the `operationId`, I can only find out if I test every routes (and since some routes return a 404 by design, it can be hard to catch).

Thoughts?

**Comment by whitlockjc** [comment]
One thing you can do to check for this is in your error handler, check to see if `req.swagger.operation` was populated.  If `req.swagger` is populated but `req.swagger.operation` is not, that means the request matched a Swagger path definition but does not match an operation.  If `req.swagger.operation` is populated, then the request matched a Swagger path definition and an operation.  The only way you can get a `404` and `req.swagger` and `req.swagger.operation` are populated is if your controller is missing.

Another thing you can do is use `DEBUG=swagger-tools:middleware*` to see this information in the logs.  I document debugging middleware [here](https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swagger-middleware-debugging).

This being said...do you think I should throw a `500` in this scenario?  Some `Route handler not found for operation` type thing?

**Comment by PierLucGagnon** [comment]
That only works at runtime (i.e. throw an error if we try to call a route without a controller). However I'd like to know on startup if a controller is missing. I don't see a log about a controller missing at startup either.

**Comment by whitlockjc** [comment]
Ah, gotcha.  There should be a startup message but if there isn't, I can fix this.  Let me get started.

**Comment by PierLucGagnon** [comment]
I can't test it right now, but I might not have set the debug environment variable properly to see it. I can re-test with it tonight if needed. Thank you!

**Comment by whitlockjc** [comment]
You are right.  The output using `DEBUG` only shows you the found routes, not that one was expected but not found.  I'll get this sorted.

**Comment by whitlockjc** [comment]
This has been fixed here: https://github.com/apigee-127/swagger-tools/commit/6650a46d186a068e27bcefeb995898a0672c38a0  Now what will happen is if swagger-router identifies that a route handler is missing and is not allowed to *(`useStubs` is `false`)*, a `500` is explicitly returned with a useful error message instead of falling through to the server environment, which typically resulted in a `404`.
