### ISSUE TITLE
Advanced routing options to work around Swagger nuances

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/swagger-tools#158]
There have been a few scenarios that have come up lately regarding working around some nuances related to Swagger.  There are two scenarios where we want to do some _advanced routing_:

* Suppose you have the following route: `/pets/{id}`.  What should happen if there is a request for `/pets` or `/pets/`?  Technically, it is a separate path and would require a separate path definition but most, if not all, routing libraries have the concept of optional path parameters and allow you to define one route to serve both paths.  Since Swagger doesn't support this, it would be nice to mark a path with a path parameter specially so that requests to the path without the path parameter get treated as if they had requested the path with the path parameter in the swagger-metadata/swagger-router middlewares.  This of course would lead to a failed request validation since the required path parameter was omitted.
* Suppose you have N paths that all have a single base and you only want to document that base path.  An example would be a pass through proxy where you just want to pass the request to some behind the scenes backend.  Having to document all possible permutations would be very time consuming if possible at all.  It would be nice to flag a path specially so that requests to that path or anything below it get treated as a request for that path in the swagger-metadata/swagger-router middlewares.

**Comment by MrLeebo** [comment]
:+1: for more smarts about aligning ivory tower swagger operations to the messy, dirty, ugly reality of actual routers :)

**Comment by theganyo** [comment]
Here's to reality! :)

**Comment by whitlockjc** [comment]
As of right now, my plan is to make this an opt-in situation where you attach a vendor extension to your path definition to enable it.  I'm sure @MrLeebo would rather it just work but I want to make swagger-tools work like Swagger by default and allow you to opt-in to the advanced routing.  Here is my suggested annotations for their respective features above, feedback welcome:

* `x-swagger-router-handle-child-paths`
* `x-swagger-router-handle-parent-path`

**Comment by theganyo** [comment]
:+1:

**Comment by MrLeebo** [comment]
I would go with something like `x-swagger-router-allow-optional-path-parameters` because calling it 'handle-child-paths' doesn't read well to me except maybe if the param is on the trailing end of the path. Consider `/households/{householdid}/pets/{petid}` if the (admittedly silly) request comes in `/households//pets/1` you're not really matching childwise you're matching sideways if I'm at all making sense?

**Comment by whitlockjc** [comment]
I like that.  @theganyo, what do you think?

**Comment by theganyo** [comment]
No, this doesn't make sense to me. The handle child paths has nothing to do with parameters.

**Comment by whitlockjc** [comment]
He's talking about the first use case, not your use case.

**Comment by theganyo** [comment]
Ah, ok, instead off x-swagger-router-handle-parent-path. Yes, that makes sense since we can't mark the parameters themselves as optional...

**Comment by whitlockjc** [comment]
I'm breaking this up into multiple issues.  I'll attach @theganyo and @MrLeebo to the appropriate issues.
