### ISSUE TITLE
Match requests for path subpaths

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/swagger-tools#160]
Swagger does not allow you to have a single path to match all subpaths below it.  The purpose of this issue is to allow this at a route matching level in swagger-tools.  The way this will work is you will annotate your path with the `x-swagger-router-handle-subpaths` vendor extension and all requests for subpaths of said path, that do not match an explicit path defined in Swagger, will be associated with the annotate path so that swagger-tools can do the appropriate routing.

This is much like #159 but in reverse.

/cc @theganyo

**Comment by theganyo** [comment]
Minor correction: The marked path will match the path as specified + all subpaths.
