### ISSUE TITLE
Report better errors for corrupted parameters

### ISSUE THREAD

**Issue by mohsen1** [apigee-127/swagger-tools#161]
If a parameter have an extra key or any other issues, Swagger Tools just proxies the JSON Schema's error. It's not enough and not helping user determine what exactly is wrong and what needs to be done. 

For example `allowMultiple` is not allowed here but following error is not helpful 
```
        -
          name: size
          in: query
          allowMultiple: true
          description: Size of array
          required: true
          type: number
          format: double
```

Error:

```
✖ Swagger Error
Data does not match any schemas from 'oneOf'
Jump to line 25
Details
 Object
code:  "ONE_OF_MISSING"
message:  "Data does not match any schemas from 'oneOf'"
 path: Array [5]
0:  "paths"
1:  "/persons"
2:  "get"
3:  "parameters"
4:  "0"
 inner: Array [2]
 0: Object
 1: Object
level: 900
```

**Comment by whitlockjc** [comment]
The `inner` property contains the per-`oneOf` schema validation failures which are more descriptive so if you were to use that for your pretty printed errors, you should already have what you want.

**Comment by prabhatjha** [comment]
Should we always use the inner property in swagger-editor for error?

On Thu, Feb 19, 2015 at 12:33 PM, Jeremy Whitlock <notifications@github.com>
wrote:

> Closed #161 <https://github.com/apigee-127/swagger-tools/issues/161>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee-127/swagger-tools/issues/161#event-238674881>.
>



-- 
Cheers,
Prabhat
---------------------------
Help spread www.eejot.org

**Comment by mohsen1** [comment]
The inner property says many things. Which should we always rely on?
```
✖ Swagger Error
Data does not match any schemas from 'oneOf'
Jump to line 25
Details
 Object
code:  "ONE_OF_MISSING"
message:  "Data does not match any schemas from 'oneOf'"
 path: Array [5]
 inner: Array [2]
 0: Object
code:  "ONE_OF_MISSING"
message:  "Data does not match any schemas from 'oneOf'"
 path: Array [5]
0:  "paths"
1:  "/persons"
2:  "get"
3:  "parameters"
4:  "0"
 inner: Array [3]
 0: Object
code:  "OBJECT_ADDITIONAL_PROPERTIES"
message:  "Additional properties not allowed: format,type,allowMultiple"
 path: Array [0]
 1: Object
code:  "OBJECT_MISSING_REQUIRED_PROPERTY"
message:  "Missing required property: schema"
 path: Array [0]
 2: Object
code:  "ONE_OF_MISSING"
message:  "Data does not match any schemas from 'oneOf'"
 path: Array [0]
 inner: Array [4]
 1: Object
level: 900
```

**Comment by mohsen1** [comment]
"Additional properties not allowed: format,type,allowMultiple"

"Missing required property: schema"

 "Data does not match any schemas from 'oneOf'"

**Comment by whitlockjc** [comment]
Can you paste the pretty printed JSON from this?  The first two are the real _this is why the 'oneOf' was not matched_ but to be sure, I'd love to see the full JSON representation.

**Comment by whitlockjc** [comment]
> Additional properties not allowed: format,type,allowMultiple

> Missing required property: schema"

Those are very specific, human readable errors.  You couple that with the path the error was associated with and you have what you need to do what you want.  I'm open to suggestions and I'm not closing this indefinitely if we have a good way to do this across the board in a way that is not brittle.

**Comment by indolering** [comment]
FWIW, I found this error very confusing, `"Data does not match any schemas from 'oneOf'"` makes 0 sense.

**Comment by whitlockjc** [comment]
We are tracking this in #200.  Long story short, I am proxying through JSON Schema validation errors and that's what we're given.  We'll soon attempt to make this better but please keep track in #200.
