### ISSUE TITLE
Can't figure out how to handle an xml payload

### ISSUE THREAD

**Issue by gsjurseth** [apigee-127/swagger-tools#166]
Hi,

I'm attempting to use a127 to mock up a soap service, but can't seem to set up the configuration so that the payload is available when passed in req to my controller.

I've tried the following post definition.

<snip>
    post:
      summary: fetch betckning reinsert into payload
      description: Send personbetckning and send back user detail information
      operationId: handlePOST
      parameters:
        - name: payload
          in: body
          required: true
          schema:
            $ref: "#/definitions/SoapEnvelope"
      responses:
        "200":
          description: Success
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
</snip>

The SoapEnvelope then defines a property, payload, of type string.

Inspecting the req object with util shows me that req.swagger.params.payload is a valid object, but value is set to {}.

I'm sure that i'm properly sending an xml payload. 

Hope this is enough information and thanks,

/geir

**Comment by whitlockjc** [comment]
Swagger does not support SOAP based on [this](https://groups.google.com/forum/m/#!topic/swagger-swaggersocket/F3pgDtAggAE) thread.  Maybe @webron could comment as to whether this is still accurate.

**Comment by webron** [comment]
I believe I provided the answer [here](https://groups.google.com/d/msg/swagger-swaggersocket/g6xyc3XfTfk/cetUJtvovwEJ) already ;)

**Comment by whitlockjc** [comment]
Like #244, I don't see swagger-tools getting custom parsing logic.  We already provide the raw request value via `req.swagger.params[paramName].value` so you should be able to process however you need in your controller.
