### ISSUE TITLE
Doesn't properly parse array query string parameters that are specified using a collectionFormat (tsv, csv, pipes, etc.)

### ISSUE THREAD

**Issue by emcpadden** [apigee-127/swagger-tools#167]
I created a swagger doc that I am using with a127 project.  In the swagger doc I make use of a query string parameter that I specify as an array that uses the csv collection format.  Here is a snippet 

```javascript
parameters:
  sortParameter:
    name: sort
    in: query
    description: Sort expression used to specify which catalog items should be included in the collection
    required: false
    type: array
    collectionFormat: csv
    items: 
      type: string
```

If I call my API (which uses this sortparameter) as follows:
```javascript
http://127.0.0.1/mycollection?sort=prop1,prop2,prop3
```
Inside my handler, when I call:
```javascript
var sort = req.swagger.params.sort.value;
```
I get an array that looks like this:
```javascript
['p','r','o','p','1',',','p','r','o','p','2',',','p','r','o','p','3',',']
```
When I stepped thru that code, I saw that it looks like the 'convertValue' function inside the swagger-metadata.js file does not look at the collectionFormat, instead it just converts the entire string into an array.

Is the collectionFormat supposed to be supported for Swagger v2 documents?

Thanks!
...Ed

**Comment by whitlockjc** [comment]
`collectionFormat` is valid Swagger but the parameter processor in Swagger does not support it.  I'll get this sorted.

**Comment by emcpadden** [comment]
Cool.  Thanks.  I'm working around it now but I'll switch back once this is fixed.

**Comment by borisirota** [comment]
:+1:

**Comment by borisirota** [comment]
@whitlockjc As I understand the spec, its possible to define array without specifying the collectionFormat and then the default is `csv`. You think of adding support for default value as well? :)
