### ISSUE TITLE
swagger-validator middleware needs to handle charset in consumes validation

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/swagger-tools#17]
The current code that checks the `Content-Type` of a request against the `consumes` of an operation does not handle the charset that can be included in the `Content-Type`.  (See [rfc2616#sec3.7](http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.7))  We need to address this.

Reported by @grahamj

**Comment by alexist** [comment]
When the consume charset is set to [ "application/json; charset=utf-8" ] in the operation, this method doesn't work and throw Invalid content type : 
Error: Invalid content type (application/json).  These are valid: application/json; charset=utf-8

**Comment by whitlockjc** [comment]
We'll discuss this further in #295.
