### ISSUE TITLE
Add validation success message

### ISSUE THREAD

**Issue by earth2marsh** [apigee-127/swagger-tools#171]
If the `validate` command returned a success message, then it help prevent users asking themselves, "Did it work?"

`All validation tests passed. This appears to be a valid spec.`

This could be a chance to have some fun with it, such as giving gold stars or telling them they look nice today, etc.

**Comment by whitlockjc** [comment]
swagger-tools operates like all Unix commands should: _No news is good news_.  I tested a number of Node.js CLI tools to make sure I wasn't being to big a pedant and the ones I tried operate this way.  I'm going to close this but if you have some counterpoint that could sway me, I'll be happy to listen but I doubt it will matter.  _(Not being a jerk but the Unix style is pretty much the standard)_
