### ISSUE TITLE
Swagger Metadata makes "unsafe" calls to request body parsing middleware, causing request timeouts

### ISSUE THREAD

**Issue by MrLeebo** [apigee-127/swagger-tools#172]
swaggerMetadata.js invokes expressjs/body-parser to parse routes with formData parameters. However, it invokes the body-parser middleware directly and doesn't check to see if the body has already been parsed first. 

When that happens, the body parser hangs, resulting in a request timeout.

I think there should be a guard statement to make sure the request hasn't already been parsed:
```
if (req.body) {
  // re-use already parsed body
} else {
  // parse w/ existing bodyParser code
}
```

This gist includes all the of steps to reproduce the error (using Restify):
https://gist.github.com/MrLeebo/4c38a2af5afa5e8e09b8

**Comment by whitlockjc** [comment]
Good catch.  We use to do this but I guess we took it out during the refactoring.
