### ISSUE TITLE
Validate fails when spec has a model with array of strings

### ISSUE THREAD

**Issue by nikhiljindal** [apigee-127/swagger-tools#182]
I have a simple swagger spec (v1.2) which fails validation with the following error:
```
#/models/main.User/properties/items/items/$ref: Model could not be resolved: string
````

Here is how my Model looks:

```
"models": {
   "main.User": {
    "id": "main.User",
    "required": [
     "items"
    ],
    "properties": {
     "items": {
      "type": "array",
      "items": {
       "$ref": "string"
      }
     }
    }
   }
```

Validate passes if I change items to be an array of int (or anything other than array of strings)

Is it invalid to have an array of strings in model? Or is this a bug in `swagger-tools validate`?

**Comment by nikhiljindal** [comment]
Actually on further trying, it seems that validation passes if I replace `$ref` with `type` in
```
"items": {
       "$ref": "string"
      }
```
As per https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#529-property-object $ref should be used to link to other model objects.
So maybe type should be used for primitive types and $ref for other model objects.
Is that correct?

**Comment by bgrant0607** [comment]
@nikhiljindal See:
https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#434-items-object
Yes, my interpretation is that `type` should be used with primitive types, such as `string`.

**Comment by nikhiljindal** [comment]
Thanks!
