### ISSUE TITLE
swagger-ui middleware does not allow explicit api-docs path

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/swagger-tools#183]
If you use `/swagger.json` as your `apiDocs` operation for the swagger-ui middleware, the Swagger document is not served when you access that path.

**Comment by javiyt** [comment]
The problem comes from the line https://github.com/apigee-127/swagger-tools/blob/master/middleware/swagger-ui.js#L129

indexOf does an strict equals, and not always the apiDocsPaths variable contains the whole path requested via URL.

```javascript
var isApiDocsPath = apiDocsPaths.indexOf(path) > -1;
```
