### ISSUE TITLE
Nice to have: warning when `items` of array is an array with single item

### ISSUE THREAD

**Issue by mohsen1** [apigee-127/swagger-tools#185]
If user made a model schema that has a single item in it's `item` array, warn them to use that item directly in `items` property.

This came from https://github.com/swagger-api/swagger-editor/issues/382#issuecomment-83755458

```
  pendingConnections:
    type: array
    items:
      - $ref: '#/definitions/PendingConnection'
    description: users pending connections
```

Warning should tell user to use `{ $ref: '#/definitions/PendingConnection}` directly in `items.

**Comment by whitlockjc** [comment]
Functionally, is there a difference?  I mean, at runtime the JSON Schema validation would work the same regardless so why the warning?

**Comment by mohsen1** [comment]
yes it's the same. With that. it's *too nice to have*! Meaning it might cause confusion.

 Closing
