### ISSUE TITLE
Operation with multipart/formdata only accepts json

### ISSUE THREAD

**Issue by traxair** [apigee-127/swagger-tools#188]
I have the following spec:
```
swagger: "2.0"
consumes:
  - application/json
paths

[...]

  /me/parameters:
    put:
      tags:
        - me
      summary: Update your parameters
      operationId: changeparameters
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: parameter1
          description: Update parameter1
          type: string
        - in: formData
          name: parameter2
          description: Update parameter2
          type: string
        - in: formData
          name: parameter3
          description: Update parameter3
          type: string
      responses:
        "204":
          description: Successfully updated
        "405":
          description: Invalid input
```

I created a nodejs server using swagger's codegen, everything works fine with the embedded doc. However, when I tried using Postman from Chrome or cURL, I came accross this error: `Error: invalid json`, when I was using multipart/formdata. I switched to a JSON object and everything was working fine again. Since I also have files that I want to send, I cannot use json. Is the first `consumes` interfering with the one from `path`?

**Comment by whitlockjc** [comment]
I'll look into this.

**Comment by whitlockjc** [comment]
Looks like the middleware I'm using does not support multi-part form data: https://github.com/expressjs/body-parser

**Comment by whitlockjc** [comment]
It looks like #60 is identical to this in implementation so fixing one will fix both.  I'm going to close this as I intend to get #60 knocked out in the next release.
