### ISSUE TITLE
Empty parameters array in swagger 2.0 spec yields a validation error

### ISSUE THREAD

**Issue by who** [apigee-127/swagger-tools#189]
The Swagger validator badge shows that an empty parameters array is valid.
See: [Validation badge](http://online.swagger.io/validator/?url=https://gist.githubusercontent.com/who/1e8d650f7912b7b6e5f0/raw/4ee499083f16e88d5632f1d48e2f0a38c98a1e1c/empty-parameters-bug.json) referencing [this gist](https://gist.github.com/who/1e8d650f7912b7b6e5f0).

However, the Swagger 2.0 spec as defined by swagger-tools calls this invalid, as the [minimum number of items for a parameters array is 1](https://github.com/apigee-127/swagger-tools/blob/6803225cb9286e201591b6ab3f2ff8e7533767f4/schemas/2.0/schema.json#L1379).

I initially filed this as an issue over in swagger-editor (See https://github.com/swagger-api/swagger-editor/issues/395) but realized that I should file it here.

**Comment by whitlockjc** [comment]
I'll update the schema shipped with swagger-tools to fix this.
