### ISSUE TITLE
Path with query parses incorrectly in swagger-metadata.js

### ISSUE THREAD

**Issue by AlenaSviridenko** [apigee-127/swagger-tools#194]
I have the following simple-swagger.json file:
```
{
  "swagger": "2.0",
  "info": {
    "title": "Microsoft Azure Redis Cache Management API",
    "description": "Some cool documentation.",
    "version": "2.0.1"
  },
  "host": "management.azure.com",
  "schemes": [
    "https"
  ],
  "basePath": "/",
  "produces": [ "application/json" ],
  "consumes": [ "application/json" ],
  "paths": {
    "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/Microsoft.Cache/Redis?api-version={apiVersion}": {
      "get": {
... etc
}
```
as you can notice, my path contains a query. It doesn't work correctly because of this string in swagger-metadata.js :
```
    var path = parseurl(req).pathname;
```
*parseurl(req).pathname* takes the path up to the first non-slash symbol. That's why I got 404 error.
In my opinion, there should be 
```
return function swaggerMetadata (req, res, next) {
    var method = req.method.toLowerCase();
    var path = parseurl(req).href;
    var cacheEntry;
    var match;
... etc
```
*parseurl(req).href* takes the whole request path. It works okay not only for query path, but also for non-query path.

**Comment by whitlockjc** [comment]
Correct me if I'm wrong @webron, but that path string is not valid.  The path string is only for the path portion of your API.  If your API takes query parameters, you should define your parameters in the appropriate location.  If I am right, I'd suggest changing your Swagger document to remove the query string from the path definition.  If I am wrong, I'll see what we can do to support this.

**Comment by mohsen1** [comment]
I think spec schema should disallow `?` in `paths` property names. It can apply to `#` too.

**Comment by webron** [comment]
@whitlockjc - You are correct, that is not valid.

@mohsen1 - We're trying to make the schema validate the structure more than the content. We've had a long discussion, for example, whether we should apply a complex regex for mime types or not. Eventually, we decided to keep it simple. It's not that we don't use regex at all to limit user input, but we keep it as little as possible. That said, if you feel strongly about it, feel free to open an issue on swagger-spec so at least it's there for evaluation.

**Comment by whitlockjc** [comment]
Thanks @webron.  I'm closing this as it should be fixed in swagger-spec.
