### ISSUE TITLE
Request/Responce body validated not according to Swagger 2.0 spec.

### ISSUE THREAD

**Issue by IvanGoncharov** [apigee-127/swagger-tools#197]
According to [spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schema-object) swagger inside **schema object** support only **limited subset** of JSON Schema draft4 and extend it with **custom keywords**.

Right now, you using "z-schema" validator which is work according to Draft4 spec.
So, you don't use "discriminator" and "readOnly" keywords during validation that mean you don't fully support Swagger 2.0 spec. At the same time your library successfully validate schemes which use such keywords.

Personally, I think it's a problem in Swagger spec.
So I created swagger-api/swagger-spec#333 feature request to make Swagger compatible with JSON Schema.
In other case we could have situation in which there is official spec but no one following it :disappointed:
And I want library authors took part in that discussion.

**Comment by whitlockjc** [comment]
We're limited by Swagger's spec so I think I will close this and watch [swagger-api/swagger-spec#333](https://github.com/swagger-api/swagger-spec/issues/333).
