### ISSUE TITLE
API errors with 0.8.6 but not 0.8.5

### ISSUE THREAD

**Issue by dannylevenson-ps** [apigee-127/swagger-tools#199]
In the Swagger documentation for my API, I have responses for one of my paths defined like this:
```javascript
"responses": {
                    "200": {
                        "description": "Person documents",
                        "schema": {
                            "type": "array",
                            "items": {
                                "schema": {
                                    "$ref": "#/definitions/PersonOutput"
                                }
                            }
                        }
                    }
                }
```

This works just fine with swagger-tools 0.8.5, but if we user 0.8.6, I get the following error:
```
API Errors:

  #/paths/~1person/get/responses/200: Data does not match any schemas from 'oneOf'
    #/paths/~1person/get/responses/200/schema/items: Data does not match any schemas from 'anyOf'
      #/schema/items: Additional properties not allowed: schema
      #/schema/items: Expected type array but found type object
    #/paths/~1person/get/responses/200: Additional properties not allowed: schema,description
```

As far as I can tell, I correctly defining the schema for the items in the array by using a reference to the definition elsewhere in my schema document.  Is this a bug introduced by 0.8.6, or do I need to change my definition for my 200 response?

**Comment by whitlockjc** [comment]
There were upstream changes to the Swagger 2.0 JSON Schema files and this is one of those change.  Just change your response  schema to look like this:

```js
"items": {
  "$ref": "#/definitions/PersonOutput"
}
```

The nested schema is not necessary and is what is causing the issue.  Let me know how it goes.  If thus fixes this, feel free to close when you respond.

**Comment by dannylevenson-ps** [comment]
Thanks.  That fixed that problem, but now I've run into another.  One of my API paths can return two different error objects depending on which error is encountered.  I currently have responses defined like this:
```javascript
"responses": {
    "200": {
        "description": "Successful response",
        "schema": {
            "$ref": "#/definitions/GroupDetailed"
        }
    },
    "400": {
        "description": "Unrecognized quote or group ID",
        "schema": {
            "oneOf": [
                {
                    "$ref": "#/definitions/UnrecognizedQuoteId"
                },
                {
                    "$ref": "#/definitions/UnrecognizedGroupId"
                }
            ]
        }
    }
}
```
After moving to Swagger schema 2.0, it causes this error:
```
API Errors:

  #/paths/~1quote~1{citvId}~1group~1{groupId}/put/responses/400: Data does not match any schemas from 'oneOf'
    #/paths/~1quote~1{citvId}~1group~1{groupId}/put/responses/400/schema: Additional properties not allowed: oneOf
    #/paths/~1quote~1{citvId}~1group~1{groupId}/put/responses/400: Additional properties not allowed: schema,description
```
How do I represent the multiple response objects in the new Swagger 2.0 schema?

**Comment by whitlockjc** [comment]
That is not allowed.  Swagger 2.0 is deterministic and `oneOf` is not.  You'll need to reference the [Swagger 2.0 Specification](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#responseObject) or the [Swagger 2.0 JSON Schema](https://github.com/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json#L340) to better understand.

**Comment by dannylevenson-ps** [comment]
I think I figured it out.  I changed my responses to include multiple 400 entries like this:
```javascript
"responses": {
    "200": {
        "description": "Successful response",
        "schema": {
            "$ref": "#/definitions/GroupDetailed"
        }
    },
    "400": {
        "description": "Unrecognized quote ID",
        "schema": {
            "$ref": "#/definitions/UnrecognizedQuoteId"
        }
    },
    "400": {
        "description": "Unrecognized group ID",
        "schema": {
            "$ref": "#/definitions/UnrecognizedGroupId"
        }
    }
}
```
Thanks for the help with this issue.  I suggest augmenting the pet store examples to contain some more complicated examples, or compiling some examples of more complicated APIs that have been documented with Swagger.  I did quite a bit of Googling and didn't find many examples that were helpful for these particular problems.

**Comment by whitlockjc** [comment]
That will work but it will not work like you want.  :)  Any JSON/YAML/JavaScript processor will collapse `400` values into one, with the last one becoming the one that _wins_.  So with the JSON snippet above, the actual JSON that is processed will be this:

```json
"responses": {
    "200": {
        "description": "Successful response",
        "schema": {
            "$ref": "#/definitions/GroupDetailed"
        }
    },
    "400": {
        "description": "Unrecognized group ID",
        "schema": {
            "$ref": "#/definitions/UnrecognizedGroupId"
        }
    }
}
```

So while the validation now works, you're still not working around Swagger's requirement of deterministic REST APIs and this will not work at runtime with anything that uses those values.

**Comment by whitlockjc** [comment]
Swagger's _deterministic APIs_ means each API produces one success and one error for each method/status code.  So you can't have an API that returns `Error1` in some cases for a `400` and `Error2` in other cases for a `400`.  Swagger does not support this and there is no working around it.

As I mentioned above, your workaround really just pleases the validator but the actual computed object from your JSON will not have two `400` responses but one, as described above.

**Comment by dannylevenson-ps** [comment]
So, the path that I am documenting is:
```
/quote/{citvId}/group/{groupId}
```
The path requires two identifiers, and the error results are different depending on which part of the path is wrong.  There is more information available for one of these error paths.  That seems quite deterministic to me.  Is it legal to return one ```Error``` that has a ```oneOf``` in it to handle the different error cases?

**Comment by whitlockjc** [comment]
I understand what you're saying and I do not disagree.  :)  This is a Swagger nuance.  It does not support using `oneOf` anywhere because that is non-deterministic.  _(Their words.)_  I just wanted to point out your _workaround_ will not do what you want even though it appeases the validator.

**Comment by dannylevenson-ps** [comment]
Well, unless somebody else has a better suggestion, it looks like I will have to collapse the two error cases down to one response object schema that includes all the properties from both cases and take the non-common properties out of the required list.  That makes things so much clearer (_heavy sarcasm_).

**Comment by whitlockjc** [comment]
Feel free to bring this up in [swagger-api/swagger-spec](https://github.com/swagger-api/swagger-spec), the specification, it's JSON Schema files and the limitations imposed by it are maintained there.  You are not the only one to bring this stuff up.
