### ISSUE TITLE
Non-standard characters throw a wrench in validation

### ISSUE THREAD

**Issue by earth2marsh** [apigee-127/swagger-tools#208]
I had a YAML spec with a comment line of:
`# consider â€¦/client/templates`

… but that caused a parse issue:
```
swagger-tools/node_modules/yamljs/lib/Parser.js:268
        throw new ParseException('Unable to parse.', this.getRealCurrentLineNb
```

1. Is it necessary to parse comments?
2. Are there character set limitations in the Swagger spec, and if so, should we test for them as part of validation?

**Comment by whitlockjc** [comment]
`yamljs` has an open issue that could be related: https://github.com/jeremyfa/yaml.js/issues/29  Can you let me know if this is the case?  I'm sure this will end up being a `yamljs` issue anyways but it would be nice to file it properly, or comment on an existing one if necessary.

**Comment by earth2marsh** [comment]
Bingo! It looks like it is indeed the root cause. I've added a comment there as you suggested, thanks.

**Comment by mohsen1** [comment]
https://github.com/nodeca/js-yaml is working much better for me in Swagger Editor

**Comment by whitlockjc** [comment]
I migrated from `yamljs` to `js-yaml`, thanks for the idea @mohsen1.
