### ISSUE TITLE
allow swaggerRouter to pass dependencies for injection to routes

### ISSUE THREAD

**Issue by pdapel** [apigee-127/swagger-tools#209]
I would like to be able to (optionally) pass along dependencies through the swaggerRouter so that they are injected into the controllers when the router loads them up.  I'm thinking of common dependencies, like a logger service.  If there is another way to accomplish this already with swagger-tools that I am overlooking, please let me know.

```js
var logger = log4js.getLogger("syslog");
var swaggerOptions = {
  	swaggerUi: "/swagger.json",
  	controllers: "./controllers",
  	useStubs: process.env.NODE_ENV === "development" ? true : false;
};
app.use(middleware.swaggerRouter(swaggerOptions, logger, anotherDep));
```

If the swaggerRouter was called with extra args, pass them to the "`controller = require(...)(logger, anotherDep)`" in the swaggerRouter.js each-loop.

**Comment by whitlockjc** [comment]
Why not just have a middleware that attaches your logger, and other dependencies, to the `req` object?  I'm sure we can come up with something but that's how I do it in a few projects and it works just fine.

**Comment by pdapel** [comment]
Hmm.  I had not considered attaching them to the request object, but that seems reasonable.  Would you mind posting a gist showing how you've implemented that?

**Comment by pdapel** [comment]
Cool.  Thanks for the suggestion and the example.  That will do the trick.  Would you like me to close this issue/request, or would you like to do so?

**Comment by whitlockjc** [comment]
Thanks.  If this no longer works for you or you have a better idea, feel free to let me know.
