### ISSUE TITLE
How to link 

### ISSUE THREAD

**Issue by Ckim15** [apigee-127/swagger-tools#213]
Hi,

I am struggling with link an object to its detail information in the same swagger file.

I am currently using html hyperlink.

Here are what I did:

1. I have a link in GeoAddress definition to see PostalAddress detail in different uri in the same swagger.yaml ( first image); 

2.  when I clicked on PostalAddress link, the url on the address bar changed to position where PostalAddress tab should be opened, but it didn't  open automatically  until I clicked on refresh button/ F5(second image); 

Any idea to solve the issue?

![linktopostaladdress](https://cloud.githubusercontent.com/assets/10535043/7602981/6f18fbce-f8f1-11e4-9743-6ae2e8f9d995.png)
![postaladdressdetail](https://cloud.githubusercontent.com/assets/10535043/7602982/721b2a2c-f8f1-11e4-8a43-0ad0914db95a.png)

**Comment by whitlockjc** [comment]
I'm sorry but this is an issue to be filed in [swagger-ui](https://github.com/swagger-api/swagger-ui).
