### ISSUE TITLE
response object in swagger security

### ISSUE THREAD

**Issue by rguikers** [apigee-127/swagger-tools#214]
I'm trying to implement an oAuth2 handler in swagger security middleware with passport.
Expected behavior will be that oAuth handles the error when token is invalid. For this we will need response object in the handler..
prefered handler :

    oauth2: function(req, def, scopes, callback) {
      return passport.authenticate('bearer', { session: false })(req, **res**, callback);
    }

Missing response for this to work...

Keep in mind that i'm a beginner in swagger security, so maybe i'm missing some valuable insight on why the response object is not included..

Thanks for your help

**Comment by whitlockjc** [comment]
This is a duplicate of #203.   I'll get it sorted, although I think you can still use the Passport API without the `res` object.  Based on the documentation [here](http://passportjs.org/guide/oauth2-api/), it seems the `res` is only used in _your_ handler and not the Passport API:

```js
app.get('/api/me',
  // This does not seem to use the `res` object
  passport.authenticate('bearer', { session: false }),
  // This is your actual 'handler' and of course it needs the `res` object
  function(req, res) {
    res.json(req.user);
  });
```
