### ISSUE TITLE
YAML parsing issue

### ISSUE THREAD

**Issue by earth2marsh** [apigee-127/swagger-tools#215]
When trying to validate the [standard petstore YAML](http://petstore.swagger.io/v2/swagger.yaml), the following error is thrown:
```
> swagger-tools validate geocoder.swagger.json

/usr/local/lib/node_modules/swagger-tools/bin/swagger-tools:201
        throw err;
              ^
SyntaxError: Unexpected token
    at Object.parse (native)
    at parseContent (/usr/local/lib/node_modules/swagger-tools/bin/swagger-tools:63:25)
    at getDocument (/usr/local/lib/node_modules/swagger-tools/bin/swagger-tools:81:5)
    at /usr/local/lib/node_modules/swagger-tools/node_modules/async/lib/async.js:249:17
    at /usr/local/lib/node_modules/swagger-tools/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/usr/local/lib/node_modules/swagger-tools/node_modules/async/lib/async.js:46:24)
    at async.each (/usr/local/lib/node_modules/swagger-tools/node_modules/async/lib/async.js:124:9)
    at _asyncMap (/usr/local/lib/node_modules/swagger-tools/node_modules/async/lib/async.js:248:13)
    at Object.map (/usr/local/lib/node_modules/swagger-tools/node_modules/async/lib/async.js:219:23)
```
At first, I thought this was a problem with the reference app, but as @webron [observes](https://github.com/swagger-api/swagger-core/issues/1052#issuecomment-101411005), it appears to be valid YAML, so this looks like it might be an issue with swagger-tools's YAML parser dependency.

Assuming the petstore reference spec is in fact valid, swagger-tools should validate it appropriately.

**Comment by whitlockjc** [comment]
The file is named `.json` so the JSON parser is used.  Change the file to `.yaml` or `.yml` and it will parse right.

**Comment by whitlockjc** [comment]
I just tested this and if I run `swagger-tools validate http://petstore.swagger.io/v2/swagger.yaml`, I do not get any errors at all during parsing.  I could add a flag to force a specific input format...might not be a bad idea for when people name YAML files with a `.json` extension.  ;)

**Comment by mohsen1** [comment]
@whitlockjc why you even use JSON parser? You can use YAML parser for JSON too. Because JSON is a subset of YAML, YAML parse will just work. In other words, always use `YAML.load` for parsing

**Comment by whitlockjc** [comment]
I didn't know `YAML.load` would do that, good to know.  I still don't know why someone would name a YAML file with a `.json` extension.  ;)

**Comment by webron** [comment]
To confuse the enemy, @whitlockjc.

**Comment by whitlockjc** [comment]
Fixed.  I knew YAML was a superset of JSON but I didn't realize that `YAML.load` would parse both JSON and YAML.  Much simpler now.

**Comment by mohsen1** [comment]
nice!
