### ISSUE TITLE
Initialize without callbacks

### ISSUE THREAD

**Issue by bachp** [apigee-127/swagger-tools#217]
It would be nice if it was possible to initialize the middleware without the callback machinery.

```javascript
swaggerTools.initializeMiddleware(swaggerDoc, function (middleware) {
  app.use(middleware.swaggerMetadata());
  app.use(middleware.swaggerValidator());
  // ...
});
```

it would be clearer to do just:

```javascript
var middleware = swaggerTools.initializeMiddleware(swaggerDoc);
app.use(middleware.swaggerMetadata());
app.use(middleware.swaggerValidator());
// ...
```

The reasoning behind this is that initialization is mostly done at server startup time.
And there it is in my experience more common to see synchronous code.

I had a quick look trough the code and it seems to be possible the make the callback optional. This would keep the old behavior but fall back to sync mode if no callback is given.

Whould this be a desired enhancement for the project?

**Comment by whitlockjc** [comment]
This was discussed in great detail in #105.  To summarize, we pre-validate the Swagger document(s) prior to starting up the server.  That API is asynchronous and so the API we use to initialize middleware is asynchronous as well.  The idea here is that if you have an invalid Swagger document(s), we will not start the server.  _(I realize for typical Swagger integrations the accuracy of your Swagger document might not matter but for Swagger-based APIs the document being valid is a requirement.)_

When this issue originally came up, I went to the Node.js community and based on their feedback, I realized that making an asynchronous API appear to be synchronous didn't make sense and we I went with this approach.  _(I did spend some time trying to make the initialization asynchronous and it involved queueing up requests until the validation came back, exhaust the queue of requests and then serve all requests as they come in.  The problem with this was the logic required, which while simple it felt brittle, and it essentially allowed you to start a server with invalid Swagger document(s).  I also didn't know a good strategy to handle the failure of validating the documents.)_

I'm all ears if you've got a better solution.

**Comment by bachp** [comment]
Well I didn't find #105 when I searched the issues.
But I see the point and I think the effort is to high to rework everything.
Things might get better once we have `yield` from ES6 :)

I'm closing this issue.

**Comment by whitlockjc** [comment]
I would love a better option but when working on #105, I just couldn't come up with something.  I'm all ears for real if you have any ideas.

**Comment by tilleps** [comment]
If anybody else needs to initialize without callbacks, I'm using this workaround:

```javascript
var swaggerTools = require('swagger-tools');
var swaggerDoc = require('./api.json');

var promise = new Promise(function (resolve, reject) {
  swaggerTools.initializeMiddleware(swaggerDoc, function (middleware) {
    resolve(middleware);
  });
});


//
//  Metadata
//
app.use((function (promise, options) {

  return function (req, res, next) {
    promise
    .then(function (middleware) {
      middleware.swaggerMetadata(options)(req, res, next);
    })
    .catch(function (err) {
      next(err);
    });
    
  };
  
})(promise));


//
//  Validator
//
app.use((function (promise, options) {

  return function (req, res, next) {
    promise
    .then(function (middleware) {
      middleware.swaggerValidator(options)(req, res, next);
    })
    .catch(function (err) {
      next(err);
    });
    
  };
  
})(promise, {
  validateResponse: true
}));


//
// Router (Same as above but with swaggerRouter)
// 


//
// UI (Same as above but with swaggerUi)
// 

```

**Comment by whitlockjc** [comment]
In all honesty, you don't have to use callbacks.  All the `swaggerTools.initializeMiddleware` does is validate the Swagger document and then do a little wiring, and it's the validation part of this that makes the API async vs. sync.  If you **know** your Swagger document is valid, just use the middleware directly.  I know I don't emphasize this enough but it is more than possible.  Here is an example for Swagger 2.0:

```
var swaggerDoc = require('api/swagger.json');
var swaggerMetadata = require('swagger-tools/middleware/swagger-metadata');
var swaggerRouter = require('swagger-tools/middleware/swagger-router');
var swaggerValidator = require('swagger-tools/middleware/swagger-validation');
var swaggerUi = require('swagger-tools/middleware/swagger-ui');
var app = require('connect')();

// Do your own validation here

app.use(swaggerMetadata(swaggerDoc));
app.use(swaggerValidator());
app.use(swaggerRouter({
  controllers: './controllers'
});
app.use(swaggerUi(swaggerDoc));
```

This should be enough to get you started.

**Comment by hisabimbola** [comment]
Minor correction on your comment @whitlockjc 
```
var swaggerValidator = require('swagger-tools/middleware/swagger-validator');
```

not 

```
var swaggerValidator = require('swagger-tools/middleware/swagger-validation');
```

**Comment by whitlockjc** [comment]
Thanks @hisabimbola, I've updated the code sample.

**Comment by andrzejzysko** [comment]
There is still mistake in example code :-)
...validatio**r**

**Comment by yoryi** [comment]
@whitlockjc Is there any updates for this? 
https://github.com/apigee-127/swagger-tools/issues/217#issuecomment-197490009 This is not working for me. Do you have any specific solution for this problem? 
As I need to configure the app for the serverless deploy, I would need to configure swagger api routing inlining with other configurations. 
![image](https://user-images.githubusercontent.com/16271026/155045856-5861ca70-52f6-4a65-a713-da8564d947f6.png)
