### ISSUE TITLE
Remote YAML references are broken

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/swagger-tools#222]
When we added _official_ support to swagger-tools for YAML, we neglected to update the code that fetches remote references to work accordingly and so you will end up with some sort of parser error when using remote YAML references.

**Comment by Ckim15** [comment]
Hi,

Is there any way to get definition from swagger yaml which is shared  internally  or from a specific directory in the same app? we need to decouple dependencies between apps.

Example1:  file://machine-name/swagger/swagger.yaml/definitions/Error
Example2:  http://localhost:port/basepath/commonModels.yaml/definitions/Error where commonModels.yaml is in the same folder as swagger.yaml

**Comment by whitlockjc** [comment]
You can already use explicit remote references like you have in _Example 2_.  As for having some syntax for relative references, there is an open issue already for finding files relatively.  The issue is specifically for Swagger 1.2 support but fixing it in one place fixes all known use cases.  _(#168 is the issue I'm referring to.)_

From an implementation perspective, the work would be done as a part of [json-refs/issues/11](https://github.com/whitlockjc/json-refs/issues/11).
