### ISSUE TITLE
Supporting null as valid values in validation

### ISSUE THREAD

**Issue by hhp21** [apigee-127/swagger-tools#228]
As per https://github.com/swagger-api/swagger-spec/issues/229, it seems like the current 2.0 spec doesn't have a way to let you specify whether you allow nulls as valid values. There are valid use cases either way but right now it seems that all null values will fail validation.

Any possibility to add support for this in swagger tools, with/without support from spec?

**Comment by whitlockjc** [comment]
If the Swagger spec does not allow nulls, neither will swagger-tools as we use the JSON Schema from Swagger to do the first pass (structural) validation.  As for making swagger-tools work with nulls, I don't see how without having a custom JSON Schema and I don't think that's a good idea.  I also would rather be Swagger compliant if it were up to me.

Sorry about this but as soon as Swagger supports it, swagger-tools will.

**Comment by anthony-o** [comment]
Couldn't swagger-tools support a `x-nullable` property like other implementations did? (for OpenAPI 2 specification)

**Comment by leedm777** [comment]
OpenAPI 3.0 [adds support for nullable](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields-20), which seems relevant to this issue.

**Comment by anthony-o** [comment]
Yes, but sadly `swagger-tools` doesn't support this version of the specs (yet ?) :(
In [this SO answer](https://stackoverflow.com/a/38140597/535203) it is advised to put an array as the value of the `type` field (`type: ['string','null']`) but I don't think that it works with `swagger-tools` at is not in the 2.0 specs.
[This SO answer](https://stackoverflow.com/a/48114322/535203) advises to use the vendor extension `x-nullable` (but that is not supported by `swagger-tools`).
But [this nullable feature](https://stackoverflow.com/q/48504816/535203) is asked by many people on Stackoverflow & the internet...
