### ISSUE TITLE
req.swagger.params decoding

### ISSUE THREAD

**Issue by jcferrer** [apigee-127/swagger-tools#230]
I ran into this issue:

I have a path parameter like: ```abc:HZ``` and a URL like: ```http://localhost:3000/accounts/{accountId}```

I call my URL (parameter is encoded): ```http://localhost:3000/accounts/abc%3AHZ```

```
Using swagger-tools:
req.swagger.params.accountId.value = abc%3AHZ
```
```
Using express:
req.params.accountId = abc:HZ
```
Why the difference? It seems express is actually decoding the URL parameters while swagger tools are not. Shouldn't the values be decoded always?

Thanks

**Comment by whitlockjc** [comment]
We use the same body parser as Express but since this is not a body parameter, it seems we need to explicitly decode path parameters.

**Comment by jcferrer** [comment]
Do you mean we as library users need to explicitly decode them or is it something you are planning to do in the library itself?

Thanks

**Comment by whitlockjc** [comment]
Nope, I'll do it in the library.

**Comment by jcferrer** [comment]
Thanks man!
