### ISSUE TITLE
Swagger 2.0 validation of 'default' attribute.

### ISSUE THREAD

**Issue by IvanGoncharov** [apigee-127/swagger-tools#235]
You using `1.2` code to validate `2.0` defaults.
For example you allow boolean to be string, see [here](https://github.com/apigee-127/swagger-tools/blob/master/lib/validators.js#L432) or don't check type of string value only it's format(in the same function).
In `2.0` parameters and schemas could be validated as JSON Schemas. 
Because constraints for the fields is the same and JSON Schema allow additional fields.

**Comment by whitlockjc** [comment]
Makes sense.

**Comment by IvanGoncharov** [comment]
That was my intention behind that PR in `z-schema`.
It was my mistake that I didn't report it here earlier.

**Comment by whitlockjc** [comment]
No worries, I'm in the process of rewriting validation so it was timely regardless of its location.

**Comment by IvanGoncharov** [comment]
I have another question.
How are you feeling about extracting swagger 2.0 document validation into separate library?
Because right now you doing best in class Swagger validation.
But `swagger-tool` is too big and complicated for simple scenarios.
That is why people reinventing the wheel, like [here](https://github.com/BigstickCarpet/swagger-parser/blob/master/lib/validate.js).

**Comment by whitlockjc** [comment]
I'm already doing it.  :)  While the repository name will likely change, here is where I'm working on things: https://github.com/apigee-127/swagger-core-api  My plan is to take all of the reusable bits that make up the _API_ and create a library from it.  We will then break out the middleware into a _server API_ as well which will then allow people to write server-specific implementations with ease.

swagger-core-api is not complete and it is a work in progress.  I'm working right now on migrating the validation API over.  Once that is done, there are a few more APIs I'd like to provide before doing the next release.  As of right now, only Swagger 2.0 is supported but underneath things we've created an internal plugin/factory model so we could build in support for other Swagger versions.

**Comment by IvanGoncharov** [comment]
Also this [proposal](https://github.com/zaggino/z-schema/issues/114) should simplify and significantly speedup Swagger validation.
Right now you traverse Swagger document twice and in case of this feature it could be done in a single pass.

**Comment by whitlockjc** [comment]
Makes sense.  Speaking of performance, right now _(in swagger-core-api)_ to ease the development and to make it easier for contributions, I am performing validation in a way that's easy to read but not necessarily the fastest.  Of course where I see reusable patterns I'm combining validation procedures for internal validations but there is nothing stopping someone from registering N validators and walking the tree N+ times.

**Comment by IvanGoncharov** [comment]
So it will be only `2.0` support in `swagger-core-api `?
Mixture of `1.2` and `2.0` make my head explode ;)

**Comment by whitlockjc** [comment]
Correct, 2.0 only for now.

**Comment by whitlockjc** [comment]
I have this working in swagger-core-api: https://github.com/apigee-127/swagger-core-api/blob/master/docs/versions/2.0.md

**Comment by whitlockjc** [comment]
This is fixed.  For Swagger 2.0, type coercion no longer occurs for default values.
