### ISSUE TITLE
Validation model error : Parameter already defined: language

### ISSUE THREAD

**Issue by mohsen1** [apigee-127/swagger-tools#237]
_From @mortias on June 29, 2015 8:49_

In the swagger editor i get a model validation error when i have the same name
for a different parameter type variable?
```
   '/services/{deviceType}/{language}':

     - name: language
          in: path

     - name: language
          in: header
```

_Copied from original issue: swagger-api/swagger-editor#517_

**Comment by whitlockjc** [comment]
What do you expect to happen?  I know swagger-tools will fail at runtime if you have a parameter with the same name regardless of its location being different.  I mean, we can't have two values for `req.swagger.params[paramName]`.  Who is throwing the error?  I didn't think swagger-tools handled this and someone brought this up already.

**Comment by whitlockjc** [comment]
Closing this in favor of #184.
