### ISSUE TITLE
no validation function for format 'uuid'

### ISSUE THREAD

**Issue by aabeling** [apigee-127/swagger-tools#243]
We have a swagger.yaml in our a127 project with a definition containing

    uuid: 
        type: "string"
        format: "uuid"

According to the spec new format values are allowed.

Now in the service log we get an error at
node_modules/a127-magic/node_modules/swagger-tools/lib/validators.js:97:13

The rest response contains

    There is no validation function for format 'uuid'

I expect the unknown format to be simply ignored during validation.

**Comment by whitlockjc** [comment]
That's correct.  We need a way for swagger-tools to add all unknown formats to a whitelist so that they do not cause JSON Schema validation failures.

**Comment by whitlockjc** [comment]
Thanks for reporting this, the fix will be in the next release.

**Comment by aabeling** [comment]
Great, works for me.

**Comment by whitlockjc** [comment]
Good to hear, thanks for the feedback.
