### ISSUE TITLE
Swagger validation: 'items' inside schema objects should be strictly optional.

### ISSUE THREAD

**Issue by IvanGoncharov** [apigee-127/swagger-tools#245]
[This](https://github.com/apigee-127/swagger-tools/blob/master/lib/validators.js#L179) exception is triggered when Schema object is missing 'items'.

But Swagger spec, enforce presence of 'items' only in schema-like objects like for e.g parameters.
But for Schema objects it borrow rules from Draft4, see:
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schema-object
http://json-schema.org/latest/json-schema-validation.html#anchor130

**Comment by webron** [comment]
That's a misinterpretation of the spec. If `type: array`, `items` is always required.

**Comment by IvanGoncharov** [comment]
@webron [Here](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schema-object) it said:
> Unless stated otherwise, the property definitions follow the JSON Schema specification as referenced here.

And I don't see any requirements for `items` inside `Schema object`. 
But JSON Schema treat `items` as optional field.

Should I submit issue in `swagger-spec` repository?
If it intended to be mandatory why don't JSON Schema for Swagger documents doesn't enforce this?
Using [dependencies](http://json-schema.org/latest/json-schema-validation.html#anchor70) validation for JSON Schema.

**Comment by webron** [comment]
Sure, you can submit a ticket on swagger-spec for clarification.

The JSON Schema is for the spec is not 100% compliant, and it never will be (mostly due to limitations with JSON Schema, but also due to complexity and maintenance issues). In any case, the JSON Schema is not the source of truth but the spec is.

**Comment by IvanGoncharov** [comment]
> The JSON Schema is for the spec is not 100% compliant

We discuss it already many times. And this issue is not about JSON Schema compatibility,
there is swagger-api/swagger-spec/issues/333 for that. Instead I want to follow `2.0` spec
as much as possible and for doing that I need validator tool and specification in sync.

This disscussion became unrelated to `swagger-tool` so I opened swagger-api/swagger-spec/issues/404

**Comment by webron** [comment]
https://github.com/swagger-api/swagger-spec/issues/333 is definitely unrelated. I was talking about the JSON Schema for the spec as a whole. https://github.com/swagger-api/swagger-spec/issues/333 refers to e possible expansion of definition in a *future* version of the spec.

**Comment by IvanGoncharov** [comment]
It should be clarify in Swagger spec itself.
So I close this issue.
