### ISSUE TITLE
Mulitple swagger base paths

### ISSUE THREAD

**Issue by rchandu** [apigee-127/swagger-tools#247]
I'm currently using swagger-tools for swagger documentation on my server. I also have client with proxy route to server as in when I'm on client if I do http://{client_url}/server will take to {server_url}. The problem is:

The swagger documentation comes pretty much fine if I load http://{server_url}/docs but not when I do http://{client_url}/server/docs . It just redirects to http://{client_url}/docs and doesn't show any swagger-ui. Is there a way to set multiple base paths for swagger documentation ?

**Comment by whitlockjc** [comment]
So you have one Swagger document and want to have two different paths that get to that document, and the swagger-ui served for that document?

**Comment by rchandu** [comment]
Yes. They're more like aliases. 
http://client/server === http://server
but, http://client/server/docs is not going to http://server/docs it just redirects to http://client/docs
while http://client/server/api-docs === http://server/api-docs

**Comment by whitlockjc** [comment]
I'm not sure this is a swagger-tools fix as you could do this with simple redirects in Express or whatever server you're using.  I can assist you if need be but having swagger-tools support aliases doesn't make much sense right now since the server itself does this with ease.
