### ISSUE TITLE
Support for validating API response messages against model schema

### ISSUE THREAD

**Issue by euoia** [apigee-127/swagger-tools#25]
It is my understanding that in some languages the swagger schema files are generated directly from class files, where fields and their types are derived from the underlying class file. In PHP (using https://github.com/zircote/swagger-php) this is not the case - the model schema files are generated from source code annotations. This leads to the possibility (due to a typo or other error) of a mismatch between what the API produces and what it says it will produce according its schema.

It would be very helpful if there was some way to validate that a message conforms to a given schema. This way, I could validate a sample of real API responses against their schemas as one way of checking for consistency. It would be good if the validator checked for missing and unexpected model properties as well as checking that property types are as expected.

Further, it may be useful during to development to treat invalid responses as an error in the application. This way errors in the API response (or the schema annotations) are caught sooner rather than later.

**Comment by ovr** [comment]
BTW I started to work on similar idea on https://github.com/ovr/swagger-assert-helper, for PHP

Now It's supports
- [X] Asserting Swagger Response Scheme to HttpResponse
- [X] Making HttpRequest by Swagger Path

Still working on it, maybe will be helpfull for someone
