### ISSUE TITLE
New changes to getParameterType() in helper.js results in Cannot read property 'schema' of undefined

### ISSUE THREAD

**Issue by roshanpaiva** [apigee-127/swagger-tools#251]
I recently pulled the latest changes to swagger-tools and noticed that my previously working swagger spec was now failing. I keep getting "Cannot read property 'schema' of undefined". After further debugging, i noticed the error was from the helpers.getParameterType() method. Where schema.schema was throwing an undefined error.

The operation is a PUT and the body has an array of objects. (i've shared a snippet of my swagger spec below). 

When i revert the change in getParameterType() to what it was before, it works fine as expected. Let me know if you need more information.

Reverted to this works.
```
var getParameterType = module.exports.getParameterType = function getParameterType (schema) {
  var type;

  var type = schema.type;

  if (!type && schema.schema) {
    type = schema.type;
  }

  if (!type) {
    type = 'object';
  }

  return type;
};
```

My swagger spec is defined like so:
```
  "/wifinetwork":
    x-swagger-router-controller: wifinetwork
    put:
      security:
        - basicAuth: []
      tags:
        - sometag
      summary: Upload wifi network
      operationId: uploadWiFiNetworks
      description: desc
      parameters:
        - in: body
          name: wifiscandata
          description: desc
          required: true
          schema:
            $ref: '#/definitions/WiFiNetworks'
      responses:
        '200':
          description: WiFi Network updated
          schema:
            $ref: '#/definitions/WiFiNetworks'
....

  WiFiNetworks:
    type: array
    items:
      $ref: '#/definitions/WiFiNetwork'
  WiFiNetwork:
    properties:
      BSSID:
        type: string
      SSID:
        type: string
      Frequency:
        type: integer
        format: int32
      Flags:
        type: string
      SignalLevel:
        type: integer
        format: int32
```

**Comment by whitlockjc** [comment]
I've cleaned up the code but the only way that you'd get the error you speak of is if `schema` is `undefined` which is not possible.  If my latest code doesn't fix this, please open this up with some reproduction recipe.  The easiest way to do that:

* Full JSON/YAML Swagger document
* Run the server in debug mode *(`DEBUG=swagger-tools* ...`)* and paste the output that shows the full stack trace
* Full example of your server that initializes the middleware

**Note:** Of course, obfuscate/prune sensitive details but without something more concrete, I'm not sure I can reproduce.

I looked through the code and could not see how it would be possible for `getParameterType` to be called with an `undefined` schema so if the fix does not fix your issue, I'll need help understanding how this occured.

**Comment by whitlockjc** [comment]
`0.9.1` was just released: https://github.com/apigee-127/swagger-tools/blob/master/RELEASE_NOTES.md#v091-2015-08-04

**Comment by roshanpaiva** [comment]
Thanks Jeremy. I will check it out and let you know.

**Comment by roshanpaiva** [comment]
Hi Jeremy, 

Not quite. This still gives me an error: 
```
if (!type && schema.schema) {
    type = getParameterType(schema.schema);
  }
```
If we change it to the following, its fine:
```
  if (!type && schema.schema) {
    type = schema.type;
  }
```
Here's a sample project that highlights the error i'm seeing: https://github.com/roshanpaiva/Sample

Run npm test to see the error, then make the change to getParameterType as above and it works. Let me know if i've made a mistake in my swagger.yaml

Thanks!

**Comment by daraghking** [comment]
I have this issue as well. I am getting around it by adding
```js
schema = schema || {};
```
as the first line in the getParameterType function. This avoids the can't get whatever from undefined when schema argument is passed in as undefined. I too would like to know if this is a bug or I have an issue in my code as this is my first swagger project so I am not 100% confident it is not an issue my end.

**Comment by whitlockjc** [comment]
I wish I had a stack trace or something to see how it is happening.  I believe it's happening but knowing how is important.

**Comment by daraghking** [comment]
```sh
uncaughtException TypeError: Cannot read property 'type' of undefined
    at Object.module.exports.getParameterType (/home/daragh/sw/swggr-account-push-api/node_modules/swagger-restify-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/helpers.js:40:20)
    at convertValue (/home/daragh/sw/swggr-account-push-api/node_modules/swagger-restify-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-metadata.js:96:21)
    at /home/daragh/sw/swggr-account-push-api/node_modules/swagger-restify-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-metadata.js:125:14
    at arrayMap (/home/daragh/sw/swggr-account-push-api/node_modules/swagger-restify-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/lodash-compat/index.js:1538:25)
    at Function.map (/home/daragh/sw/swggr-account-push-api/node_modules/swagger-restify-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/lodash-compat/index.js:6868:14)
    at convertValue (/home/daragh/sw/swggr-account-push-api/node_modules/swagger-restify-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-metadata.js:124:15)
    at /home/daragh/sw/swggr-account-push-api/node_modules/swagger-restify-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-metadata.js:237:15
    at arrayEach (/home/daragh/sw/swggr-account-push-api/node_modules/swagger-restify-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/lodash-compat/index.js:1421:13)
    at Function.<anonymous> (/home/daragh/sw/swggr-account-push-api/node_modules/swagger-restify-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/lodash-compat/index.js:3482:13)
    at /home/daragh/sw/swggr-account-push-api/node_modules/swagger-restify-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-metadata.js:226:7
```

I think the problem is linked to when it is going through an array definition in the body once it hits the type of the items in the array schema.schema is undefined and then you get the error.

**Comment by roshanpaiva** [comment]
Hey Jeremy, check out the sample project i created for you. Run 'npm test'  and you'll see the error we're seeing. I hope that helps.

**Comment by whitlockjc** [comment]
Yeah, I just cloned your repo.  I'll reproduce and get back to you.

**Comment by whitlockjc** [comment]
Can you tell me how you're testing your API?  I was able to reproduce the issue and after some debugging, I think it's due to a malformed `req.body`...something that swagger-tools can't really do anything about.  Here is how I reproduced the situation with your sample project and how I remedied it.

**Reproduction**

`curl -v -X "PUT" -d '[]' http://localhost:10010/v0_95/1/localwifi/1`

When I was able to reproduce this, my first step in debugging was to see what values were in `req.body` and what swagger-tools was processing as its value.  With the test above, I saw that `req.body` was represented as `{'[]': ''}` instead of `[]`.  That led me to believe that maybe the body parser being used didn't treat my request body as JSON so I tried the same curl above but set the `Content-Type` to `application/json`.  This request worked without any issue.

**Working**

`curl -v -X "PUT" -H 'Content-Type: application/json' -d '[]' http://localhost:10010/v0_95/1/localwifi/1`

That being said, if `req.body` is not well formed, there isn't much I can do and that is what is happening here.  Please let me know what your thoughts are on my findings and we'll go from there.

**Comment by roshanpaiva** [comment]
Hi Jeremy, thanks for testing. I'm definitely sending everything as 'application/json'. If that was the case, then almost everything would fail right? For me, its only failing when i PUT an array of objects. Other PUT's work. 
```
- in: body
          name: creds
          description: WiFi creds
          required: true
          schema:
            $ref: '#/definitions/WiFiCredentials'
```

**Comment by whitlockjc** [comment]
Let me try with more than an empty array.

**Comment by roshanpaiva** [comment]
Jeremy, modify your curl as such and try again pls? (i just added an object into the array). 
```
curl -v -X "PUT" -H 'Content-Type: application/json' -d '[{"id":"test","security":"WPA2-PSK","password":"newtest123"}]' http://localhost:10010/v0_95/1/localwifi/1
```
It failed for me.

**Comment by whitlockjc** [comment]
I've fixed this.  There were two problems:

* We were not using the parameter's schema properly for body parameters *(Not sure how this didn't get tested before, must had been due to this being an array of objects)*
* We were assuming that we found a schema when in some cases that might not happen *(This should be an invalid document but we will not handle it anyways)*

**Comment by whitlockjc** [comment]
I will get a release out soon.

**Comment by roshanpaiva** [comment]
Thanks a lot Jeremy. You rock!

**Comment by whitlockjc** [comment]
`swagger-tools@0.9.3` is released.  Let me know if that fixes your issues.

**Comment by roshanpaiva** [comment]
Yes it does! Thank you.
