### ISSUE TITLE
swagger-ui middleware does not honor Connect mount-points

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/swagger-tools#256]
Connect's `app.use` allows you to use a *mount-point* to allow for middleware to only be registered for a particular base path.  So instead of `app.use(swaggerMetadata)`, you could use `app.use('/some/path', swaggerMetadata)`.  Where the swagger-tools middleware gets tripped up is that `req.url` is the URL **after** the mount-point which means `req.url` will be `/docs` for a request of `/some/path/docs` when using the `/some/path` mount-point.  Since all of swagger-tools middleware was written to work with the full URL, we need to update the pertinent middlewares to use `req.originalUrl || req.url` instead of just `req.url`.

Was originally reported in #250.

**Comment by whitlockjc** [comment]
I just realized that this really only applies to swagger-ui in the instance that @keithchilders was talking about.  All of the swagger-tools middleware uses `req.url` which means it does work with mount-points.  Where the problem happens is when we calculate the URL used in the `Swagger-API-Docs-URL` header consumed by our swagger-ui to auto-configure itself.

**Comment by whitlockjc** [comment]
@keithchilders Can you check the latest master build and see if it fixes your issue?  I have unit tests showing it works but I'd love to hear from you.

**Comment by whitlockjc** [comment]
`0.9.1` was just released: https://github.com/apigee-127/swagger-tools/blob/master/RELEASE_NOTES.md#v091-2015-08-04

**Comment by keithchilders** [comment]
Confirmed fixed. Thanks!
