### ISSUE TITLE
Question: Add validation for format

### ISSUE THREAD

**Issue by oliverhr** [apigee-127/swagger-tools#262]
`lib/validators.js` validateTypeAndFormat

Define validation for format if type is String, the supported formats are `date` and `dete-time`.

How can I add with sagger-tools a Validation for a format like email or any other format?

**Comment by whitlockjc** [comment]
What is happening now?

**Comment by oliverhr** [comment]
Hi Jeremy,

Just the question. How can I add with sagger-tools a Validation for a format like email or any other format?

**Comment by whitlockjc** [comment]
Right now it does not and this would fall into #140.  In all honesty, we're in the process of breaking out the API parts of swagger-tools into a separate project which already has this: https://github.com/apigee-127/swagger-core-api/blob/master/docs/API.md#SwaggerApi+registerValidator

**Comment by oliverhr** [comment]
Ok, thank you Jeremy
