### ISSUE TITLE
Consumes Mime-types not getting validated

### ISSUE THREAD

**Issue by firefoxNX** [apigee-127/swagger-tools#264]
I have a path with "consumes": ["application/json"] defined. When API is called with "Content-Type: application/json, application/x-www-form-urlencoded" the JSON objects show up as undefined. Is this something which swagger-tools validator middleware should be validating?

**Comment by whitlockjc** [comment]
Your `Content-Type` is invalid.  Based on [HTTP rfc2613 section 14.17](http://greenbytes.de/tech/webdav/rfc2616.html#rfc.section.14.17), one content type is provided at a time so what is happening is that when swagger-tools gets your `application/json, application-x-www-form-urlencoded`, it does not match `application/json` and so we do not process the value.  You can still use `req.swagger.params.{yourParamName}.original` to get the original value if you don't want to change your `Content-Type`.
