### ISSUE TITLE
Validations not working when using arrays in input parameters

### ISSUE THREAD

**Issue by firefoxNX** [apigee-127/swagger-tools#265]
I have a POST users endpoint which takes array of users. I have the swagger spec defined as
```
"post": {
  "summary": "Add Users",
  "description": "Add Users",
  "x-swagger-router-controller": "users",
  "operationId": "createUser",
  "parameters": [
    {
      "name": "users",
      "in": "body",
      "description": "Users to add",
      "required": true,
      "schema": {
        "$ref": "#/definitions/Users"
      }
    }
  ]
...
```
The Users definition is
```
"Users": {
  "description": "Collection of Users",
  "properties": {
    "users": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/User"
      }
    }
  }
}
```
When I send invalid JSON the swagger-tools validator does not throw any errors. Any ideas on why the z-schema validation is not working in this scenario?

Debug output -

```
Mon, 10 Aug 2015 22:35:44 GMT swagger-tools:middleware:metadata POST /users
Mon, 10 Aug 2015 22:35:44 GMT swagger-tools:middleware:metadata   Is a Swagger path: true
Mon, 10 Aug 2015 22:35:44 GMT swagger-tools:middleware:metadata   Is a Swagger operation: true
Mon, 10 Aug 2015 22:35:44 GMT swagger-tools:middleware:metadata   Processing Parameters
Mon, 10 Aug 2015 22:35:44 GMT swagger-tools:middleware:metadata     users
Mon, 10 Aug 2015 22:35:44 GMT swagger-tools:middleware:metadata       Type: object
Mon, 10 Aug 2015 22:35:44 GMT swagger-tools:middleware:metadata       Value provided: true
Mon, 10 Aug 2015 22:35:44 GMT swagger-tools:middleware:metadata       Value: [object Object]
Mon, 10 Aug 2015 22:35:44 GMT swagger-tools:middleware:validator POST /users
Mon, 10 Aug 2015 22:35:44 GMT swagger-tools:middleware:validator   Will process: yes
Mon, 10 Aug 2015 22:35:44 GMT swagger-tools:middleware:validator   Request validation: succeeded
Mon, 10 Aug 2015 22:35:44 GMT swagger-tools:middleware:router POST /users
Mon, 10 Aug 2015 22:35:44 GMT swagger-tools:middleware:router   Will process: yes
Mon, 10 Aug 2015 22:35:44 GMT swagger-tools:middleware:router   Route handler: users_createUser
Mon, 10 Aug 2015 22:35:44 GMT swagger-tools:middleware:router   Mock mode: false
Mon, 10 Aug 2015 22:35:44 GMT swagger-tools:middleware:router Handler threw an unexpected error: Cannot read property 'originalValue' of undefined
TypeError: Cannot read property 'originalValue' of undefined
```

I also created a sample project which replicates this behavior - https://github.com/firefoxNX/swagger-tools-valid

**Comment by whitlockjc** [comment]
The error is because you're using `req.swagger.params.user.originalValue` instead of `req.swagger.params.users.originalValue`.  I am able to see that an invalid value passes validation so let me see what I can find.

**Comment by firefoxNX** [comment]
Awesome thanks!

**Comment by whitlockjc** [comment]
Before I tell you what is up, why do you think the request is invalid?

**Comment by firefoxNX** [comment]
It's invalid because the input Json should have users as a property. Unless
the swagger spec is incorrect?

**Comment by whitlockjc** [comment]
In your `Users` definition, there is no `"required": ["users"]` so it is not required.  Not only that but JSON Schema schemas have a default `additionalProperties` value of `{}` which means that you can pass in any extra parameters you want without triggering a validation error.  If I change your `Users` definition to look like this, it works as you'd expect:

```js
{
  "description": "Collection of Users",
  "additionalProperties": false,
  "required": ["users"],
  "properties": {
    "users": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/User"
      }
    }
  }
}
```

I tested this using the [online JSON Schema validator](https://json-schema-validator.herokuapp.com/) and with the sample application you gave me.

**Comment by whitlockjc** [comment]
Once you make these changes, your `{"invalid": []}` will trigger an error.  Changing `invalid` to `users` does not trigger an error because it's an empty array.  If you want to fix that, you need to set `minItems` to `1` for your array.  Of course, even with that not set, if you try `{"users": [{}]}` the expected error is triggered as well.

**Comment by whitlockjc** [comment]
If you can verify my finding, please let me know and close the issue.  Otherwise, let me know what you find and I'll take a peek.

**Comment by firefoxNX** [comment]
Thank You very much Jeremy. I need a lesson in JSON schemas!

**Comment by whitlockjc** [comment]
No sweat.  I've been bitten by the default lax nature of JSON Schema many times.  :)
