### ISSUE TITLE
inline schema definitions

### ISSUE THREAD

**Issue by Hanspagh** [apigee-127/swagger-tools#273]
This swagger-api/swagger-ui#1133 does not seem to work with swagger-tools

**Comment by whitlockjc** [comment]
I need to update the embedded version of swagger-ui with swagger-tools.  In the meantime, you can work around this by using your own deployed swagger-ui: https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swaggeruioptions

**Comment by Hanspagh** [comment]
I tried that, but I cant find a way to do it when using the swagger io from npm? Am I missing something?

**Comment by whitlockjc** [comment]
How did you hook swagger-ui up in swagger-node?  However you did that, just update the call to the swagger-ui middleware to have the `options.swaggerUiDir` set to where you have your custom swagger-ui deployment on disk.

**Comment by Hanspagh** [comment]
Yes, I used the swaggerUiDir options. For making the deployment easier I really wanted to use the swagger-ui dist. on npm. The problem with this is that this dist. points to the pet example, so my question is can I do anything from swagger-tools/node to overwrite this without changing the the ui dist.

**Comment by whitlockjc** [comment]
No.  swagger-ui out of the box is hard coded to work with the Petstore.  When I ship swagger-ui with swagger-tools I have to work around this by changing the `index.html` file.  You *might* be able to use the `options. apiDocs` to be `swagger.yaml` and that *could* work as I think the default swagger-ui distribution will look for the Swagger document relative to the swagger-ui deployment.  But...that is only a guess.

**Comment by Hanspagh** [comment]
Didn't seem to work, I could work around it by providing the docs in browser ui, but for now I think I will stick to swagger-tools and then just live with the fact that inline docs does not for now. Any idea when you are gonna update or would you accept a pull request with the update?

**Comment by whitlockjc** [comment]
I can push a release any time really but I try to lump bugs/features together.  Let me look at the issue queue to see if there are any quick wins that I can bundle with this.

**Comment by Hanspagh** [comment]
Cool.
