### ISSUE TITLE
Getting Invalid content type (application/octet-stream) for empty POST request body from docs page

### ISSUE THREAD

**Issue by nick13jaremek** [apigee-127/swagger-tools#275]
Hi there,

I am using Swagger 2.0 and swagger-tools on a NodeJS project to offer my RESTFUL API.

I have defined my API in a swagger.json file and everything works fine so far except for one endpoint which seems to fail strangely.

It is a POST endpoint that only requires one parameter in its path, no body content, as follows: 

    {
        "/app/subscribe/{id}": {
            "post": {
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Identifier of the application for which the user subscribes",
                        "required": true,
                        "type": "string"
                    }
                ]
            }
        }
    }

For some reason, when clicking on the "Try it out" button of my local swagger docs for this endpoint, I get the following error:

    {
      "code": "InternalError",
      "message": "Invalid content type (application/octet-stream).  These are valid: application/json"
    }

If I add the `application/octet-stream` content type to the `consumes` object in *swagger.json*, then the "Try it out" request works fine.

Of course, If I do a `curl` operation from the terminal setting the content type to `application/json` then everything behaves fine.

However, it is unfortunate that such an amazing and interactive docs section fails because the request content-type is not of type `application/json`.

Is there any way to force the POST request to be of type `application/json`

**Comment by whitlockjc** [comment]
If I understand correctly, you're saying that swagger-ui's "Try It" functionality is not setting the `Content-Type` properly so that when it makes a request, the request validation fails due to the `Content-Type` checking.  If this is correct, the error should be reported to swagger-ui.  Let me know if this is the case.

**Comment by nick13jaremek** [comment]
Hi.

That is correct. The "Try it out" functionality seems to set the content type to application/octet-stream rather than to application/json for POST request without body content, in the Swagger-UI.

Let me know if you would need more information on this to report or if you want me to report it in the swagger-ui repo.

Thanks!

Enviado desde mi iPhone

**Comment by whitlockjc** [comment]
Yes, it should be reported to swagger-ui.
