### ISSUE TITLE
Handle CORS OPTIONS call

### ISSUE THREAD

**Issue by akras14** [apigee-127/swagger-tools#278]
This is more of a question, than an issue. We are currently switching our API's from swagger-node-express to swagger-tools, and run into issue with CORS requests. 

It looks like express automatically adds Allow headers based on which methods are defined in routes. Something like: 

https://github.com/strongloop/express/blob/11a77a3fffb0476a460c4e68536ce20f5b3c542f/lib/router/index.js#L623
```
// send an OPTIONS response
function sendOptionsResponse(res, options, next) {
  try {
    var body = options.join(',');
    res.set('Allow', body);
    res.send(body);
  } catch (err) {
    next(err);
  }
}
```

Swagger-tools, does not appear to provide same functionality (or may be I overlooked it). I was just curious if: 

1. You are providing this option already, (and it just didn't work in our modified version)
2. If you do not currently provide it, if you plan on adding this in, or if we should handle it outside of the swagger tools flow (either via a custom middleware or Nginx config).

**Comment by whitlockjc** [comment]
swagger-tools does not get involved in CORS at all since that is part of your API contract.  swagger-tools merely helps with the Swagger integration.  If I misunderstood, please feel free to reopen.

**Comment by akras14** [comment]
Perfect, thanks for a quick response.
