### ISSUE TITLE
x-swagger-router-controller and subfolders ?

### ISSUE THREAD

**Issue by jscti** [apigee-127/swagger-tools#283]
Hi
Is it possible to link a swagger path to a controller that is located in a subfolder ?

I have different modules in my app and I wish I could do something like (in my YAML) :

```javascript
x-swagger-router-controller: "main" // api/controllers/main.js
x-swagger-router-controller: "auth" // api/controllers/auth.js
x-swagger-router-controller: "pets/cat" // api/controllers/pets/cat.js
x-swagger-router-controller: "pets/dog" // api/controllers/pets/dog.js
x-swagger-router-controller: "module2/whatever" // api/controllers/module2/whatever.js
```

Thanks

**Comment by whitlockjc** [comment]
This isn't an option right now but it it should be trivial to support.

**Comment by whitlockjc** [comment]
So how do you see this working?  Would you still set `options.controllers` to some singular directory and then the `x-swagger-router-controller` will allow `/` to denote a sub directory to search within?

**Comment by michael-jonas** [comment]
Running into a similar situation as @jscti. @whitlockjc I imagine it working the way you mentioned. Makes it easier to organize the structure of the project, IMO. Has any progress been made on this?

**Comment by whitlockjc** [comment]
No but I'm scheduling a swagger-tools release soon and hoping to knock out as many bugs as possible, this one included.

**Comment by michael-jonas** [comment]
Oh awesome! Looking forward to it.

**Comment by mateusnroll** [comment]
Fixed it, and did a pull request. What do you guys think?

**Comment by whitlockjc** [comment]
I love the idea but I need some tests to merge.  Some documentation would be nice as well but I don't mind doing that after the fact to get this merged sooner.

**Comment by leomar-developer** [comment]
Could you guys tell if this feature has been merged already?

**Comment by whitlockjc** [comment]
There was a PR for it but it needed tests and while I continued to ask for an update, I never got anything.  If @mateusnroll could complete the PR, we could get this merged.

**Comment by cristiboariu** [comment]
Hi guys, can this PR be merge as soon as possible? I think this is a very needed feature to have...

**Comment by whitlockjc** [comment]
I guess @mateusnroll has moved on and his PR is dormant.  I will have to take over this myself.  I'll look into it.

**Comment by whitlockjc** [comment]
This has been taken care of by #422 and will be in the next release.
