### ISSUE TITLE
Swagger-validator only returns one error in the results.errors array

### ISSUE THREAD

**Issue by The3ngineer** [apigee-127/swagger-tools#286]
Currently the swagger-validator stops validating after the first error it finds so the _failedValidation_ Error array _results.errors_ only ever has one entry. Looking at the source (_createJsonValidator_ in _lib/helpers.js_) it appears that the default for a new ZSchema validator is to set _breakOnFirstError:true_ and you have to explicitly set this to false to obtain multiple errors. 

In our application we would like to send all detectable errors back in one go and setting _breakOnFirstError:false_ we get the desired response. Is there some reason why the validator does not do this as standard? Thanks!

**Comment by whitlockjc** [comment]
Can you give me an example of what you're seeing and what you'd expect?  It's weird that our tests haven't run into this already since we have tests that verify multiple breaks but maybe we're not testing the scenario you speak of.

**Comment by whitlockjc** [comment]
I can reproduce this and will get it into the next release.  Surprised this hasn't come up before.

**Comment by The3ngineer** [comment]
Thanks!
Steve

**Comment by whitlockjc** [comment]
No problem, thanks for the report.
