### ISSUE TITLE
pass options for multer into swagger-metadata middleware

### ISSUE THREAD

**Issue by calibr** [apigee-127/swagger-tools#287]
Hello! Our swagger project recieves big file uploads(up to 2G), but current swagger-metadata middleware uses `inMemory: true`(https://github.com/apigee-127/swagger-tools/blob/master/middleware/swagger-metadata.js#L41-L43) multer configuration, so that can cause huge memory consumption with concurrent uploads. I guess it's a good approach to allow multer to be configurable, I can submit PR, but I have no idea how to pass options to swagger-metadata middleware. I see that first two arguments are taken(https://github.com/apigee-127/swagger-tools/blob/master/middleware/swagger-metadata.js#L430), perhaps need to add third argument for custom options. Can you give advice about that?

**Comment by whitlockjc** [comment]
All of the request parsers are provided for your convenience and will not always work for your needs.  If you need to provide your own configuration, just `app.use` them however you would as if swagger-tools was not involved.  We almost went down the path of having configuration options for each parser but we chose against it.  I'll keep it open to allow you to respond but chances are good I'll close this as it's working as designed.

**Comment by calibr** [comment]
Your answer was helpful, I have fixed this issue by adding custom middleware before swagger's:

```js
var upload = multer({dest: "/tmp"});
app.use(upload.fields([{name: "file"}]));
```

It works as needed. Thank you for help!

PS. Part of yaml file with field definition if somebody also stuck with this issue:

```yaml
  parameters:
    - name: file
      in: formData
      description: File to store
      type: file
      required: true
```

**Comment by whitlockjc** [comment]
Thanks @calibr, I appreciate your help.

**Comment by b4dnewz** [comment]
@calibr do you know if is possible to set custom middlewares only for specific routes instead of whole app?

**Comment by calibr** [comment]
@b4dnewz I don't think you can configure this via the yml file, so probably you have to use path option in the `app.use` function: `app.use("/path", middleware)`
