### ISSUE TITLE
mainController

### ISSUE THREAD

**Issue by Santinell** [apigee-127/swagger-tools#288]
I am tired of writing the same controllers, so may be add new feature - setting mainController?
With this feature you can be more flexible - all logic of calling methods from models will be in mainController.

example of my mainController:
```javascript

'use strict';
var path = require('path');

var controller = {
  sendResult: function(result, res) {
    res.set('Content-Type', 'application/json');
    if (typeof result !== 'undefined') {
      res.end(JSON.stringify(result || {}, null, 2));
    } else {
      res.status(500).end();
    }
  },
  getMethod: function(operationId) {
    var res = operationId.split(".");
    var modelName = res.length > 1 ? res[0] : 'default';
    var methodName = res.length > 1 ? res[1] : res[0];
    var model = require(path.join(__dirname, 'models', modelName));

    return model[methodName];
  },
  getArgs: function(method, params) {
    var args = method.toString().match(/function[^(]*\(([^)]*)\)/)[1]
    var argNames = args ? args.split(/,\s*/) : [];
    var methodArgs = [];
    for (var i = 0, len = argNames.length; i < len; i++) {
      methodArgs.push(params[argNames[i]].value);
    }
    return methodArgs;
  },
  call: function(req, res, next) {
    var method = controller.getMethod(req.swagger.operation.operationId);
    if (!method || typeof(method) !== "function")
      throw new Error("Method not found: " + req.swagger.operation.operationId);
    var methodArgs = controller.getArgs(method, req.swagger.params);
    var result = method.apply({}, methodArgs);
    controller.sendResult(result, res);
  }
};

module.exports = controller;

```

mainController must have method "call" and throw Error if something wrong

**Comment by Santinell** [comment]
With this feature I can use my own rules of naming methods.
For example - without "x-swagger-router-controller" use operationId like:
'user.info'
'user.register'
'post.add'
'post.list'

And split it by point on modelName and methodName

**Comment by theganyo** [comment]
Hi @Santinell,
Just curious, do you happen to use swagger-node? Or are you using swagger-tools directly? (I ask because if you're using swagger-node, there is a way you could do this without setting x-swagger-router-controller on each path.)
Scott

**Comment by Santinell** [comment]
I am using swagger-tools and to be honestly - it looks strange what swagger-node depends on swagger-tools. I think  swagger team must create base library, and on top of it will be build all other tools and middlewares

**Comment by whitlockjc** [comment]
swagger-tools existed before swagger-node so to avoid rewriting everything swagger-tools already provided, it made sense.  I'm not sure what's weird about it but feel free to contribute your own suggestions.

**Comment by whitlockjc** [comment]
As for what you want, swagger-tools will allow you to do this.  Just use the same `x-swagger-router-controller` for each path...or just solve this in the JavaScriot layer.  There are a few ways to solve your problem right now.

**Comment by Santinell** [comment]
I think using x-swagger-router-controller is not good choise, because it will be removed in version 1.0
You don't like idea with mainController? I think it can solve many issues:
- user defined Model-Method mapping
- modules and submodules (ex. user.me, user.add, user.auth.key, user.auth.refresh)
- using subfolders of models

**Comment by whitlockjc** [comment]
Oh, removing `x-swagger-router-controller` is not guaranteed.  I think my thoughts on removing it were more about not needing it than not benefiting from it.  Whenever we neglected to require unique `operationId` values, you could have two different operations using the same `operationId` and `x-swagger-router-controller` allowed you to differentiate them.  Since we **should be** validating unique `operationId` *(See #220)*, you wouldn't *need* `x-swagger-router-controller` anymore but it could still be useful because even though you need unique `operationId` values, you'd still need a way to say what controller that handler should be found.  So, #221 will likely end up not happening.

As for your idea, I'm not against it.  We already have open requests for sub-path based controllers *(See #283)*, so `admin/User` for using `controllers/admin/User.js`, and multi-level handlers *(See #131)*.  Seeing that we've not solved these means we of course have not looked into *how* we'll do it just yet.

**Comment by Santinell** [comment]
Maybe instead of using `x-swagger-router-controller` is better use `operationId` to define Controller or Model(if mainController is defined in options) and Method? That can guarantee unique `operationId`.
And if we give the user the ability to determine which method to call (based on operationId), it will give greater flexibility

**Comment by whitlockjc** [comment]
Well, `operationId` is for the method itself and we aren't validating they are unique since that would break deployments out there that were using duplicates.  We'll add that in 1.0.  We'll be revisiting this for sure.
