### ISSUE TITLE
Path templating with dashes and slashes

### ISSUE THREAD

**Issue by theganyo** [apigee-127/swagger-tools#289]
I had a couple of issues with path templates in swagger-tools today:

1) You can't have a parameter in your template that has a dash ('-') in it: `/path/{Some-ID}`. Note that this doesn't get an error on parsing or validation, but it also will not match an incoming request to a path like `/path/24`. It seems to me that this is probably a bug in either swagger-tools validation or path-matching.

2) A parameter in a template cannot match slashes within the segment. Ie. `/path/{SubPath}/end` will not match an incoming request to `/path/some/sub/end`. This seems more likely to be correct, but...

I couldn't find where either of the above examples were explicitly allowed or disallowed in the spec.  Did I just miss the definition in the spec? Or are either of these a bug / limitation in swagger-tools?

Thanks!

**Comment by whitlockjc** [comment]
1. It seems that [pillarjs/path-to-regexp](https://github.com/pillarjs/path-to-regexp) does not handle `-` in the variable name portion of paths.  I have opened up a question to see if this should be supported at [pillarjs/path-to-regexp/issues/63](https://github.com/pillarjs/path-to-regexp/issues/63)

2. It seems to be working as designed for this one.

**Comment by whitlockjc** [comment]
@webron, can you comment on this?  Are there any expected limitations on the characters used in the parameter name for path templates?

**Comment by webron** [comment]
The Swagger spec doesn't provide specific details about it.

However, following [RFC 6570](https://tools.ietf.org/html/rfc6570#section-2.3) it looks like characters other than alphanumeric or underscore cannot be used unless they are decoded. I'd leave the decision on whether to support it up to you, but I believe it's ok to not provide support for it.

**Comment by mohsen1** [comment]
The RFC 6570 limitation is not good enough for Swagger. A path parameter that is just a number (`/{1}`) doesn't make much sense for example. Other example is `%`. It should not be allowed in path parameter name since it's going to complicate a lot of things.

**Comment by webron** [comment]
The RFC limitation would probably have to be good enough for Swagger as I suspect that the next version of the spec would refer to it more explicitly and depend on it for the restrictions and behavior regarding path templating.

**Comment by mohsen1** [comment]
Is there an open issue/proposal for this?

**Comment by webron** [comment]
Too many, @mohsen1. Too many :)

**Comment by mohsen1** [comment]
Could you link on of many to this so we can track it?

**Comment by webron** [comment]
https://github.com/swagger-api/swagger-spec/search?q=6570&type=Issues&utf8=%E2%9C%93 :stuck_out_tongue_winking_eye:

**Comment by whitlockjc** [comment]
pillarjs/path-to-regexp/issues/63 punted on this and I think I will as well.  We can reopen it if someone feels we need to, and by _"need"_ I mean has a current use case for it, not some _"it sure would be nice"_ scenario.

**Comment by cjolif** [comment]
I do have a use-case :( I was given some guidelines on how to name an API, that guideline include "dash" in path parameters and I can't make it work :(

**Comment by cjolif** [comment]
@whitlockjc if you don't intend to fix it would there's be a relatively easy way to plugin in the desired behavior into swagger-tools from the outside?

@webron 

>The RFC limitation would probably have to be good enough for Swagger as I suspect that the next version of the spec would refer to it more explicitly and depend on it for the restrictions and behavior regarding path templating.

I still don't see the spec depending this right? Is there a place I could point people to saying that this might not be a good idea to rely on "-" here?

**Comment by whitlockjc** [comment]
I'll give it some thought.
