### ISSUE TITLE
API Failing To Work After Latest Updates

### ISSUE THREAD

**Issue by atom0s** [apigee-127/swagger-tools#292]
I have posted my issue(s) over on StackOverflow as well which can be seen here:
http://stackoverflow.com/questions/33376711/swagger-updates-breaks-api-usage

Since upgrading our deps. which included swagger-tools, we have seen major breakage in our API parsing. As is, our project will no longer start due to lots of errors from calling swagger-tools function initializeMiddleware.

**Comment by whitlockjc** [comment]
Can you inspect the resolved Swagger document provided by swagger-parser?  swagger-tools hasn't changed its logic in quite some time so I'm not sure what would change for you but not change for others.

**Comment by atom0s** [comment]
Yes, the object is created and marked as swagger 2.0 as seen here:
![http://i.imgur.com/z7U21LH.png](http://i.imgur.com/z7U21LH.png)

Stepping into SwaggerTools.initializeMiddleware shows that the call fails while trying to handle the parameters. Inside of swagger-tools\lib\specs.js there is a line that states:
```
    seenParams.push(parameter.name + ':' + parameter.in);
```

While this happens, my parameters are references so the .name and .in are not valid here. The parameter at this point looks like this:
![http://i.imgur.com/EQP1Btt.png](http://i.imgur.com/EQP1Btt.png)

**Comment by whitlockjc** [comment]
Seeing `undefined` in the error messages tells me swagger-tools cannot find the reference.  From your Swagger, I cannot see this.  I just tested based on the snippets you gave me, swagger-tools runs fine.  I'll need a more complete Swagger to reproduce locally.  It would be nice to see the actual parameters array after being dereferenced.

**Comment by atom0s** [comment]
Is there a private method I can send you the complete swagger yaml files we are using? They are private so I cannot post them here publicly.

**Comment by atom0s** [comment]
Actually it seems that the issue is because we were using swagger-tools.parse instead of swagger-tools.validate. Prior, this seemed to handle references automatically. However in the latest version it seems that it does not.

**Comment by whitlockjc** [comment]
`swaggerTools.parse` isn't a thing.  :)

**Comment by atom0s** [comment]
Erm meant swagger-parser.validate and .parse lol. Using .parse and passing the returned api object to swagg-tools functions was broken between versions recently. (parse no longer resolves references etc.)

**Comment by whitlockjc** [comment]
Gotcha.
