### ISSUE TITLE
Validation issue with Content type/charset

### ISSUE THREAD

**Issue by alexist** [apigee-127/swagger-tools#295]
Hi,

I have a put operation that declare :
 "consumes" : [ "application/json; charset=utf-8" ],

When client execute the PUT :
 curl -X PUT http://localhost:8080/adresseElectronique  -H 'Content-Type: application/json'  -d '{"email":"test@test.fr"}'
or
 curl -X PUT http://localhost:8080/adresseElectronique  -H 'Content-Type: application/json; charset=utf-8'  -d '{"email":"test@test.fr"}'
 validateContentType in swagger-tools/lib/validators.js is throwing the error 
"Error: Invalid content type (application/json). These are valid: application/json; charset=utf-8"

If i remove charset=utf-8 in consumes attribute, validation is working.

**Comment by whitlockjc** [comment]
I was unaware that the `consumes`/`produces` values allowed `Content-Type` parameters in it but looking at the Swagger 2.0 [mime type](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#mimeTypes) documentation, it does seem valid.  I'll see what @webron thinks but it appears I will have to check for an exact `Content-Type` match and a match without the parameter *(`charset`)*.

**Comment by whitlockjc** [comment]
@webron If the consumes is `application/json; charset=utf-8`, shouldn't `application/json` and `application/json; charset=utf-16` both fail validation?  I mean, if you explicitly set the charset in your consumes/produces, you're clearly stating that you only consume/produce content types having that charset?

**Comment by whitlockjc** [comment]
Here are the scenarios with how I see them making sense:

1. `consumes/produces` does not include a `charset`:
    a. `charset` provided: Has no impact
    b. `charset` not provided: Has no impact
2. `consumes/produces` includes a `charset`:
    a. `charset` provided: Allow if charsets are the same, deny otherwise
    b. `charset` not provided: Denied since you explicitly said you will only produce a specific charset

@alexist Any chance you can chime in on how you expect it to work?  @webron will be responding sometime soon so we'll get the official Swagger opinion from him.

**Comment by fehguy** [comment]
It is legal in swagger to declare the charset in the `consumes` or `produces` but it's probably not terribly helpful to do so.  The server should be matching based on the primary content-type then the _preferred_ charset.

That said, I suggest to folks that the content-type is declared in the swagger spec, and the character set omitted.  For this issue in swagger-tools, the tools should match on being _compatible_ (i.e. ignoring the charset) and then inspecting the media type parameter (i.e. charset).

**Comment by whitlockjc** [comment]
Thanks.  So the plan is just to update swagger-tools to handle charset in the consumes/produces but having charset in the consumes/produces will not impact validation of requests/responses.

**Comment by whitlockjc** [comment]
`swagger-tools@0.9.10` is out and the fix to this issue is included.

**Comment by webron** [comment]
You're so cool, @whitlockjc.
