### ISSUE TITLE
Security Requirements: Logical `OR` clarification/bug

### ISSUE THREAD

**Issue by thefotios** [apigee-127/swagger-tools#296]
I've been trying to find an example using a `logical or` for security requirements. According to the [swagger 2.0 spec][1],
> The object can have multiple security schemes declared in it which are all required (that is, there is a logical AND between the schemes).

The [schemas you're using in your tests][2] for `and` and `or` are identical and I think the [`and` tests][3] are broken. The description says that it `should not authorize` if one is false, but they `expect(200)`.

[1]: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#security-requirement-object
[2]: https://github.com/apigee-127/swagger-tools/blob/master/test/2.0/test-middleware-swagger-security.js#L118-L136
[3]: https://github.com/apigee-127/swagger-tools/blob/master/test/2.0/test-middleware-swagger-security.js#L397-L449

**Comment by whitlockjc** [comment]
I'm going to bring in the author, @theganyo, to see if he can shed some light on the security stuff.

**Comment by theganyo** [comment]
Yes, it appears something was lost in translation. This was the original schema I wrote and submitted: https://github.com/apigee-127/swagger-tools/pull/83/files#diff-d9b11e0c98022ec8668fcfa70ecca81fR20. I think that when it was rewritten, the differences were lost.

**Comment by whitlockjc** [comment]
I very well could had broken something during a refactoring.  I'll look to see what needs changing based on @theganyo's original PR but if you have suggestions or see something, let me know.

**Comment by thefotios** [comment]
This is definitely a bit confusing. If I'm reading the [spec][1] correctly, it says that an individual operation (or the whole app) can have a `security` object that should be an `array` of `securityRequirement` objects whose values should be `strings`. So technically @theganyo's  [original examples][2] were both valid. 

When it says the "(it) can have multiple security schemes which are all required", to me, that sounds like 
```json
"security": [
  { "myOauth": ["scope"] },
  { "apiKey": [] }
]
```
and that the result of that should be a logical `AND`. That, however, is the opposite of @theganyo's fixture data. The spec also doesn't address how multiple values inside of a `securityRequirement` object should be handled (and I haven't been able to find any examples to support either scenario).

[1]: https://github.com/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json#L1161-L1177
[2]: https://github.com/apigee-127/swagger-tools/pull/83/files#diff-d9b11e0c98022ec8668fcfa70ecca81fR20

**Comment by whitlockjc** [comment]
Maybe @webron can chime in.  If we can figure out how to handle them, we can fix the middleware and its tests.

**Comment by theganyo** [comment]
Hmm. Perhaps the spec document has changed in the mean time, because I remember this being clearly spelled out as I implemented it when I originally wrote the security middleware. (shrug)

**Comment by webron** [comment]
Okay, I've tried finding a sample I used once, but can't find it, so I'll base it on something from here.

```json
"security": [
  { "myOauth": ["scope"] },
  { "apiKey": [] }
]
```
That means either `myOauth` OR `apiKey` is required.

```json
"security": [
  { 
  	"myOauth": ["scope"],
  	"apiKey": [] 
  }
]
```
This means both `myOauth` AND `apiKey` are required.

Haven't followed all the links out here, and that was the behavior since day one of the spec. Hope it helps clarifying things.

And yes, you can combine both structures to have an OR between complex AND structs.

**Comment by theganyo** [comment]
Thanks, @webron. Good to know I interpreted it correctly. :)

**Comment by webron** [comment]
![dc-comics-batman-logo_0](https://github-cloud.s3.amazonaws.com/assets%2F241629%2F10956526%2F33ac47da-8311-11e5-8345-285256110ce4.jpg)
