### ISSUE TITLE
Errors are being silenced

### ISSUE THREAD

**Issue by mershal** [apigee-127/swagger-tools#298]
Hi,

When I initialize swagger router using the following command:
```
app.use(middleware.swaggerRouter(routerOptions));
``` 
then swagger requires each of the controllers that are being used in the swagger doc.
If an error is thrown during this process, it is being silenced; meaning it is not being reflected. 
Then the rest of the commands are not being called in the swagger doc initialization:
```
swaggerTools.initializeMiddleware(doc, function(middleware) {
    // initialization code

    app.use(middleware.swaggerRouter(routerOptions));    
 
   // code that is never being executed because the above code failed
})
```

**Comment by whitlockjc** [comment]
Do you have an example?  I *think* I understand but a reproduction recipe would remove the guess work.

**Comment by mershal** [comment]
Yes. I try to require some module within my controller (which is specified in the swagger doc), from my `node_modules` directory. From some reason the module was not downloaded properly, and was not in the `node_modules` directory. 
I didn't get any `Cannot find module` error, and the server was not started. Unfortunately there was not indication for the reason that caused this, and in order to solve this issue, i used tons of `console.log`s in your code, and in mine either, until I figured it out.

Thanks for your feedback :+1:

**Comment by whitlockjc** [comment]
Does the server terminate?  I have unit tests where failures happen when initializing the router middleware and swagger-tools will log the error and terminate the process.  I'm also looking at the code involved and I don't see any places where we're trapping errors and blindly ignoring them.  I will try to create a unit test but a review of the code doesn't seem to shed light on the situation.

**Comment by mershal** [comment]
By server you mean swagger? Because if so, then it never starts.
I can tell for sure that the process does not terminate.
I thought maybe it gets lost on express `use` function, but I wasn't able to find something.
Any thoughts?

**Comment by whitlockjc** [comment]
Can you reproduce this programmatically without your code specifically?  Something you could attach to this issue or throw into a gist or something else?  That would speed things up but I can definitely try to create a reproduction recipe in a couple hours if not.

**Comment by mershal** [comment]
I generated a simple code that fails the same way, but without all my classes, and I did get notified about an error, which means this is my bad and not yours. 
Sorry for the misleading issue, and many thanks on your replies!

**Comment by whitlockjc** [comment]
No problem.  Let me know if I can help further.
