### ISSUE TITLE
Future of this project?

### ISSUE THREAD

**Issue by tanzim** [apigee-127/swagger-tools#299]
Apologies for the attention grabbing headline. It seems that the swagger-node project has moved away from using swagger-tools (by virtue of swagger-express-mw > swagger-node-runner removing dependency on swagger-tools). So where does swagger tools fit into the ecosystem? 
Ideally, I'd like to *just* use the swagger-node project, but due to issues like swagger-node not having direct support for displaying the swagger docs etc. a swagger-tools dependency is still needed, which seems to be a bit messy.

**Comment by whitlockjc** [comment]
swagger-tools started out as a validation CLI and quickly became a lot more.  Now it's an API, a CLI and middleware.  We've been planning on refactoring the project out into multiple projects specific to their function.  We've already broken out the API portion of swagger-tools into [sway](https://github.com/apigee-127/sway).  *(Sway does not have Swagger 1.2 support at this time but it sway was written with a plugin system to allow it if we ever felt so inclined.)*  We're in the process of creating [sway-connect](https://github.com/apigee-127/sway-connect) as a way to write a *reference implementation* of Swagger-driven middleware that would replace the middleware in swagger-tools.  The CLI will likely end up being some sort of *Swagger linter* at some point but swagger-node already has a CLI that does conversion/validation.

All of this being said, a number of the tools that were built on top of swagger-tools *(swagger-editor, swagger-node-runner)* are in the process of migrating off of swagger-tools in favor of the new Sway-based solutions.  I *think* swagger-node-runner has completed its first pass at this but i'm not 100% sure.

All of this being said, swagger-tools will continue but it will likely be broken up.  Once it's been broken up completely, all pertinent issues will be ported to the new repository.  swagger-tools and all new projects that come from its refactoring will continue to be supported but just know, there are some things that to fix/support in swagger-tools would require a big rewrite and I'm not sure that's time well spent right now.  *(Example: #227)*

I hope this helps clear things up but just know, I have no desire to just stop supporting swagger-tools.  I also hope that the spin off projects end up being used as much as swagger-tools has.  It's been a lot of fun providing these projects and I would love to continue supporting the Swagger needs of the Node.js community.  *(Not to imply that I'm the only one doing it, just saying I've enjoyed playing a role.)*

**Comment by tanzim** [comment]
@whitlockjc thanks, very helpful and I am grateful for your work so far. 
Having said that, for someone new to the world of node and swagger, the existence of all the various elements can be a bit daunting. 
For example, once can still have a working node+swagger project without knowing anything about swagger-node, just by using swagger-tools. It would help if the project goals were stated upfront so that it's easier to pick the right thing (i.e. use swagger-node if you want x vs use swagger-tools if you want y). Hope that makes sense.

**Comment by theganyo** [comment]
@tanzim Also note that there's nothing about swagger-ui that requires swagger-tools. We'll be adding official support for a swagger-ui in the future. But if you need to, it should be as easy to to add swagger-ui to a swagger-node project as you would in any connect-based project via a simple piece of middleware.

**Comment by tanzim** [comment]
@theganyo Correct. Right now I've just done that :+1:
