### ISSUE TITLE
Can't get required field validation working

### ISSUE THREAD

**Issue by mattriley** [apigee-127/swagger-tools#301]
Hi. I'm trying to use model validation but can't seem to get required fields to be validated. I have a model schema similar to:

```json
    "Model": {
      "properties": {        
        "field": {
          "type": "string",
        }
      },
      "required": ["field"]
    }
```

I'm using code I found in the documentation to validate. `model` is the object to validate. Validation seems to pass even though `model` does not contain `field`.

```javascript
  var spec = require('swagger-tools').specs.v2; // Using the latest Swagger 2.x specification
  var swaggerObject = require('./swagger.json'); // This assumes you're in the root of the swagger-tools

  spec.validateModel(swaggerObject, '#/definitions/Model', model, function (err, result) {
    if (result) {
      console.log('Swagger model failed validation:');

      console.log('Errors');
      console.log('------');

      result.errors.forEach(function (err) {
        console.log('#/' + err.path.join('/') + ': ' + err.message);
      });

      // Since this is schema validation, warnings shouldn't be populated
      context.fail(err);
    } else {
      console.log('Swagger model is valid');
    }
  });
```

Am I doing something wrong? Thanks.

**Comment by whitlockjc** [comment]
It depends.  What is the value of `model`?  I'll give you more details when I know what you expect to produce a validation error.

**Comment by whitlockjc** [comment]
I'm closing this as I do not have enough information to proceed.  I can see that you're omitting the `type` parameter for your `Model` definition and that will cause issues if you're expecting non-object values to fail validation.
