### ISSUE TITLE
Specification.prototype.validateModel can't validate Array data ?

### ISSUE THREAD

**Issue by jscti** [apigee-127/swagger-tools#303]
Hi

I'm using `lib/specs.js::Specification.prototype.validateModel` function to validate data agaisnt Schema Definition on the fly ...
It's working well when my data/schema consists of an Object like :
``{
    data : [1,2,3]
}``

But when I use directly an array structure, the validation seems to not handle it :
``[1,2,3]``
Error : ``Error: json must be an object
    at Object.findRefs (D:\users\xxxx\node_modules\swagger-tools\node_modules\json-refs\index.js:219:11)
    at addExternalRefsToValidator (D:\users\node_modules\swagger-tools\lib\specs.js:63:38)
``

In both case, the swagger specification is respected and the structure is totally valid. (loads well in swagger-ui/editor).
Am i missing something ?

Thanks

**Comment by whitlockjc** [comment]
There is an open but in json-refs for this: https://github.com/whitlockjc/json-refs/issues/39  I'll keep this issue open until I update swagger-tools with the latest json-refs once the bug is fixed.

**Comment by whitlockjc** [comment]
json-refs has been updated to fix this issue but there is a slight problem with adding the newer version of json-refs to swagger-tools.  json-refs' API is now Promise based and that breaks some things.  I have the work done to support this with tests but I'm having an issue with getting the tests passing.  Just updating you to know I didn't forget about you.

**Comment by whitlockjc** [comment]
Done.  I'll get a release out soon.

**Comment by whitlockjc** [comment]
`swagger-tools@0.9.10` is out and the fix to this issue is included.

**Comment by jscti** [comment]
You rock, thank !
