### ISSUE TITLE
When having multiple security handlers, logic AND is not respect

### ISSUE THREAD

**Issue by luofan189** [apigee-127/swagger-tools#305]
The issue is that I have two security handlers, handler1 and handler2. handler1 succeeds and handler2 fails. I assume the middleware will return errors, but it actually advance to next(). I believe this is a bug. Please help me with this.

**Comment by whitlockjc** [comment]
This was recently documented here: https://github.com/apigee-127/swagger-tools/issues/296#issuecomment-153891769  Update this issue with the results.

**Comment by luofan189** [comment]
@whitlockjc thanks a lot for pointing out that reference. It worked as it described, it does support both logic AND and logic OR

In case other people have the same question, here is the yaml:

OR
```
security:
   - handler1: []
   - handler2: []
```

AND
```
security:
  -
    handler1: []
    handler2: []
```

Again, thanks a lot!
