### ISSUE TITLE
Swagger security and oauth2server

### ISSUE THREAD

**Issue by carama-s** [apigee-127/swagger-tools#306]
Hi,

Before to add swagger in my project, I used <b>node-oauth2-server</b>:
``` 
app.get('/', app.oauth.authorise(), function (req, res) {
  res.send('Secret area');
});
```
But I don't understand how can I implement the Oauth authentification with swagger.

My security middleware is defined like that: 
```
app.use(middleware.swaggerSecurity({
   OAuth2: function (req, def, scopes, callback) {
      callback()
   }
 }));
```
Obviously, with callback(), all my API requests are working without authentification needed. But how to add the Oauth authentification provided by <b>app.oauth.authorise()</b> in this case ?

I tried something like that but it's not working:
```
app.use(middleware.swaggerSecurity({
   OAuth2: [app.oauth.authorise(), function (req, def, scopes, callback) {
      callback()
   }]
 }));
```

Ps: I added the securityDefinitions and security in my different YAMLs, this part is ok.

Thanks !

**Comment by whitlockjc** [comment]
You should be able to do this programmatically.  Basically, `app.oauth.authorize()` is just a function that itself has a callback.  So you should be able to do something like this:

```js
app.use(middleware.swaggerSecurity({
   OAuth2: function (req, def, scopes, callback) {
      app.oauth.authorize(function (err, user) {
        // Handle Passport.js response here by returning an Error when not authorized
      });
   }
 }));
```

There is an open issue *(#81)* about how this middleware doesn't use consistent middleware functions for its security handlers but other than that, it should return `null` or `undefined` for valid requests and an `Error` for invalid requests.  *(Also, you can attach the following properties to the error and they can be relayed to the end user: `code`, `headers` and `state`.  Of course, `message` is always provided as well.)*

**Comment by carama-s** [comment]
Thanks !

But I looked at the code of the Authorise function and it seems I can't get a callback: https://github.com/thomseddon/node-oauth2-server/blob/master/lib/authorise.js

Maybe I should manually do the verification by my self.

**Comment by whitlockjc** [comment]
Yup, my bad...I misread this and assumed it was a Passport.js implementation.  When I look at the `Authorise` constructor *([lib/authorise.js#L38](https://github.com/thomseddon/node-oauth2-server/blob/master/lib/authorise.js#L38))*, it does have a `next` argument which is the callback it will call.
