### ISSUE TITLE
Swagger with custom configuration not loading params

### ISSUE THREAD

**Issue by nazarhussain** [apigee-127/swagger-tools#311]
I am facing issue while fetching request params. Is it something related to swagger-tools. Please suggest. 

https://github.com/swagger-api/swagger-node/issues/332

**Comment by nazarhussain** [comment]
Solved the issue by adding `swagger_params_parser` layer in `swagger_controllers` under config. This was not mentioned in any guide/wiki. Please update wiki for it. 

More details are on: http://stackoverflow.com/questions/34306720/swagger-with-custom-configuration-not-loading-params/34306770#34306770

**Comment by theganyo** [comment]
For posterity: https://github.com/theganyo/swagger-node-runner/releases/tag/v0.6.0
