### ISSUE TITLE
collectionType 'multi' parses single parameter incorrectly

### ISSUE THREAD

**Issue by perrydt** [apigee-127/swagger-tools#313]
I'm using a 2.0 specification and trying to define a 'multi' array parameter:

        - name: providerName
          in: query
          description: filter packages by provider name
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi

This works fine when there's >=2 query parameters:

    .../url?providerName=abc&providerName=xyz

    req.swagger.params.providerName.value: [ 'abc', 'xyz' ]

But with only one, this happens:

    .../url?providerName=abc

    req.swagger.params.providerName.value: [ 'a', 'b', 'c' ]

The issue seems to be that qs sets req.query['providerName'] to an array in the first example but a string in the second, and the code in swagger-metadata.js doesn't handle this: 

    value = _.map(value, function (item, index) {
      return convertValue(item, _.isArray(schema.items) ? schema.items[index] : schema.items);
    });

If it's a string, the 'map' call ends up splitting it into an array of characters.

I haven't been able to find a workaround for this; obviously we want our params in the swagger controller to be an array whether there's only one query parameter or more than one.  Using a different collection type, e.g. 'csv', solves this, but requires our consumers to stuff the values into a single query parameter with separators and that's difficult because the values can contain any character and introduces issues with escaping the strings.  Is this behavior intended?

**Comment by whitlockjc** [comment]
I can see why it's happening and it's definitely not intended.

**Comment by whitlockjc** [comment]
`swagger-tools@0.9.10` is out and the fix to this issue is included.
