### ISSUE TITLE
Question about consuming application/xml payload

### ISSUE THREAD

**Issue by jcferrer** [apigee-127/swagger-tools#316]
I am trying to consume a simple xml payload. Is there any working swagger example anybody can share?.

I am using 
```
consumes:
  - application/json
  - application/xml
  - application/x-www-form-urlencoded

....

        - in: body
          name: body
          description: XML body
          required: true
          schema:
            $ref: "#/definitions/RequestBody" 

.....

definitions:

  RequestBody:
    properties:
      message:
        type: string
```

When using Content-Type: application/xml the validator throws: 
```
Parameter (body) value expected to be an array/object but is not
```

The only way I can get pass the validator is when using Content-Type: application/x-www-form-urlencoded, with a body like:  
```message="<something>,,,,</something>"```

Can somebody share some light?

Thanks

JC

**Comment by whitlockjc** [comment]
swagger-tools does not do any body parsing itself.  Instead, we rely on your server being configured to do this for you.  When it comes time to do validation, whether your body was JSON, XML, YAML or whatnot, the validation will happen against JavaScript types.  So you need to wire in a body parser that can do XML parsing which will take your XML string body and parse it into the proper JavaScript type so JSON Schema validation can occur.  I know there are a number out there but I've never used them.

**Comment by jcferrer** [comment]
Thanks Jeremy, 

I guess, if I understand correctly, since let's say, I am using swagger-tools as part of the a127-apigee middleware, that means that I would have to wire my body parser middleware first, right?

i.e.
```
    app.use(middleware.mine(config));
    app.use(a127.middleware(config));
```

**Comment by whitlockjc** [comment]
Yes, that is correct.  swagger-tools only includes request parsing middlewares as a convenience and we do not include an XML parsing middleware.

**Comment by whitlockjc** [comment]
Since this is not an issue with swagger-tools, I'm closing this.  Please let me know if I can help further.
