### ISSUE TITLE
Discuss swaggerMetadata namespacing its processed request parameters

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/swagger-tools#32]
Typical Node.js development uses `req.params` to get access to request parameters.  With swaggerMetadata, we intentionally namespaced them in `req.swagger.params`.  Let's run this by the community to see what their thoughts on doing this are.

**Comment by Emmpa** [comment]
I know this is coming in late, but I thought I would offer a bit more feedback:

1) Swagger-tools utilizes tools to set req.query and req.body, but it avoids req.params? Seems like it's breaking the pattern...
2) Node Express prevents modifying the req.params with middleware, so the suggestion by BigstickCarpet to add middleware would not work.
3) I think a simple solution would be to modify swagger-router.js to add:
```javascript
var swaggerParamsToParams = function(req){
  _.forEach(req.swagger.params, function(param, key){
    if (param.schema.in === 'path')
      req.params[key] = param.value;
  })
}
```
just before calling the handler. That wouldn't break any middleware, but it would also allow the use of the more common req.params variable

**Comment by whitlockjc** [comment]
1) swagger-tools does nothing of the sort regarding `req.body` or `req.query`.  The server middleware is responsible for these things.  And while swagger-tools provides default middleware for you so things _just work_, it's up to you to own this if need be.  `req.swagger` is the only object swagger-tools creates/manipulates

2) swagger-tools does not alter `req.params`
3) I don't know that we have a problem here so the solution doesn't make much sense to me
