### ISSUE TITLE
Error: Cannot resolve the configured swagger-router handler: ...

### ISSUE THREAD

**Issue by uwieske** [apigee-127/swagger-tools#321]
Hi 

Yesterday I downloaded Swagger editor, because I wanted to try out swagger. 
I did the YAML specification part and generated NodeJS server. Unfortunately I got the error below when I tried to invoke the POST operation (add) through Swagger UI (http://localhost:8080/docs) 
(A the full stacktrace has been added at the end of my ticket)

"Error: Cannot resolve the configured swagger-router handler: addObituary ........"

I am wondering what is the problem? Is there an error in the server generation code itself or  am I missing something in my specification?
I found a similar reported issues such as #274 and #312. 

Kind regards,
Urso

My npm and node versions:
>npm -v
3.5.4

>node -v
v4.2.2

Attached Yaml specification:
[swagger_ob.zip](https://github.com/apigee-127/swagger-tools/files/90334/swagger_ob.zip)

Error: Cannot resolve the configured swagger-router handler: addObituary<br> &nbsp; &nbsp;at swaggerRouter (C:\Users\uw\WebstormProjects\condreg\generated\nodejs-server\node_modules\swagger-tools\middleware\swagger-router.js:414:18)<br> &nbsp; &nbsp;at call (C:\Users\uw\WebstormProjects\condreg\generated\nodejs-server\node_modules\connect\index.js:239:7)<br> &nbsp; &nbsp;at next (C:\Users\uw\WebstormProjects\condreg\generated\nodejs-server\node_modules\connect\index.js:183:5)<br> &nbsp; &nbsp;at C:\Users\uw\WebstormProjects\condreg\generated\nodejs-server\node_modules\swagger-tools\middleware\swagger-validator.js:350:30<br> &nbsp; &nbsp;at C:\Users\uw\WebstormProjects\condreg\generated\nodejs-server\node_modules\async\lib\async.js:52:16<br> &nbsp; &nbsp;at C:\Users\uw\WebstormProjects\condreg\generated\nodejs-server\node_modules\async\lib\async.js:361:13<br> &nbsp; &nbsp;at C:\Users\uw\WebstormProjects\condreg\generated\nodejs-server\node_modules\async\lib\async.js:52:16<br> &nbsp; &nbsp;at async.forEachOf.async.eachOf (C:\Users\uw\WebstormProjects\condreg\generated\nodejs-server\node_modules\async\lib\async.js:236:30)<br> &nbsp; &nbsp;at _asyncMap (C:\Users\uw\WebstormProjects\condreg\generated\nodejs-server\node_modules\async\lib\async.js:355:9)<br> &nbsp; &nbsp;at Object.map (C:\Users\uw\WebstormProjects\condreg\generated\nodejs-server\node_modules\async\lib\async.js:337:20)
Response Code

**Comment by whitlockjc** [comment]
You need to use `x-swagger-router-controller` and set its value to be that of the controller name.  This is documented here: https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#how-to-use  Also, we have an example project here: https://github.com/apigee-127/swagger-tools/tree/master/examples/2.0

I'm closing this unless you find that swagger-tools is not working.  If you find that is the case, please reopen with a reproduction recipe.

**Comment by nnonaf** [comment]
**please am still having this issue, below is my code.**
  x-swagger-router-controller: busStop
    # x-swagger-router-handle-subpaths: true,
    x-a127-apply: 
      spikearrest: {}
      defaultQuota: {}    
    get:
      summary: get bus stop
      description: query bus stop that match query parameters
      operationId: getBusStops
      # parameters:
      # - in: header
      #   name: authorization
      #   type: string
      #   # required: true
      tags: 
        - busStop
      responses:
        200:
          description: OK
          schema: {}
        default:
          description: Default Response 
          schema:
            $ref: "#/definitions/DefaultResponse"


**below is response:**

{"message":"Cannot resolve the configured swagger-router handler: busStop_getBusStops"}
