### ISSUE TITLE
Adding validatorUrl to swagger-ui middleware

### ISSUE THREAD

**Issue by pkimbrel** [apigee-127/swagger-tools#323]
When setting up the **swagger-ui** in the **swagger-tools** middleware, it would be great if I could I set the "validatorUrl" on the swagger-ui index.html to change or disable swagger validation.  swagger-ui supports this, but I cannot pass the validator URL from swagger-tools to swagger-ui.

This would be used for internal API's that cannot be read from the public swagger validation tool.

Example:
`app.use(middleware.swaggerUi({validatorUrl: null}));`

This would be useful for passing any number of swagger-ui parameters to the swagger-ui initialization.

**Comment by whitlockjc** [comment]
There's no reason we couldn't do this but in reality, the swagger-ui we ship with swagger-tools is there merely as a convenience and any customizations you need, whether UI related or other *(like this one)*, really should be done by deploying your own swagger-ui.

I'm not going to close this because I can accommodate but you could do this yourself pretty easily by deploying your own swagger-ui and using `options.swaggerUiDir` when calling `middleware.swaggerUi`.

**Comment by zdila** [comment]
+1 for this

In our case we don't want to do separate deployment of SwaggerUI. We want it to be part of our server app as a dependency which will be updated automatically just by running `npm update`.

**Comment by whitlockjc** [comment]
So the purpose of this would be to provide some URL that actually resolves when passed to the online Swagger validator badge?

**Comment by sherpya** [comment]
the default is not null so it will always complain if you are using private addresses

**Comment by whitlockjc** [comment]
Right, if you have a `localhost` or an address that is unreachable, the online validator badge will not be able to validate the Swagger document and will fail.  I really wish the online validator was better.

**Comment by sherpya** [comment]
`swagger-ui` automatically skips the badge if the url is `localhost` but not for private addresses, it would be nice to have the parameter customizable, right now I need to patch `./node_modules/swagger-tools/middleware/swagger-ui/index.html` by hand

**Comment by whitlockjc** [comment]
Agreed, that's why this is still open.  :)

**Comment by mankeli** [comment]
+1 for this. Would be great for private API's

**Comment by MaxKramnik** [comment]
Is there a reason to not always have validatorUrl as null in index.html?

**Comment by whitlockjc** [comment]
That's the plan for the fix.
