### ISSUE TITLE
Swagger tools not passing jshint

### ISSUE THREAD

**Issue by supritashankar** [apigee-127/swagger-tools#324]
Swagger tools is not passing jshint. To reproduce this - once can install the https://github.com/victorporof/Sublime-JSHint Sublime plugin and see that there are so many errors. 

the jshint ignore lines don't work .. in other words it takes into account the jshint lines and throws errors. 
does anyone see this too? v0.9.11

can u please help - @whitlockjc @theganyo

**Comment by whitlockjc** [comment]
swagger-tools is passing JSHint, otherwise the build would be failing *([which it's not](https://travis-ci.org/apigee-127/swagger-tools))*.  Not only that but I just ran `gulp lint` and `jshint .` and both ran without issue.  Chances are that the Sublime JSHint plugin is busted because I cannot reproduce this, Gulp cannot reproduce this and Travis CI cannot reproduce this.

**Comment by whitlockjc** [comment]
I just tried Atom, Emacs, IntelliJ and Visual Studio Code.  All four are clean with regard to JSHint.

**Comment by supritashankar** [comment]
@whitlockjc We are using swagger tools and our builds are failing :(

**Comment by whitlockjc** [comment]
I bet I know what is going on.  You're linting upstream/vendor code, like swagger-tools, and it is failing.  Why would your project's lint checks be applied against upstream/vendor code?  You can never guarantee that this will pass.

I'm not seeing how this is a swagger-tools issue.  The swagger-tools code passes lint checks as defined in the [swagger-tools .jshintrc](https://github.com/apigee-127/swagger-tools/blob/master/.jshintrc) and that is all I can do.

**Comment by supritashankar** [comment]
@whitlockjc To give more context to the problem. We are doing 'grunt unit' which has a mochacli file which executes all of the unit tests. One of the options being that of 'check-leaks:true' .. this checks for global variable leaks. You can see that here (https://www.npmjs.com/package/grunt-mocha-cli) .. this is failing for swagger tools. We were thinking that when we use 'use strict' this should ideally be caught by jshint. @whitlockjc your thoughts on this? If we comment out swagger tools .. all of the test passes. If we comment out 'check-leaks' all of the test passes too. But both together - (we have swagger tools and check-leaks uncommented) then the tests fail.

**Comment by whitlockjc** [comment]
How are you using swagger-tools?  Did you `npm install swagger-tools` or are you using the browser builds?  What about sharing some errors you're seeing instead of just saying it's _" not passing"_.

In the end, the point I'm trying to make is that you running upstream/vendor code through JSHint or any type of validator is almost guaranteed to fail.  Not only can you not guarantee that the upstream/vendor code uses linting but you cannot guarantee that the upstream/vendor code uses the same linter or even the same lint rules.

**Comment by supritashankar** [comment]
@whitlockjc I am *not* running upstream/vendor code .. I understand that :)

I am doing npm install swagger-tools. There are *no errors* it just says that it "aborted with warnings". 
I gave you all the information we had. I thought sharing here will help me debug this more  - I didn't expect an instant solution. More like, potential pitfalls that I need to watch out for. 

We will figure it out. Thank you for taking time out to reply :)

**Comment by whitlockjc** [comment]
I don't mind helping, I'm just not sure what is going on here.  You're saying swagger-tools is not passing jshint when all the information I have says otherwise.  I'm just asking for more information.  As for you not validating upstream/vendor code, you must be or there would not be an issue with swagger-tools not passing jshint.  Help me help you.

**Comment by whitlockjc** [comment]
Anything that is specific to the problem, please share.  When you run `npm install swagger-tools --save`, what output do you get?  What are the errors you get when you run `grunt unit`?  Anything specific that I can use to help diagnose.

**Comment by supritashankar** [comment]
this is my mochacli file which is executed when I run *grunt unit* 
https://github.paypal.com/gist/supshankar/1025a9a07902c2a9b9f3

this is how I am using swagger-tools https://gist.github.com/supritashankar/909e377a9dc9acdc8241

If I comment out *check-leaks* in the first line then all tests pass. If I comment out *swaggerTools.initializeMiddleware* then it passes too. But both together does not pass.

So one of my guesses is that there is a global variable leak in swagger tools ? (Not sure. I am just *guessing*) ..

**Comment by whitlockjc** [comment]
The first link is not accessible by me.  As for the second, where is `swaggerTools

**Comment by supritashankar** [comment]
@whitlockjc Yes I have declared it. I had declared it on the top of the file and didn't include it thats why you don't see it :) Now I have included it. Also I have made the first link accessible.

No problem at all :) I have been stuck on this issue because of which our builds are not passing .. Thats why I asked. I understand you must be getting a lot of issue and you must be busy .. so no problem at all :+1: I completely understand.

**Comment by whitlockjc** [comment]
Can I see the error output?  swagger-tools doesn't expose any global variables itself, nor does it assume any are available other than the ones Node.js provide, which never trigger linters when configured properly.

**Comment by supritashankar** [comment]
No errors @whitlockjc  .. :( .. we are also struggling with the same.

**Comment by whitlockjc** [comment]
Okay, I'm lost again.  :(  The original issue was _"Swagger tools not passing jshint"_ but there are no errors being emitted or printed to the console when running `grunt unit`?  What is the output of `gulp unit`?  Any chance you can share the Mocha file in a gist, or in this issue so I can see it?  The link you provided is not accessible.

**Comment by supritashankar** [comment]
this is the link of mochacli -  https://gist.github.com/supritashankar/5d4dea9367c4b5247ec8

*check-leaks* is causing the problem.

**Comment by whitlockjc** [comment]
What is the complaint from `check-leaks`?  I mean, there has to be something printed to screen or thrown into `xunit.xml` that explains what the problem is.  There has to be some string of text that is outputted somewhere that explains what is going on.

**Comment by supritashankar** [comment]
global leak detected: Promise
Error: global leak detected: Promise
    at test/unit/controller/name-route-test.js:90:5

But there is no Promise used in any of the unit tests. It is coming from swagger-tools is my *guess* ..

**Comment by whitlockjc** [comment]
What is the code at `test/unit/controller/name-route-test.js:90:5`?  That is not swagger-tools code.  What's interesting is that swagger-tools itself doesn't use the `Promise` object but json-refs, one of swagger-tools' dependencies, does.  Unfortunately, this leads me back to my original question...why is your Grunt process checking, whether it's `check-leaks` or `jshint`, code that is not maintained as part of your project?  I'm not saying you're doing this deliberately, I'm wondering why grunt-mocha-cli is reporting errors outside of your project.

**Comment by supritashankar** [comment]
Yes these are our unit tests. Do not know :/
If I comment out swagger tools it all works fine. So I thought you guys might be able to help. But I am wrong I guess. This seems to be some other problem ... 
Do not waste much time on this. If you think of something .. which we have not tried .. let me know ..
Thank you Jeremy!

**Comment by whitlockjc** [comment]
You might want to bring it up with the grunt-mocha-cli project to see if it can help.  I do have one more idea, do you have a `node_modules` directory anywhere within your `test` directory?  That is the only case where I can see why grunt-mocha-cli would validate upstream/vendor code.

**Comment by supritashankar** [comment]
Fixed it finally!!  :+1:  

I added Promise to the list of globals on mochacli task list. Updated the gist.
https://gist.github.com/supritashankar/5d4dea9367c4b5247ec8

Thank you so much!

**Comment by whitlockjc** [comment]
Yes, that is one option but do you mind answering my question?  It might help others.

**Comment by supritashankar** [comment]
@whitlockjc Yes sure. No there is no node_modules inside the test directory.
Even I am curious on why it is checking for something outside of my main directory for global variable leaks.

**Comment by whitlockjc** [comment]
Well, my last idea was wrong.  ;)  Glad you got around it.

**Comment by supritashankar** [comment]
Thank you again @whitlockjc :+1:
