### ISSUE TITLE
There is no way to change api-key name

### ISSUE THREAD

**Issue by bssergy** [apigee-127/swagger-tools#330]
How can I change 'api-key' name? In my API I use 'token' key name. I know that this parameter is configuring index.html of swagger:
```
var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("api_key", key, "query");
window.swaggerUi.api.clientAuthorizations.add("api_key", apiKeyAuth);
```
But how can I do this with swagger-tools configuration?

**Comment by whitlockjc** [comment]
swagger-tools ships with swagger-ui.  Modifying the included version of swagger-ui is likely not what you want to do so I will not discuss that.  swagger-tools' swagger-ui middleware is configurable to serve any swagger-ui instance so if you download a swagger-ui distribution and alter it like you would any other swagger-ui instance, you can use `options.swaggerUiDir` when wiring up the swagger-ui middleware.  This option is documented here: https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swaggeruioptions
