### ISSUE TITLE
Silently crashes process on require() errors

### ISSUE THREAD

**Issue by steve-gray** [apigee-127/swagger-tools#331]
Hello,

The swagger-router when dynamically loading controllers during startup does not log any information regarding what happened. This causes the application process usually to exit silently under the following scenarios:

- Syntax error in controller (or any file required at any-depth from a controller)
- Any init-time/module-load time exceptions thrown on the require path.

This **may **be related to the issues in #327, but has cost myself and my team a lot of time trying to figure out that the real issue was a downstream service connection not being able to start, causing a module to fail to load, etc etc.

-Steve

**Comment by whitlockjc** [comment]
Have you tried running with the debug environment variables set?  All errors encountered should be logged.  It's documented here: https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swagger-middleware-debugging

**Comment by whitlockjc** [comment]
Yes, this is related to #327.

**Comment by steve-gray** [comment]
Yes: all that happens is that you see the line about 'Controllers:' and then it silently dies. That's why this fix. I've tested this fix with and without DEBUG set and confirmed the outputs from my examples are as expected.

**Comment by steve-gray** [comment]
Though what I've just realised is that the spacing has gone mental when copy pasting from editor to editor >_<

**Comment by whitlockjc** [comment]
I appreciate the help.  When you fix the formatting, just update the PR.

**Comment by steve-gray** [comment]
It's fixed now. If you could let me know whenever this eventually makes it into an NPM release, I'd be much appreciative as it means we can ditch our locally patched version :)

**Comment by whitlockjc** [comment]
You got it.  I really appreciate your help.

**Comment by steve-gray** [comment]
It's the least I could do. For what its worth, I've also put up an example project I'm using when teaching people about microservices using swagger. You can find it at:

https://github.com/node-templates/base-microservice-swagger

It basically uses more or less every bit of middleware you've produced, though I'd be interested to see an example of how I can add API-key support to it if you get a moment, because I struggle slightly with how the security middleware works.

**Comment by whitlockjc** [comment]
This has been resolved.
