### ISSUE TITLE
Previously validating schema fails in .9.12

### ISSUE THREAD

**Issue by dexwiz** [apigee-127/swagger-tools#334]
The newest version of swagger-tools is failing to validate a schema that passed in with .9.11. I see that error handling changed, so something that was being swallowed previously is now causing everything to fail. 

Log with `DEBUG=swagger-tools*` when running tests.

```
Initialized DB with dummy data
./api/swagger/status.yaml
  swagger-tools:middleware Initializing middleware +0ms
  swagger-tools:middleware   Identified Swagger version: 2.0 +5ms


  swagger-tools:middleware   Validation: failed +294ms
Error initializing middleware
TypeError: Cannot read property 'securityDefinitions' of undefined
    at processDocument (/home/awagoner/trust1-api/node_modules/swagger-tools/lib/specs.js:370:35)
    at validateSwagger2_0 (/home/awagoner/trust1-api/node_modules/swagger-tools/lib/specs.js:949:3)
    at validateSemantically (/home/awagoner/trust1-api/node_modules/swagger-tools/lib/specs.js:1033:5)
    at /home/awagoner/trust1-api/node_modules/swagger-tools/lib/specs.js:1226:7
    at /home/awagoner/trust1-api/node_modules/swagger-tools/lib/specs.js:1066:29
    at /home/awagoner/trust1-api/node_modules/swagger-tools/lib/specs.js:712:12
    at /home/awagoner/trust1-api/node_modules/swagger-tools/lib/specs.js:688:9
    at process._tickCallback (node.js:368:9)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3

```

Also there are no security definitions in that file.

**Comment by whitlockjc** [comment]
There was a bug in json-refs.  I'm fixing it now and will re-release.  Sorry about that.

**Comment by dexwiz** [comment]
What was the bug? I found that JsonRefs.resolveRefs was mutating `apiDOrSO` here https://github.com/apigee-127/swagger-tools/blob/master/lib/specs.js#L680 

This prevents the doc from being retrieved from the cache since its Hash changes. This leads to a cache lookup failing later, and something with no resolved refs being passed to `processDocument`.

**Comment by whitlockjc** [comment]
I have tests for that bug maybe something else is wrong.  I'll see if I can find where that is happening.

**Comment by dexwiz** [comment]
So maybe there is another root cause, but I fixed my issue by changing cache keys. 

https://github.com/apigee-127/swagger-tools/blob/master/lib/specs.js#L686

From

```javascript
    JsonRefs.resolveRefs(apiDOrSO, jsonRefsOptions)
      .then(function (results) {
        removeCirculars(results.resolved);

        cacheEntry.referencesMetadata = results.refs;
        cacheEntry.resolved = results.resolved;
        cacheEntry.resolvedId = SparkMD5.hash(JSON.stringify(results.resolved));


        callback();
      })
      .catch(callback);
```

To

```javascript
    JsonRefs.resolveRefs(apiDOrSO, jsonRefsOptions)
      .then(function (results) {
        removeCirculars(results.resolved);

        cacheEntry.referencesMetadata = results.refs;
        cacheEntry.resolved = results.resolved;
        cacheEntry.resolvedId = SparkMD5.hash(JSON.stringify(apiDOrSO));

        callback();
      })
      .catch(callback);
```

**Comment by whitlockjc** [comment]
Do you mind testing something for me?  On line 1161 of json-refs' index.js, add `obj = clone(obj);` and let me know if the original swagger-tools code works.

**Comment by whitlockjc** [comment]
I'm still working on some json-refs issue and when it's done, I'll release and get swagger-tools updated as well.

**Comment by whitlockjc** [comment]
Fixing the issue you pointed out above fixed the issue I was running into with json-refs.  I'll get the release out soon but I'm hoping the suggestion above works for you too, because that means that this was the cause for both issues.

**Comment by dexwiz** [comment]
Yep that fixed it. So `resolveRefs` is mutating the object somehow.

**Comment by whitlockjc** [comment]
Fixed.  `swagger-tools@0.9.13` is out with this fix in it, tests are confirmed passing.

**Comment by whitlockjc** [comment]
Sorry about this and thanks for your patience.

**Comment by dexwiz** [comment]
No problem. Thanks for the quick turn around.
