### ISSUE TITLE
"Reference could not be resolved" error in 0.9.12 and 0.9.13

### ISSUE THREAD

**Issue by iamigo** [apigee-127/swagger-tools#336]
My schema has an object defined which contains a reference to itself. Specifically, my "SubjectsResponse" object contains an item called "children" which is an array of "SubjectsResponse" records.
With swagger-tools v. 0.9.12 and 0.9.13, I now get this error:

JSON Schema file is invalid:
  #/items/properties/children/items: Reference could not be resolved: #/definitions/SubjectsResponse

(It still works in 0.9.11.)

**Comment by whitlockjc** [comment]
I bet that's because json-refs no longer replaces circular references with `{}` and instead keeps the circular reference untouched.  I'll have to update the validation logic for this.

**Comment by whitlockjc** [comment]
I'll get a release out shortly.

**Comment by whitlockjc** [comment]
`swagger-tools@0.9.14` is released with this fix.

**Comment by lironess** [comment]
This issues happens again to me at 0.10.1

**Comment by whitlockjc** [comment]
Do you have an example that reproduces this?
