### ISSUE TITLE
SwaggerUi (by swagger-tools) doesnt work with restify but works with express

### ISSUE THREAD

**Issue by lironess** [apigee-127/swagger-tools#339]
Hi.
This code brings up a simple express server with swagger ui :

    const express = require('express');
    const swaggerTools = require('swagger-tools');
    const swaggerDoc = require('./mySwaggerDoc.json');

    const app = express();

    swaggerTools.initializeMiddleware(swaggerDoc, (middleware) => {
      app.use(middleware.swaggerUi());

      app.get('/', (req, res) => {
        res.send('Hello World!');
      });

      app.listen(5000, () => {
          console.log('Example app listening!');
      });
    })

then when I'm trying to reach `http://localhost:5000/docs` I'm getting my documentation perfectly.
The problem comes when I'm trying to to the same thing for restify server (which I think should handle that as well, because swaggerUi just returns a middleware).

my code looks like this :

    const Restify = require('Restify');
    const swaggerTools = require('swagger-tools');
    const swaggerDoc = require('./mySwaggerDoc.json');

    server = Restify.createServer();
    swaggerTools.initializeMiddleware(swaggerDoc, (middleware) => {
      server.use(middleware.swaggerUi());

      server.get('/', (req, res) => {
        res.send('Hello World!');
      });

      server.listen(5000, () => {
          console.log('Example server listening!');
      });
    });

now when I'm trying to reach `http://localhost:5000/docs` I'm getting:

    {
      code: "ResourceNotFound",
      message: "/docs does not exist"
    }

Ideas ?

**Comment by whitlockjc** [comment]
The reason for this is Restify owns the router.  If you do not register a `/docs` route, even though my middleware would gladly serve `/docs`, it won't be served.  You will need to register the following:

```js
var swaggerUi = middleware.swaggerUi();

server.get('/docs', swaggerUi);
server.get('/api-docs', swaggerUi);
```

Of course, the paths you match need to match the options you provide to the swagger-ui middleware: https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swaggeruioptions

Let me know how it goes.

**Comment by lironess** [comment]
Well, it still not working. I'm getting a response from `/`, but `/docs` or `/api-docs` returns that it not exist. You can check out this code piece at your environment:

```javascript
const Restify = require('Restify');
const swaggerTools = require('swagger-tools');
const swaggerDoc = require('./mySwaggerDoc.json');

server = Restify.createServer();
swaggerTools.initializeMiddleware(swaggerDoc, (middleware) => {
  const swaggerUi = middleware.swaggerUi();

  server.get('/docs', swaggerUi);
  server.get('/api-docs', swaggerUi);

  server.get('/', (req, res) => {
    res.send('Hello World!');
  });

  server.listen(5000, () => {
      console.log('Example server listening!');
  });
});
```

**Comment by lironess** [comment]
Update: i deleted all node_modules and "npm install" everything again,and the server seems to serve the schema and docs route.
The only problem i got now that the swagger ui looks for its assets (jquery, css ...) and can't find them. Maybe I have to provide some flag or argument ... ?

**Comment by whitlockjc** [comment]
I know what is going on there, you'd need to double up your paths because you're listening at a base and swagger-ui listens for a base after that base.  So `/docs` would likely be `/docs/docs`.  I'll look at Restiy docs to see the right way to fix this.

**Comment by lironess** [comment]
Thanks. You can take my piece of code and edit it.

**Comment by whitlockjc** [comment]
I got it working but this was more an effort in learning restify and less about swagger-tools.  So while I'm happy to help, this had nothing to do with swagger-tools.  Here is the working code:

```js
'use strict';

var restify = require('restify')
var server = restify.createServer();
var swaggerTools = require('swagger-tools');

var serverPort = 3000;

// swaggerRouter configuration
var options = {
  controllers: './controllers',
  useStubs: process.env.NODE_ENV === 'development' ? true : false // Conditionally turn on stubs (mock mode)
};

// The Swagger document (require it, build it programmatically, fetch it from a URL, ...)
var swaggerDoc = require('./api/swagger.json');

// Initialize the Swagger middleware
swaggerTools.initializeMiddleware(swaggerDoc, function (middleware) {
  var middlewares = [
    middleware.swaggerMetadata(),
    middleware.swaggerValidator(),
    middleware.swaggerRouter(options),
    middleware.swaggerUi()
  ];

  // Required since swagger-ui uses CORS to fetch the Swagger document
  server.use(restify.CORS());

  // Supported Swagger HTTP verbs (options and patch are not Restify server APIs)
  // https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#path-item-object
  ['get', 'put', 'post', 'delete', 'head'].forEach(function (verb) {
    if (verb === 'delete') {
      verb = 'del';
    }

    // Register the middlewares with Restify
    server[verb](/.*/, middleware.swaggerMetadata(), middleware.swaggerValidator(), middleware.swaggerRouter(options), middleware.swaggerUi());
  });

  // Start the server
  server.listen(serverPort, function () {
    console.log('Your server is listening on port %d (http://localhost:%d)', serverPort, serverPort);
  });
});
```

This code is the same [Connect-based server in the 2.0 example](https://github.com/apigee-127/swagger-tools/blob/master/examples/2.0/index.js) but modified to work the way Restify requires.  Of course, your issue was more with just the swagger-ui middleware so you could probably do this a little simpler.

**Comment by lironess** [comment]
Why did you closed the issue ? its still not working ..
took your example from [here](https://github.com/apigee-127/swagger-tools/tree/master/examples/2.0) and pasted your code at index.js. When I'm trying to get /docs, i can see that it is trying to get all assets, but no success as the status of all requests stays pending (according to chrome devtools)

**Comment by whitlockjc** [comment]
If you hit `/docs`, it will likely redirect to `/docs/` and the page will look goofy because swagger-ui doesn't handle the redirect.  Even so, that is different than the original issue you reported.  The original issue was that you couldn't get swagger-tools' swagger-ui middleware working with Restify and the code above does that for you.  I agree that the `/docs -> /docs/` redirect not working is weird so I'll create a new issue but that is definitely a separate issue than this.

**Comment by lironess** [comment]
No. I don't think it redirected at all. I see that the url is not changing, and also at the responses at Chrome's devtools resources tab I see that this request is not redirected

**Comment by whitlockjc** [comment]
This is the case, I ran into it yesterday while working on this issue.  If you access `/docs/` it works and `/docs` does not.  I've tried this, I assure you.  With the code I gave you above, not only did `/api-docs` work fine but `/docs/` did as well.  As for `/docs` not working, I've created #347 as it is a different issue than the one you reported.  We can discuss it there.

**Comment by lironess** [comment]
Ok. I checked it out and as you said its working with `/docs/`.
Now - can I somehow drop the unnecessary `swaggerRouter` and `swaggerValidator` and stay just with `swaggerMetadata` and `swaggerUi` ?
Because when i'm trying to do so, i can get the /docs/ but every other route fails even if i specify it manually :
```javascript
'use strict';

var restify = require('restify')
var server = restify.createServer();
var swaggerTools = require('swagger-tools');

var serverPort = 3000;

var swaggerDoc = require('./swagger.json');

swaggerTools.initializeMiddleware(swaggerDoc, function (middleware) {
  var middlewares = [
    middleware.swaggerMetadata(),
    middleware.swaggerUi()
  ];

  server.use(restify.CORS());

  ['get', 'put', 'post', 'del', 'head'].forEach(function (verb) {
    server[verb](/.*/, middleware.swaggerMetadata(), middleware.swaggerUi());
  });

  server.get('/', function (req, res) {
    res.end("hello world");
  });

  server.listen(serverPort, function () {
    console.log('Your server is listening on port %d (http://localhost:%d)', serverPort, serverPort);
  });
});
```

**Comment by whitlockjc** [comment]
Restify owns the router and so using swagger-router from swagger-tools might not work right.  The example I gave you seemed to work but if you're having trouble, don't use it.  Also, swagger-metadata isn't required for swagger-ui so unless you're using `req.swagger` in your applications, you could omit it.

**Comment by lironess** [comment]
Ok. everything works. thanks !

**Comment by simonv3** [comment]
For what it's worth I fixed this with: 

```
// Initialize the Swagger middleware
swaggerTools.initializeMiddleware(swaggerSpec, function (middleware) {

  // Supported Swagger HTTP verbs (options and patch are not Restify server APIs)
  // https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#path-item-object
  ['get', 'put', 'post', 'del', 'head'].forEach(function (verb) {
    server[verb](/(swagger.*|api\-docs)/, middleware.swaggerUi({
      swaggerUi: '/swagger-docs',
      apiDocsPath: '/api-docs.json'
    }));
  });
});
```

If I didn't specify the endpoints that swaggerUi took control of, then all my other endpoints just hung until they timed out.

**Comment by jhonny111s** [comment]
that works to me.

```
initializeMiddleware(swaggerDoc, function (middleware) {
    // Interpret Swagger resources and attach metadata to request - must be first in swagger-tools middleware chain
    app.pre(middleware.swaggerMetadata());

      // Validate Swagger requests
      app.pre(middleware.swaggerValidator());

      // Serve the Swagger documents and Swagger UI
    app.pre(middleware.swaggerUi({
        swaggerUi: '/swagger-docs',
        apiDocsPath: '/api-docs.json'
    }));

app.listen ....
});
```
