### ISSUE TITLE
swagger-ui middleware redirects without trailing slash

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/swagger-tools#347]
Whenever you access `/docs`, it redirects *(or attempts to)* to `/docs/` and the initially displayed page never fully renders.  I know that the `node-static` middleware we're using has a configuration to disable the redirect but we also could benefit from figuring out why this is happening.  This originally was found while working on #339.

**Comment by lironess** [comment]
+1

**Comment by whitlockjc** [comment]
I cannot reproduce this with Connect or Express but with Restify, I see the issue.  I think the redirect that the swagger-ui middleware is performing is not handled by Restify since Restify's `res.redirect` is different than Connect/Express.  That being said, I cannot fix this in swagger-tools.  But I was able to get this working using a simple Restify redirect *(modified from #339)*:

```js
'use strict';

var restify = require('restify')
var server = restify.createServer();
var swaggerTools = require('swagger-tools');

var serverPort = 3000;

// swaggerRouter configuration
var options = {
  controllers: './controllers',
  useStubs: process.env.NODE_ENV === 'development' ? true : false // Conditionally turn on stubs (mock mode)
};

// The Swagger document (require it, build it programmatically, fetch it from a URL, ...)
var swaggerDoc = require('./api/swagger.json');

// Initialize the Swagger middleware
swaggerTools.initializeMiddleware(swaggerDoc, function (middleware) {
  var middlewares = [
    middleware.swaggerMetadata(),
    middleware.swaggerValidator(),
    middleware.swaggerRouter(options),
    middleware.swaggerUi()
  ];

  // Required since swagger-ui uses CORS to fetch the Swagger document
  server.use(restify.CORS());
  // Use Restify versions of body/query parsing middlewares
  server.use(restify.queryParser());
  server.use(restify.jsonp());
  server.use(restify.bodyParser());

  // Fix issue with swagger-ui redirect not working with Restify (Not sure who is to blame here)
  server.get('/docs', function (req, res, next) {
    res.redirect('/docs/', next);
  });

  // Supported Swagger HTTP verbs (options and patch are not Restify server APIs)
  // https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#path-item-object
  ['get', 'put', 'post', 'delete', 'head'].forEach(function (verb) {
    if (verb === 'delete') {
      verb = 'del';
    }

    // Register the middlewares with Restify
    server[verb](/.*/, middleware.swaggerMetadata(), middleware.swaggerValidator(), middleware.swaggerRouter(options), middleware.swaggerUi());
  });

  // Start the server
  server.listen(serverPort, function () {
    console.log('Your server is listening on port %d (http://localhost:%d)', serverPort, serverPort);
  });
});
```

I think at the end of the day, the middleware in swagger-tools is written to be Connect compatible, which Restify is not.  So while I'm sure we can make swagger-tools work just fine with Restify, there may be some hoops you have to jump through to do so.  *(The code above was able to make all functionality of the [swagger-tools 2.0 example](https://github.com/apigee-127/swagger-tools/tree/master/examples/2.0) work using Restify.)*

**Comment by lironess** [comment]
```javascript
      server.get(`${BaseUrl}/docs`, (request, response, next) => {
        response.redirect(`${BaseUrl}/docs/`, next);
      });

      [`get`, `put`, `post`, `del`, `head`].forEach((verb) => {
        server[verb](/.*/, middleware.swaggerUi({
          swaggerUi: `${BaseUrl}/docs`,
          apiDocs: `${BaseUrl}/api-docs`
        }));
      });
```
Not working. getting Error 310 (net::ERR_TOO_MANY_REDIRECTS) - because /docs redirects to /docs/, than /docs/ redirects to /docs because of ``swaggerUi: `${BaseUrl}/docs``

**Comment by whitlockjc** [comment]
I'm sorry but this is an issue with Restify and the serve-static middleware not working with this.  swagger-tools cannot work around this.  I'm not sure if the options you're passing are causing the issue but since you're passing in the default values, you might as well just pass no options.  Does that help?  Also, it seems you're only using swagger-tools for its swagger-ui middleware.  If that's the case, save yourself the trouble and just use Restify's built-in static file serving and serve swagger-ui yourself.  I only suggest this because I'm sure using Restify to do this would be much simpler than trying to work around it.
