### ISSUE TITLE
Overring multer options, breaks validator

### ISSUE THREAD

**Issue by Hanspagh** [apigee-127/swagger-tools#348]
After upgrading to the newest version, where multer has been updated, I face an issue when I try override the default multer config. Doing the following
` var upload = multer(`
`{ limits: {`
               `fileSize: 2 * 1024 * 1024}`
               `storage : multer.memoryStorage() `
`}).any();`
`app.use(upload)`
makes the makes the validator fail with the following message
> message: 'Request validation failed: Parameter (file) is required'

If I remove my own config is issue is resolved, but then I cant configure the limit
Any help would be appreciated

**Comment by whitlockjc** [comment]
Can you run with the `DEBUG=swagger-tools* node .` and paste the output?  Also, did you `app.use(upload)` prior to swagger-metadata?

**Comment by Hanspagh** [comment]
Yes, I did put upload before swagger metadata, since I am using swagger-node it is before   `swaggerExpress.register(app);`
It seems like my multer consumes the uploaded file and it never reaches swagger-tools


Here is a screenshot of the initializing 
<img width="916" alt="udklip" src="https://cloud.githubusercontent.com/assets/1024416/12972101/9641df7a-d0a2-11e5-85ab-4bd5017ebc29.PNG">
And here for the route
<img width="1180" alt="udklip" src="https://cloud.githubusercontent.com/assets/1024416/12972130/bc19b434-d0a2-11e5-99d5-34b51d0625dc.PNG">

**Comment by whitlockjc** [comment]
Try using `app.use(upload.fields([{name: "file"}]));` instead of `app.use(upload);`.  Here is the code swagger-tools uses: https://github.com/apigee-127/swagger-tools/blob/master/middleware/swagger-metadata.js#L175  See #287 and #318 for details on how multer was changed to work with multer 1.x.

**Comment by Hanspagh** [comment]
Thanks,  I will try it out when I get to my pc

**Comment by Hanspagh** [comment]
I tried your suggestion, I also tried with array(), but nothing seems to work. I read though the changes, but when I use my own multer config, the file never shows up in `req.swagger.params`, which is where there validator checks if it exists

**Comment by Hanspagh** [comment]
So my current guess for what is wrong is the following. 
My multer consumes the file and saves it in `reg.files`,
Swagger Tools multer cant find the file since its already consumed, so instead of doing nothing, it sets `reg.files` to an empty object

**Comment by whitlockjc** [comment]
swagger-tools' multer is only used when `req.files` is not populated already.  So if your multer hasn't populated `req.files`, only then will the multer shipped with swagger-tools be used.  In fact, all of the body/query parsers included with swagger-tools are only used if necessary.  Well...that's the way it's suppose to work but it seems the multer support in swagger-tools doesn't have this check in it anymore.  It might be a result of recent PRs to support newer versions of multer.

If you have the time to dig, could you tell me if `req.files` is populated prior to the multer in swagger-tools being invoked?  Honestly, I would expect swagger-tools' multer to not do anything if your multer had already ran.

**Comment by Hanspagh** [comment]
It is populated all the way up to the line of code I referenced earlier which is called from the swagger tools multer. I am on phone right now so can't provide a log of it sadly. But I debugged it earlier.

**Comment by whitlockjc** [comment]
That's enough for me.  I will get a fix out.

**Comment by Hanspagh** [comment]
Fantastic,  I really apriciate the help

**Comment by whitlockjc** [comment]
The problem here is the use of `multer.any()`.  What it does is it will populate `req.files` with an array of files instead of an object whose keys are the multi-part field names.  I need to see if there is anything I can do to address this or if this would be something you would have to change.

**Comment by whitlockjc** [comment]
Easy fix.  Release coming soon.

**Comment by whitlockjc** [comment]
Fixed.  I want to fix one more thing before releasing but I will get a release out today.

**Comment by whitlockjc** [comment]
`swagger-tools@0.9.15` is released with this fix in it.
