### ISSUE TITLE
double API key , resolved in swagger-js but not here 

### ISSUE THREAD

**Issue by rajegit** [apigee-127/swagger-tools#349]
This issue 
https://github.com/swagger-api/swagger-js/pull/633

is not updated

**Comment by whitlockjc** [comment]
I have no idea what is being requested.  Can you give more details?  As for _"resolved in swagger-js but not here"_, swagger-tools doesn't use swagger-js.  The only thing I can gather is that you want the bundled swagger-ui updated to reflect the change you linked against?

**Comment by whitlockjc** [comment]
I've updated the swagger-ui shipped with swagger-tools.  That's the best I can do without anymore information.  This will be in the next release.

**Comment by whitlockjc** [comment]
`swagger-tools@0.9.15` is released with this fix in it.
