### ISSUE TITLE
Error message on the web page: schemaValidationMessages":[{"level":"error","message":"Can't read from file

### ISSUE THREAD

**Issue by pradvaar** [apigee-127/swagger-tools#352]
Getting this error message on my web page after exporting source code from local host. 

when I click on it: schemaValidationMessages":[{"level":"error","message":"Can't read from file https://mywebsieswagger/docs/v1"}]}

Can't produce it locally.

![image](https://cloud.githubusercontent.com/assets/17340011/13180556/ecb6e030-d6f6-11e5-83b9-f31e7b452b45.png)

**Comment by whitlockjc** [comment]
That's the Swagger validator badge that's a part of swagger-ui.  This isn't an error from swagger-tools.  Looks like the badge is unable to read your hosted Swagger document.  As for why it doesn't happen locally is the online validator behind the badge skips validating localhost addresses.  This should be brought up here if it is indeed a legitimate issue: https://github.com/swagger-api/validator-badge

**Comment by pradvaar** [comment]
@whitlockjc Im sorry for bringing this up here...thanks for the info.

**Comment by whitlockjc** [comment]
Don't be sorry, I'm here to help, even if that means gently pointing you elsewhere sometimes.  ;-)
