### ISSUE TITLE
New changes to multer breaks when no file is provided

### ISSUE THREAD

**Issue by Hanspagh** [apigee-127/swagger-tools#353]
When I send a request without a file I get the following error
`val = req.files[parameter.name] ? req.files[parameter.name] : undefined;`
`TypeError: Cannot read property 'file' of undefined`
`in file \node_modules\swagger-tools\middleware\helpers.js:88`
Instead of a validation error saying the file is missing

**Comment by whitlockjc** [comment]
I know it's cryptic but I've already started this in #350.

**Comment by Hanspagh** [comment]
My bad, I should have checked the other issues

**Comment by whitlockjc** [comment]
Nah, you're good.  Even I would had created a new one as #350 is general where as this is only reproducible with multer from what I can tell.

**Comment by whitlockjc** [comment]
I've fixed this.  I will get a release out in a few but just know, a `0.10.x` will be released immediately.  *(Please review the release notes after this `0.9.x` release to see what is up.)*

**Comment by whitlockjc** [comment]
swagger-tools `0.9.16` and `0.10.0` have both released with your fix.  I'd suggest you jump on `0.10.0`.

**Comment by Hanspagh** [comment]
Thanks, I am using https://github.com/swagger-api/swagger-node, so I guess I will have to stay on 0.9.x

**Comment by whitlockjc** [comment]
They'll upgrade soon I bet.
