### ISSUE TITLE
How to run swagger tool through https?

### ISSUE THREAD

**Issue by levuphuong** [apigee-127/swagger-tools#357]
Hi

I want to use swagger tool on my node js web server, If i use http, everything is ok.
But when i use https i cannot access my web and swagger ui

Here is a snippet code in my .json file.

`"produces": ["application/json"],
  "host": "localhost:8000",
  "schemes": ["https"],
  "basePath": "/api",`

**Comment by whitlockjc** [comment]
How you run your server has nothing to do with swagger-tools.  All swagger-tools provides is the middleware.  You setting up an https server is outside the scope of swagger-tools or with Swagger.

That being said, you can look at the [https module documentation](https://nodejs.org/api/https.html) for Node.js and they have an example.

**Comment by levuphuong** [comment]
I am sorry
Maybe i didn't say clearly my case. 
I mean. 
1. I can run my server without swagger tool through https
2. I can run my server with seagger tool through http
3. But i cannot run my server with swagger tool through https

Can you show me how to configure swagger tool to it can work on https

Thank you

**Comment by whitlockjc** [comment]
I don't understand how swagger-tools is involved in the problem.  Can you share your server configuration?

**Comment by levuphuong** [comment]
I just check my code server again
Variable in swagger example
`app.use(middleware.swaggerRouter(options));`
is same with 
`var server = https.createServer(options,app);`

I renamed this variable and then everything ok.

That is a my mistake.
Thanks for your help so much
