### ISSUE TITLE
Update Swagger-UI

### ISSUE THREAD

**Issue by briananderson1222** [apigee-127/swagger-tools#358]
https://github.com/swagger-api/swagger-ui/issues/1889#event-590677210 

- This issue appears to have been resolved and should add some of the long awaited security integration to swagger-ui.

- I realize I can update my own swagger-ui and pass that as an option in the meantime, but just thought i'd bring this to your attention

**Comment by whitlockjc** [comment]
> I realize I can update my own swagger-ui and pass that as an option in the meantime, but just thought i'd bring this to your attention

Thanks a lot.

**Comment by briananderson1222** [comment]
Turns out I was a little antsy on this. After further looking into this, I suppose it's best to wait until an official swagger-ui release comes out. Looks like authorizations are now supported from the UI but not from the swagger-js client which is a dependency of swagger-ui. Please disregard this issue :/
