### ISSUE TITLE
Validation error badge

### ISSUE THREAD

**Issue by rzachariah** [apigee-127/swagger-tools#363]
I used swagger project create/edit to define a new node service. With swagger project verify, I see that my API definition is fine. It also works fine locally and in prod. However, when I deploy it to an https endpoint, I get a validation error badge from the swagger docs page. If I click the badge, I get this message.

```json
{
schemaValidationMessages: [
{
level: "error",
message: "Can't read from file https://digitalexhaust.ezesoft.net/api/collection/api-docs"
}
]
}
```

If I follow that link on my intranet, I see the api-docs, and they look fine.

Here's how I configured the server
```
'use strict';

const defaultRoutingPath = '/api/collection';
const defaultPort = 3000;

var path = require('path');
var SwaggerExpress = require('swagger-express-mw');
var SwaggerUi = require('swagger-tools/middleware/swagger-ui');
var express = require('express');
var app = express();
var subpath = express();
module.exports = app; // for testing

var routingPath = process.env.ROUTING_PATH || defaultRoutingPath;
var port = process.env.PORT || defaultPort;
var host = process.env.HOST || `localhost:${port}`;
var nodeEnv = process.env.NODE_ENV;

var config = {
  appRoot: __dirname, // required config
};

SwaggerExpress.create(config, function(err, swaggerExpress) {
  if (err) { throw err; }
  
  app.use(routingPath, subpath);
  
  app.get('/', (req, res) => {
    res.redirect(path.join(routingPath, 'docs'));
  })

  app.get(routingPath, (req, res) => {
    res.redirect(path.join(routingPath, 'docs'));
  })
  
  configureSwagger(swaggerExpress.runner.swagger)

  // enable SwaggerUI
  subpath.use(swaggerExpress.runner.swaggerTools.swaggerUi({
    url: getApiDocsUrl(),
  }));

  // install middleware
  swaggerExpress.register(app);

  app.listen(port);

  if (swaggerExpress.runner.swagger.paths['/health']) {
    console.log(`try this:\ncurl ${getBaseUrl() + '/health'}`);
  }
});

function configureSwagger(swagger) {
  if (nodeEnv === 'production') {
    swagger.host = host;
    swagger.schemes = ['https'];
  } else {
    swagger.host = `localhost:${port}`;
    swagger.schemes = ['http'];
  }
  swagger.basePath = routingPath;
}

function getBaseUrl() {
  var scheme = 'http';
  if (nodeEnv === 'production') {
    scheme = 'https';
  }
  return `${scheme}://${host}${routingPath}`;
}

function getApiDocsUrl() {
  var baseUrl = getBaseUrl();
  return baseUrl + '/api-docs';
}
```

Here's my swagger.yaml
```
swagger: "2.0"
info:
  version: "0.0"
  title: collector
  description: Collects Digital Exhaust for refinement into insight
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /health:
    x-swagger-router-controller: health
    get:
      tags:
        - Health
      description: Returns health report to the caller
      operationId: check
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HealthResponse"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /bin:
    x-swagger-router-controller: collector
    get:
      tags:
        - Bin
      description: Get exhaust from the bin (syche)
      responses:
        "200":
          description: Snarky response
          schema:
            $ref: "#/definitions/SnarkyResponse"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      tags:
        - Bin
      description: Post exhaust to the bin
      parameters:
        - name: exhaust
          in: body
          description: Digital Exhaust
          required: true
          schema:
            $ref: "#/definitions/CollectRequest"
      responses:
        "202":
          description: Ack
          schema:
            $ref: "#/definitions/CollectResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HealthResponse:
    required:
      - name
      - status
    properties:
      name:
        type: string
      status:
        type: string
  SnarkyResponse:
    required:
      - message
    properties:
      message:
        type: string
  CollectRequest:
    required:
      - product
    properties:
      product:
        type: string
      host:
        type: string
      component:
        type: string
      action:
        type: string
  CollectResponse:
    required:
      - message
      - payload
    properties:
      message:
        type: string
      payload:
        type: object
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string        
```

**Comment by whitlockjc** [comment]
The validation badge is its [own project](https://github.com/swagger-api/validator-badge) and it is delivered via swagger-tools as part of [swagger-ui](https://github.com/swagger-api/swagger-ui).  The error you're getting is a result of the hosted service behind the validator-badge is unable to access your intranet to validate the Swagger document.  This is not a client-side service so it cannot access your intranet.  That being said, this is outside the scope of swagger-tools as we have no involvement in swagger-ui or the validator-badge.

**Comment by rzachariah** [comment]
Ok, thanks. Do you know how to turn off validation, or should I ask them?

**Comment by whitlockjc** [comment]
You could remove that from your swagger-ui instance.  Since you're probably using the bundled swagger-ui, I'm not sure how to do it.  I'll ask around.

**Comment by rzachariah** [comment]
The validator guys suggested nulling out the validatorUrl, but that didn't work for me.

```
  // enable SwaggerUI
  subpath.use(swaggerExpress.runner.swaggerTools.swaggerUi({
    url: getApiDocsUrl(),
    validatorUrl: null
  }));
```

**Comment by rzachariah** [comment]
I'll try running the validator myself using this.
https://hub.docker.com/r/swaggerapi/swagger-validator/

**Comment by whitlockjc** [comment]
Your attempt was wrong.  When they said to set `validatorUrl` to `null`, they meant in swagger-ui, not in swagger-tools.  Here is where the change would be made: https://github.com/apigee-127/swagger-tools/blob/master/middleware/swagger-ui/index.html#L40  But since that's a bundled file, you'll need to download swagger-ui, modify it for your needs and then use https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swaggeruioptions to point to your custom swagger-ui instance.

**Comment by rzachariah** [comment]
Sorry, I am kind of a newbie at this. I guess I'm not clear on the difference between bundled and unbundled. I followed [these instructions](https://github.com/swagger-api/swagger-node) to build a node service with swagger documenation. I guess those are the instructions for going bundled. I'm not attached to this approach. Let's say I wanted to switch to an unbundled approach. Where would I find instructions on how to do that?

Thanks.

**Comment by whitlockjc** [comment]
swagger-tools ships with a binary distribution of swagger-ui bundled within its npm module.  We provide this as a convenience to make things _just work_ when you deploy.  In the event that you need to change swagger-ui in any way _(branding, code changes, ...)_, it is advised that you download your own swagger-ui distribution and host it alongside your Node.js server.  You then need to configure the swagger-ui middleware shipped with swagger-tools to point to where your custom/modified version of swagger-ui is located.

**Comment by rzachariah** [comment]
Thanks. Interestingly, I haven't made any changes, but the validation error badge is suddenly gone today.
