### ISSUE TITLE
Does Swagger Security support custom error responses (for unauthorized requests)??

### ISSUE THREAD

**Issue by leomar-developer** [apigee-127/swagger-tools#366]
When Swagger Security determines that a given request has been unauthorized it sends back a response with a 403 status code (which is good) and a string message which seems to be the stacktrace that describes the error which was sent via the swagger security callback to denote the request was unauthorized, what has me stuck at the moment is I don't see a way to avoid this and instead send a custom response to our API consumers, we would like to send a JSON response (with status code 403) with a custom object with some properties that have information about what happened when a request to a given API method has been unauthorized. Is this possible right now in the swagger security middleware? if so please tell me how

Thanks in advance!

**Comment by whitlockjc** [comment]
swagger-security sends the authorization error downstream like any other middleware error gets handled.  Here is where it happens: https://github.com/apigee-127/swagger-tools/blob/master/middleware/swagger-security.js#L73  Long story short, this is a common pattern for connect-style middleware.  This means that all you have to do is provide an error-handler middleware to receive the error and style it however you want.  Express has a very simple guide on how to do this: http://expressjs.com/en/guide/error-handling.html

**Comment by leomar-developer** [comment]
Thanks whitlockjc for the clear explanation! I will give that a try

**Comment by whitlockjc** [comment]
Let me know if I can help further.
