### ISSUE TITLE
When deployed getting error

### ISSUE THREAD

**Issue by aymittal** [apigee-127/swagger-tools#369]
When i deployed my code, i get the swagger ui but it fails 
**http://online.swagger.io/validator/debug?url=http://localhost:8080/be/selfsvc/api/swagger.json**

Due to which i get a error symbol at bottom right side

**Comment by whitlockjc** [comment]
This has nothing to do with swagger-tools.  `online.swagger.io` validator is an online service and it uses server-side logic to do the validation.  If you provide it with a `url` it cannot access, it will give you an error.

**Comment by aymittal** [comment]
Then what should we provide it with??

**Comment by whitlockjc** [comment]
You don't need it.  I should just update the swagger-ui template to stop rendering this because it's confusing the end users.  I've opened #370 to track this.
