### ISSUE TITLE
Return 400 Bad Request on request validation error

### ISSUE THREAD

**Issue by hjpbarcelos** [apigee-127/swagger-tools#37]
Currently, when there is a validation error in the request, a `500 Internal Server Error` response is returned.

This seems a little odd, since a malformed request should return a `400 Bad Request` response, as stated in this [RFC](https://tools.ietf.org/html/rfc7231#section-6.5.1).

**Comment by AhsanNissar** [comment]
![screenshot 28](https://user-images.githubusercontent.com/14846851/41929613-1aa70ade-7992-11e8-9164-ec41df2cbacd.png)
 can anybody help me with this?

**Comment by AhsanNissar** [comment]
![capture2](https://user-images.githubusercontent.com/14846851/41929670-44fb5e34-7992-11e8-9b1f-c33443233d76.PNG)
can anybody help me with this error?
