### ISSUE TITLE
Remove validator badge from embedded swagger-ui

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/swagger-tools#370]
swagger-ui's online validator badge is confusing people because in many cases, the online service cannot reach the actually hosted URL for the Swagger document and it leads the users to think something is wrong when it isn't.  In fact, swagger-tools validates the Swagger document prior to starting the server.

**Comment by joetinoco** [comment]
SwaggerUI itself has [a "validatorUrl" parameter](https://github.com/swagger-api/swagger-ui#parameters) that can be set to 'null' to stop the bad from showing in the page. Maybe it's just a matter of enabling this on the embedded SwaggerUI?

**Comment by whitlockjc** [comment]
That's definitely one option.  I think that's the simplest option but I do fear that for the cases where it _does_ work already, people might be upset by it.  I'll give it some thought.

**Comment by joetinoco** [comment]
In that case I'd set it on by default, only turning it off if and only if a user explicitly instantiates the SwaggerUI object with this parameter set to 'null'. I'm quite busy with school/work otherwise I'd try my hand with a pull request...

**Comment by whitlockjc** [comment]
The more I think about this, the more I feel I've got a solution.  `swagger-tools` validates your Swagger document(s) prior to allowing your server to start so isn't this feature in `swagger-ui` redundant?  Why not just turn it off completely?

**Comment by chadxz** [comment]
I came looking for this feature today. I would be fine with either turning it off completely or allowing me to specify the validatorUrl passed to swagger-ui

**Comment by chadxz** [comment]
solution for this would also solve #323

**Comment by whitlockjc** [comment]
Great, my response 10 day sago still stands.  When I update swagger-ui before the next release, I will just turn this off.

**Comment by chadxz** [comment]
right on

**Comment by SciTechEnthusiast** [comment]
set below in the config 

validatorUrl:null

source: https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#network
