### ISSUE TITLE
swagger_router breaks the pipeline

### ISSUE THREAD

**Issue by cvrabie** [apigee-127/swagger-tools#372]
I noticed that the router [does not call `next()`](https://github.com/apigee-127/swagger-tools/blob/master/middleware/swagger-router.js#L407) after the execution of the controller. 

This basically breaks the bagpipes pipeline as nothing after the router fitting will get called. This could be very useful as you can have fittings to modify the response. This kind of usage is even mentioned in the [bagpipes docs](https://github.com/apigee-127/bagpipes#user-defined-fittings).

I do see that the router does pass the `next` callback as the third argument for the controller so you can still do it by calling `next()` in each controller handler. However the [documentation for swagger controllers](https://github.com/swagger-api/swagger-node/blob/master/docs/controllers.md#implementing) does not mention it. Further more, the recommended `.json()` function actually [ends the response process](https://github.com/theganyo/swagger-node-runner/blob/master/fittings/express_compatibility.js#L28) so you couldn't change the response anyway.

Am I correct in thinking that the only way do have the pipeline work properly, is to ditch the `express_compatibility` fitting and then **(in each controller)** set the json header manually with `res.setHeader`, and call `next` with your response object?

----------

When I started to write this ticket I thought that the problem is in the router middleware which should guarantee a call to `next`. As I wrote and looked at the code for the various projects I got a better understanding of what's happening and I'm not certain anymore what's the real problem (if any). I think that at the core there's a discrepancy between the [swagger api](https://github.com/swagger-api/swagger-node/blob/master/docs/controllers.md#implementing) and the bagpipes implementation. At the very least the interplay between a controller and the bagpipes system should be explained in the documentation for the controllers. I would even go as far as to suggest that the main example for a controller should be the *correct* way, not the one relying on express compatibility.

**Comment by whitlockjc** [comment]
It is up to the route handler author to do whatever they deem fit.  I cannot guarantee one way or the other so if you want to write routes that use `next`, by all means do so.  All responses swagger-tools middleware send uses `next` but in the case of swagger-router, route handlers are user space so the author owns the response and _they_ own what happens at that point.  swagger-tools' router middleware [does in fact](https://github.com/apigee-127/swagger-tools/blob/master/middleware/swagger-router.js#L407) send `next` to the route handler.  It seems like the issues you found in documentation are in swagger-node and not swagger-tools.
