### ISSUE TITLE
Attach custom middlewares on a path basis

### ISSUE THREAD

**Issue by confuser** [apigee-127/swagger-tools#375]
I have middleware that I'd like to attach to specific routes (to avoid duplication), not all of them.

Under express, it'd be a simple case of `router.get('/path', someMiddleware, anotherMiddleware, actualOperation)`

However, with the combination of `x-swagger-router-controller` and `operationId`, the method provided according to docs/examples, is just a singular `fn(req, res, next)` function.

Obviously I could within each `operationId` function, execute each middleware (and use something like async.series to avoid callback hell), but it seems a little convoluted to do this for each and every `operationId`.

Does swagger-tools have any support for this?

**Comment by whitlockjc** [comment]
You should be able to do this now no differently.  Instead of enabling swagger-tools' middlewares globally, just enable them like you did in your example.  Am I missing something?

**Comment by confuser** [comment]
The routes are defined in the swagger file, how do I append middleware to them?

**Comment by confuser** [comment]
To clarify, this is using a127-magic

**Comment by whitlockjc** [comment]
I think I'm misunderstanding.  Why couldn't you do something like this:

```js
// ...
app.use(swaggerMetadata);

// Custom routes
router.get('/path', swaggerValidator, swaggerRouter);

app.use(swaggerValidator);
app.use(swaggerRouter);
// ...
```

I am probably missing something so can you give me a little more about what you're trying to do?

**Comment by whitlockjc** [comment]
Ah...well, if `a127-magic` is being used, I'm not sure I can help because swagger-tools' middleware is abstracted a few layers deep and is configuration driven.

**Comment by confuser** [comment]
No worries, thanks for confirming. I'll create a helper function then that wraps the operationId function to support this functionality.

**Comment by whitlockjc** [comment]
I'm sorry I wasn't able to help.  If you were using swagger-tools as-is, I think my suggestion above _(or some variation of it)_ would work.  But when you get into a127 and swagger-node, control is removed and makes things like this much more difficult and maybe even not possible.  Good luck.

**Comment by confuser** [comment]
It's certainly possible ;) I just wanted to check if there was a better way as I couldn't find any information about this anywhere.

To help anyone else using magic and not wanting to refactor it out to solve this problem, I've created a wrapper function that supports this; without hopefully causing any memory leaks (I've profiled and haven't seen any), module is on npm [series-middleware](https://www.npmjs.com/package/series-middleware)

Usage:
```js
var seriesMiddleware = require('series-middleware')
// define your middlewares, or require them

module.exports = {
  theOperationIdName: seriesMiddleware(aMiddlewareFn, anotherMiddlewareFn, function (req, res) {
    // Your normal controller logic here
  }
}
```
