### ISSUE TITLE
use 'express' instead of 'connect' 

### ISSUE THREAD

**Issue by rajegit** [apigee-127/swagger-tools#377]
Hi 
I am trying to replace express inside swagger-tool instead of default connect middleware. In the weather (example) app I am replacing 
app = require('connect')() ; with app = require('express')();
All other code remains same .

And initialization of middleware is failing . And its not able to read the controllers/weather.js itself . It gives 
Error initializing middleware

I guess
  app.use(middleware.swaggerRouter(options));
is designed for 'connect' and needs to be changed for 'express' . 

_Raje

**Comment by rajegit** [comment]
My typos sorry for bothering . 

A quick update , author can say , connect can be replaced by express here https://github.com/apigee-127/swagger-tools/blob/master/docs/QuickStart.md

and still it works well.

**Comment by pgun9476** [comment]
This is what you need to work with express

`'use strict';

import express from 'express'
import swaggerTools from 'swagger-tools';

// The Swagger document (require it, build it programmatically, fetch it from a URL, ...)
import swaggerDoc from '../swagger/swagger.json'

const app = express()
const port = process.env.PORT || 80

// swaggerRouter configuration
var options = {
  controllers: `${__dirname}/controllers`,
  useStubs: process.env.NODE_ENV === 'development' ? true : false // Conditionally turn on stubs (mock mode)
};


// Initialize the Swagger middleware
swaggerTools.initializeMiddleware(swaggerDoc, function (middleware) {
  // Interpret Swagger resources and attach metadata to request - must be first in swagger-tools middleware chain
  app.use(middleware.swaggerMetadata());

  // Validate Swagger requests
  app.use(middleware.swaggerValidator());

  // Route validated requests to appropriate controller
  app.use(middleware.swaggerRouter(options));

  // Serve the Swagger documents and Swagger UI
  app.use(middleware.swaggerUi());

  // Opens a socket and listens for connections only if there is no parent module running the script.
  if (!module.parent) {
    app.listen(port, () => {
      console.log(`Server started on port ${port}...`)
    })
  }

});


export default app;`
