### ISSUE TITLE
swagger-tool work with json not yaml ? 

### ISSUE THREAD

**Issue by rajegit** [apigee-127/swagger-tools#378]
Hi 

I wanted to use yaml along with swagger-tool (against default json) . I am currently running weather example app . 

Reason , because swagger editor reads yaml ( not sure json , atleast not documented well )

-Raje

**Comment by whitlockjc** [comment]
swagger-tools works with YAML, it just doesn't do the loading/parsing of the YAML file.  Use any YAML parser you want, load the file and pass the object to the corresponding API.  All swagger-tools APIs take a JavaScript object as input.
