### ISSUE TITLE
Update swagger-ui to newest version

### ISSUE THREAD

**Issue by sebastianwahn** [apigee-127/swagger-tools#384]
On my local system, there is an error with the following message and trace:

```
index.js:24 Uncaught TypeError: Cannot read property '0' of undefined
SwaggerUi.partials.signature.getInlineModel @ index.js:24 SwaggerUi.partials.signature.createParameterJSONSample @ index.js:24 SwaggerUi.Views.ParameterView.Backbone.View.extend.render @ index.js:24 SwaggerUi.Views.OperationView.Backbone.View.extend.addParameter @ index.js:24 SwaggerUi.Views.OperationView.Backbone.View.extend.render @ index.js:24 SwaggerUi.Views.ResourceView.Backbone.View.extend.addOperation @ index.js:24 SwaggerUi.Views.ResourceView.Backbone.View.extend.render @ index.js:24 SwaggerUi.Views.MainView.Backbone.View.extend.addResource @ index.js:24 SwaggerUi.Views.MainView.Backbone.View.extend.render @ index.js:24 window.SwaggerUi.Backbone.Router.extend.render @ index.js:24 
options.success @ index.js:24
SwaggerClient.buildFromSpec @ resolver.js:455 
Resolver.finish @ spec-converter.js:65 
(anonymous function) @ schema-markup.js:464 
Resolver.resolve @ schema-markup.js:505 
obj.on.response @ resolver.js:219 
responseInterceptor @ resolver.js:710
obj.on.response @ resolver.js:714
(anonymous function) @ schema-markup.js:186
Request.callback @ index.js:24
(anonymous function) @ index.js:24
Emitter.emit @ index.js:24
xhr.onreadystatechange @ index.js:24
```

According to https://github.com/swagger-api/swagger-ui/issues/1903 this is fixed on the master branch.
I suggest to use an intermediate version of swagger-ui in the meantime.

**Comment by avianey** [comment]
Any news about this, would be great to release with latest version of swagger-ui

**Comment by whitlockjc** [comment]
I will release a new version of swagger-tools with the swagger-ui update as soon as I can.  If you do not want to wait, feel free to use the built-in ability to use a custom _(like the latest)_ swagger-ui build documented here: https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swaggeruioptions

**Comment by keithchilders** [comment]
Hi @whitlockjc ,

I brought in swagger-ui from the latest public npm module then switched to using it with options.swaggerUiDir in the middleware configuration. Because the dist version lacks your mod that looks for a response header to get the default path to the spec, it loads the petstore by default. Can you recommend a way to pass the right default url for the spec into the stock swagger-ui? I see its code is looking for url= ... perhaps redirect /docs to /docs?url=http://server/api-docs before the swagger-ui middleware?

**Comment by whitlockjc** [comment]
The best thing would be to look at the code here: https://github.com/apigee-127/swagger-tools/blob/master/middleware/swagger-ui/index.html#L98  That is where I call `swagger-tools` to get the URL from `swagger-tools` and then I initialize `swagger-ui` using that URL.

**Comment by mig-1** [comment]
I tried to use options.swaggerUi, but faced with a problem.
I could update Swagger version  with `app.use(middleware.swaggerUi({ swaggerUiDir: "node_modules/swagger-ui/dist" }));`  
But I have problem with files in `swagger-ui/lib`. This files are not updated. They are still old.
