### ISSUE TITLE
swaggerMetadata middleware should allow passing options to body parser

### ISSUE THREAD

**Issue by ronkot** [apigee-127/swagger-tools#390]
I'm having problem with the default 100kb limit on body size. I can get around this locally by adding `limit` option manually to `swagger-metadata.js`, but this is not desirable solution:

`var jsonBodyParser = bp.json({
  limit: '10mb'
});`

One should be able to pass extra body parser params during middleware initialization.

**Comment by whitlockjc** [comment]
This is a duplicate to #287 and a few others.  Long story short, use your own middleware configured for your own needs prior to initializing any of the swagger-tools middleware and the provided parser middlewares will not be used.  They are only provided as a convenience and are intended to be overridden by the server author in cases like this.

**Comment by ronkot** [comment]
Thanks @whitlockjc, and sorry for dup :-) I tried to read the swagger-tools source code before opening this issue and for me it seemed like there was no way to define an own body parser. Apparently I didn't understand body parser middleware behaviour well enough.

So is the beef that if body has already been parsed upstream, the downstream parsers just skip their work?

**Comment by whitlockjc** [comment]
Pretty much.  As a convenience, I ship some parser middlewares.  But they are only used when necessary, which is when swagger-metadata tries to process a parameter.
