### ISSUE TITLE
Not enough feedbacks from swaggerValidator

### ISSUE THREAD

**Issue by mikspi** [apigee-127/swagger-tools#391]
I am implementing a JSON post request in my API. The JSON has to have the mandatory fields that are listed in my swagger.yaml. I am using the swagger validator middleware to validate the posted JSON. If a field is missing I get this error:

`Request validation failed: Parameter (body) failed schema validation`

It doesn't say which field is missing. Is there a way to see more details? Needless to say, it would be useful for the end users who are using my API to get a feedbacks on the JSON they sent and that didn't pass the check.

Thanks,
Mike

**Comment by whitlockjc** [comment]
Well, it tells you the parameter name _(`body`)_ and the reasons as to why are located in the error object itself.  This is documented here: https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swagger-middleware-errors

**Comment by mikspi** [comment]
My express error handler was printing just `err.message`, that's why I didn't see enough. The feedback is rich of information. Thanks for the answer and for the library!

**Comment by whitlockjc** [comment]
You got it.
