### ISSUE TITLE
Define response with array of objects

### ISSUE THREAD

**Issue by atulatgithub** [apigee-127/swagger-tools#392]
Hello,
How can i define a response of arrays  eg
[
 {"name", "atul"),
{"name", "himu"}
]

I have define as below 
"schema": {
              "type": "array",
              "$ref": "#/definitions/SalesByChartResponse"
            }

but it taking as object.

@earth2marsh 
@whitlockjc

**Comment by whitlockjc** [comment]
```json
{
  "type": "array",
  "items": {
    "$ref": "#/definitions/SalesByChartResponse"
  }
}
```

This is described in the second table in this section: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object
