### ISSUE TITLE
validating request object succeeds for properties unknown in schema

### ISSUE THREAD

**Issue by smoebody** [apigee-127/swagger-tools#397]
Hi,
is it true that unspecified properties in the schema object of a request parameter are permitted by the validator? if yes, how can i forbid arbitrary properties in the request parameter? the `readOnly` flag seems also not to work according to https://github.com/OAI/OpenAPI-Specification/issues/333

thanks in advance

**Comment by whitlockjc** [comment]
You need to set `additionalProperties` to `false`.
