### ISSUE TITLE
Importing different Swagger-ui build to swagger-tools

### ISSUE THREAD

**Issue by MatWrz** [apigee-127/swagger-tools#404]
I've made changes to swagger-ui and built a dist from it. When I try to replace the dist from my swagger build with the one in swagger-tools my docs don't appear correctly.

**Comment by whitlockjc** [comment]
swagger-tools provides you with the configurability to use your own swagger-ui distribution but you own it.  I will do my best to help you out but it is likely not a swagger-tools bug or issue.  I will need more details on what _"my docs don't appear correctly"_ and possibly part of your `index.html` to see how you're instantiating swagger-ui.

**Comment by MatWrz** [comment]
I replaced the swagger-ui folder of swagger-tools with a dist built in swagger-ui. There wasn't much configuration on my part.

**Comment by whitlockjc** [comment]
Well, the `index.html` in the distribution I publish has some extra code to go get the URL to the Swagger document and without your code having that, it likely will not _just work_.  You'll either need to set the `url` property that swagger-ui uses to retrieve the Swagger document URL or you'll need to take the JavaScript part from my `index.html` and just replace the JavaScript part in your `index.html`.

**Comment by MatWrz** [comment]
Changed the javascript part of the index.html, api docs still don't display
[index.zip](https://github.com/apigee-127/swagger-tools/files/353088/index.zip)

**Comment by whitlockjc** [comment]
Do you have any errors in your browser console?  Can you post a screenshot?

**Comment by MatWrz** [comment]
![exc](https://cloud.githubusercontent.com/assets/11278500/16687726/48a03bc6-44e8-11e6-91ba-ee482fa752ad.png)
Here's what displays

**Comment by MatWrz** [comment]
![capture](https://cloud.githubusercontent.com/assets/11278500/16689818/bace29c4-44f2-11e6-8525-82f2d81485a0.PNG)

Also encountering this

**Comment by whitlockjc** [comment]
If you type in the full URL to your Swagger document, does it work?  It seems like it should be `http://localhost:10010/api-docs`.

**Comment by MatWrz** [comment]
Not working, it opens to that url on launch
![capture5](https://cloud.githubusercontent.com/assets/11278500/16693355/d3d9d818-4502-11e6-9c46-932217eb36b7.PNG)

**Comment by whitlockjc** [comment]
The URL to swagger-ui is what is being opened on launch, the URL I gave you was for the URL to the Swagger document.  If you access that URL directly in the browser, do you get your Swagger document in return?  If not, swagger-ui shouldn't work and we need to figure out where your Swagger document is served.  Based on the port of `10010` I assume you're not using swagger-tools directly but something like swagger-node?

**Comment by MatWrz** [comment]
I do get the swagger document when I open that url 
Using swagger express to run the server and feeding swagger ui that sits in swagger tools.
Tried just pointing to the swagger-ui module with no luck

**Comment by whitlockjc** [comment]
Gotcha.  Thanks for clarifying.  I'm not sure what the issue could be.  Does your swagger-ui work fine outside of swagger-tools?  swagger-tools is just a static site server for swagger-ui so getting it working outside of swagger-tools first is a must.  I'll look at your .zip to see if I can find something out.

**Comment by MatWrz** [comment]
I think I narrowed it down to issues with my swagger ui build and not swagger tools itself. As I have some builds working and others not. Thanks a lot for your help.

**Comment by whitlockjc** [comment]
Let me know if I can help further.
