### ISSUE TITLE
Showing debug(....) output using WebStorm

### ISSUE THREAD

**Issue by reselbob** [apigee-127/swagger-tools#405]
This is a very newbie question, still....

I am working with Swagger Tools under Webstorm.

I want to print out the debug() statements at run time.

For example: node_modules/swagger-tools/middleware/swagger-security.js line164

```javascript
  debug('    Request allowed: %s', allowed);
```
Tell me please, how do I enable output at runtime.

**Comment by whitlockjc** [comment]
Ask and you shall receive: https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swagger-middleware-debugging

**Comment by reselbob** [comment]
Thank you
