### ISSUE TITLE
Where is the err.message created in an custom OAuth handler displayed in the eventual response?

### ISSUE THREAD

**Issue by reselbob** [apigee-127/swagger-tools#406]
Hi;

I am writing a handler for Swagger Security. I pass the handler function definition in as part of the middleware initialization.

```javascript
var oauthHandler = require("./handlers/oauthHandler");

var options = {
  swaggerUi: './api/swagger.json',
  controllers: './controllers',
  oauth:oauthHandler.handler,
  useStubs: process.env.NODE_ENV === 'development' ? true : false // Conditionally turn on stubs (mock mode)
};

app.use(middleware.swaggerSecurity(options));
```

The OAuth handler checks to make sure a good token is present. If not, an ``err`` object is created as specified in the documentation.

```javascript
.
.
.
    var reply = getTokenSync(request.headers);
    if (!reply.token) {
        var err = {};
        err.message = reply.message;
        err.state = null;
        err.code = reply.statusCode;
        err.statusCode = reply.statusCode;
        err.headers = request.headers;// yeah, this needs to be cleaned up

        callback(err); 
        return;
    } 
```

However, the custom message I create never makes it back anywhere in the ``response``. Either I am doing something terribly wrong, for which I apologize and welcome correction. Or as the err object gets passed on through the middleware it gets transformed. In addition, the ``response.headers`` get transformed too. Lastly, when the`` response`` makes it out of the server, ``response.body`` is an empty object.

Tell me please, where is my custom error message in the ``response`` emitted from the server? Do I need to do anything special to get the message to display in the sent ``response``? Better yet, is there anyway I can tell the middleware to embed the ``err.message`` in the response.body?

Thanks in advance.

I know that must be a pretty elementary inquiry. But, my sense of professionalism requires me to give those using my API more than a sole 401 statusCode.

**Comment by whitlockjc** [comment]
You could create an error hander middleware to identify your OAuth errors and update the response accordingly.  That's what I'd do.  As for where in the swagger-tools middleware the `err.message` is overridden/set, I don't see anything.  I didn't write the security middleware so I'd have to dive deeper if the suggested approach isn't good enough.

**Comment by reselbob** [comment]
I like your idea. Can you point me to a place where I can read up on how to create a middleware error handler, or review a sample?

Again, thank you for your help Jeremy. @whitlockjc .

**Comment by whitlockjc** [comment]
Here is an example _(modified from https://github.com/apigee-127/swagger-tools/blob/master/examples/2.0/index.js):

```js
'use strict';

var app = require('connect')();
var http = require('http');
var swaggerTools = require('swagger-tools');

var serverPort = 3000;

// swaggerRouter configuration
var options = {
  controllers: './controllers',
  useStubs: process.env.NODE_ENV === 'development' ? true : false // Conditionally turn on stubs (mock mode)
};

// The Swagger document (require it, build it programmatically, fetch it from a URL, ...)
var swaggerDoc = require('./api/swagger.json');

// Initialize the Swagger middleware
swaggerTools.initializeMiddleware(swaggerDoc, function (middleware) {
  // Interpret Swagger resources and attach metadata to request - must be first in swagger-tools middleware chain
  app.use(middleware.swaggerMetadata());

  // Validate Swagger requests
  app.use(middleware.swaggerValidator());

  // Route validated requests to appropriate controller
  app.use(middleware.swaggerRouter(options));

  // Serve the Swagger documents and Swagger UI
  app.use(middleware.swaggerUi());

  // Create an error handler to allow me to process errors before being sent to the client
  app.use(function (err, req, res, next) {
    // All errors that swagger-tools creates/handles are sent downstream via `next`.  This
    // means that all errors swagger-tools creates/handles will be sent here and can be
    // handled as your application deems fit.
  });

  // Start the server
  http.createServer(app).listen(serverPort, function () {
    console.log('Your server is listening on port %d (http://localhost:%d)', serverPort, serverPort);
  });
});
```

**Comment by whitlockjc** [comment]
While this link is to Express.js documentation, Express was originally built using Connect and has continue to use its middleware paradigm: http://expressjs.com/en/guide/error-handling.html
