### ISSUE TITLE
Update swagger-ui

### ISSUE THREAD

**Issue by Nepoxx** [apigee-127/swagger-tools#408]
The provided swagger-ui is outdated, is there any opposition to updating it to the latest version?

I'm using the `swaggerUiDir` option (which seems incompatible with the `apiDocs` option) of the swaggerUi middleware as a workaround for [this issue](https://github.com/swagger-api/swagger-ui/issues/2292), however having swagger-tools have the latest version would be a plus :)

**Comment by whitlockjc** [comment]
There is a PR to update it but I've not pulled it as I'm waiting for a json-refs release to take care of these things.  As for `swaggerUiDir`, the only conflict is that the shipped swagger-ui has special code in the `index.html` that goes to the server and gets the Swagger document URI and that obviously will not be present in the custom swagger-ui version.  It's an easy fix but updating swagger-ui would be ideal.

**Comment by Nepoxx** [comment]
Got it. I'm merged that code in the latest swagger-ui version and it works beautifully. Thanks for the help. 

(ref: https://github.com/apigee-127/swagger-tools/pull/399 )
