### ISSUE TITLE
Swagger validator for nodejs is not outputting the failed schema validation as json  

### ISSUE THREAD

**Issue by vinay32724** [apigee-127/swagger-tools#412]
Hi , 

I used the following swagger.json and autogenerated nodejs server code and run the server . Made an POST api call http://localhost:8080/api/pets with intentionally {"d" : "superpet"} json making name  parameter missing

I except a json which should say missing name parameter , but instead  I get
Error: Parameter (pet) failed schema validation<br> &nbsp; &nbsp;at throwErrorWithCode (/Users/vinayk/Downloads/nodejs-server-server/node_modules/swagger-tools/lib/validators.js:121:13)<br> &nbsp; &nbsp;at Object.module.exports.validateAgainstSchema (/Users/vinayk/Downloads/nodejs-server-server/node_modules/swagger-tools/lib/validators.js:176:7)<br> &nbsp; &nbsp;at /Users/vinayk/Downloads/nodejs-server-server/node_modules/swagger-tools/middleware/swagger-validator.js:143:22<br> &nbsp; &nbsp;at /Users/vinayk/Downloads/nodejs-server-server/node_modules/async/lib/async.js:356:13<br> &nbsp; &nbsp;at async.forEachOf.async.eachOf (/Users/vinayk/Downloads/nodejs-server-server/node_modules/async/lib/async.js:233:13)<br> &nbsp; &nbsp;at _asyncMap (/Users/vinayk/Downloads/nodejs-server-server/node_modules/async/lib/async.js:355:9)<br> &nbsp; &nbsp;at Object.map (/Users/vinayk/Downloads/nodejs-server-server/node_modules/async/lib/async.js:337:20)<br> &nbsp; &nbsp;at validateValue (/Users/vinayk/Downloads/nodejs-server-server/node_modules/swagger-tools/middleware/swagger-validator.js:136:11)<br> &nbsp; &nbsp;at /Users/vinayk/Downloads/nodejs-server-server/node_modules/swagger-tools/middleware/swagger-validator.js:343:21<br> &nbsp; &nbsp;at /Users/vinayk/Downloads/nodejs-server-server/node_modules/async/lib/async.js:356:13

What I'm I missing??Pls help
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Swagger Petstore",
    "description": "A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "name": "Swagger API Team"
    },
    "license": {
      "name": "MIT"
    }
  },
  "host": "localhost",
  "basePath": "/api",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/pets": {
      "get": {
        "description": "Returns all pets from the system that the user has access to",
        "operationId": "findPets",
        "produces": [
          "application/json",
          "application/xml",
          "text/xml",
          "text/html"
        ],
        "parameters": [
          {
            "name": "tags",
            "in": "query",
            "description": "tags to filter by",
            "required": false,
            "type": "array",
            "items": {
              "type": "string"
            },
            "collectionFormat": "csv"
          },
          {
            "name": "limit",
            "in": "query",
            "description": "maximum number of results to return",
            "required": false,
            "type": "integer",
            "format": "int32"
          }
        ],
        "responses": {
          "200": {
            "description": "pet response",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Pet"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      },
      "post": {
        "description": "Creates a new pet in the store.  Duplicates are allowed",
        "operationId": "addPet",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "pet",
            "in": "body",
            "description": "Pet to add to the store",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewPet"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "pet response",
            "schema": {
              "$ref": "#/definitions/Pet"
            }
          },
           "400": {
            "description": "pretty bad request sent by you",
            "schema": {
              "$ref": "#/definitions/Pet"
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      }
    },
    "/pets/{id}": {
      "get": {
        "description": "Returns a user based on a single ID, if the user does not have access to the pet",
        "operationId": "findPetById",
        "produces": [
          "application/json",
          "application/xml",
          "text/xml",
          "text/html"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of pet to fetch",
            "required": true,
            "type": "integer",
            "format": "int64"
          }
        ],
        "responses": {
          "200": {
            "description": "pet response",
            "schema": {
              "$ref": "#/definitions/Pet"
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      },
      "delete": {
        "description": "deletes a single pet based on the ID supplied",
        "operationId": "deletePet",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of pet to delete",
            "required": true,
            "type": "integer",
            "format": "int64"
          }
        ],
        "responses": {
          "204": {
            "description": "pet deleted"
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Pet": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/NewPet"
        },
        {
          "required": [
            "id"
          ],
          "properties": {
            "id": {
              "type": "integer",
              "format": "int64"
            }
          }
        }
      ]
    },
    "NewPet": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "tag": {
          "type": "string"
        }
      }
    },
    "ErrorModel": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}

**Comment by whitlockjc** [comment]
Unless you've got an error handler turning the validation error into a valid response, this is expected.

**Comment by vinay32724** [comment]
Hi Jeremy,

   It would be great if you provide me an example how I can attach an error
handler to turn the validation error into a valid response .

Regards,
Vinay

**Comment by whitlockjc** [comment]
https://github.com/apigee-127/swagger-tools/issues/406#issuecomment-231549585
