### ISSUE TITLE
Required when as an enhancement to the validation

### ISSUE THREAD

**Issue by fastcodejava** [apigee-127/swagger-tools#423]
​​Right now in the definitions for the request body takes required true. Is it possible to make it conditional? ​
E.g. we have create account which can be an individual account or a business account. 
​When the ​type is individual we can make have first name, last name ​etc ​required. 
And when the type ​is ​business ​we can have ​business name required. 
Right now we are having to do all this in the cod​e​.
It would be nice if ​s​wagger ​tools ​itself can do it.

**Comment by whitlockjc** [comment]
Swagger does not support this so swagger-tools will not support this.
