### ISSUE TITLE
x-swagger-router-validater for the validation

### ISSUE THREAD

**Issue by fastcodejava** [apigee-127/swagger-tools#424]
Can we add x-swagger-router-validater (similar to x-swagger-router-controller) for validation? 
Right now we are having to do all the validation in the cod​e​.
It would be nice if ​s​wagger ​tools ​itself can do it.

**Comment by whitlockjc** [comment]
I'm not sure I understand.  If you use the `swagger-validator` middleware, you get validation already.  That's one of the main features of swagger-tools.

**Comment by fastcodejava** [comment]
Sorry this is for more custom validation on top of the built in validation. 
Here is more detailed [description ](https://github.com/apigee-127/swagger-tools/issues/423).

**Comment by whitlockjc** [comment]
This is a duplicate of #140.
