### ISSUE TITLE
date-time validator rejects value with Z suffix (e.g. 2016-09-22T23:19:08Z)

### ISSUE THREAD

**Issue by mattoshry** [apigee-127/swagger-tools#428]
The dateTimeRegExp in lib/validators.js:49 allows for 'z' or an offset, but the code added as part of [1] around line 114 assumes the regex matched an offset and not a 'z'. Also unclear why this is wrapped in try/catch.

```
 try {
    timezoneHours = Number(matches[6]);
    timezoneMinutes = Number(matches[7]);
  } catch (err) {
    return false;
  }
```

[1] https://github.com/apigee-127/swagger-tools/commit/5918b5ddc03c786d85c141716272df52678af2b0#diff-dafdb143c8e94abc7ec70930d4ba6fffR115

**Comment by whitlockjc** [comment]
Closing this in favor of #428.  We'll discuss there.
