### ISSUE TITLE
Unable to install swagger-tools on Windows server / Azure web service using NPM.

### ISSUE THREAD

**Issue by uint8** [apigee-127/swagger-tools#437]
Hi, 

I've been attempting to install a swagger project onto my azure web service. So far this swagger-tools seems to be giving the most trouble. I first attempted to use the package.json to specify the libraries needed: this failed to deploy as intended. Next I used Microsoft powershell to directly attempt to install it globally. Here's the results

PS D:\home> npm install swagger-tools -g
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\4.4.7\\node.exe" "D:\\Program Files (x86)\\npm\\2.15.8\\node_modules\\npm\\bin\\npm-cli.js" "install" "swagger-tools" "-g"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path D:\local\AppData\npm\node_modules\swagger-tools\node_modules\swagger-converter\node_modules\lodash.clonedeep\node_modules\lodash._basecreatecallback\node_modules\lodash.bind\node_modules\lodash._createwrapper\node_modules\lodash._basebind\package.json.2826373707
npm ERR! code EINVAL
npm ERR! errno -4071
npm ERR! syscall rename

npm ERR! EINVAL: invalid argument, rename 'D:\local\AppData\npm\node_modules\swagger-tools\node_modules\swagger-converter\node_modules\lodash.clonedeep\node_modules\lodash._basecreatecallback\node_modules\lodash.bind\node_modules\lodash._createwrapper\node_modules\lodash._basebind\package.json.2826373707' -> 'D:\local\AppData\npm\node_modules\swagger-tools\node_modules\swagger-converter\node_modules\lodash.clonedeep\node_modules\lodash._basecreatecallback\node_modules\lodash.bind\node_modules\lodash._createwrapper\node_modules\lodash._basebind\package.json'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\4.4.7\\node.exe" "D:\\Program Files (x86)\\npm\\2.15.8\\node_modules\\npm\\bin\\npm-cli.js" "install" "swagger-tools" "-g"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path D:\home\npm-debug.log.2915258447
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'D:\home\npm-debug.log.2915258447'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'D:\home\npm-debug.log.2915258447']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'D:\\home\\npm-debug.log.2915258447' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\home\npm-debug.log
PS D:\home>

I don't know if there's a problem with the library or if I'm doing something wrong. 

Any help is appreciated. 

Thanks so much!

**Comment by whitlockjc** [comment]
This is an issue with NPM and Windows, related to long paths.  If I google the issue, I find a number of bugs reported to NPM itself and other Node.js modules affected by it.  Some people report upgrading to NPM 3.x fixes the issue because there was work done to limit this but some report it didn't help.

I'll help if possible but this isn't an issue with `swagger-tools` itself.
