### ISSUE TITLE
Swagger tools is converting the payload to an array

### ISSUE THREAD

**Issue by fastcodejava** [apigee-127/swagger-tools#438]
If I have a schema for the request body as an array and I put an object Swa​​gger tools is converting that to an array.
Is this the expected behavior or this is a bug?

**Comment by whitlockjc** [comment]
It would be great to have an example of the request body definition in Swagger and the request body being made.  There is zero chance of reproducing this issue without these things.

**Comment by fastcodejava** [comment]
I have my defined as

       - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/MyBodyList"


My definition : 

    MyBody: 
       type: array
       items:
          $ref: "#/definitions/MyBody"


The definition for `MyBody` has two properties, foo and bar.

Now I put the request body as 

    {
        "foo": "x",
        "bar": "y"
    }

it becomes an array:

    {{
        "foo": "x",
        "bar": "y"
    }]

**Comment by whitlockjc** [comment]
That shouldn't happen.  It should fail with an invalid type error.  I'll get working on it.

**Comment by SameerSiddiqui** [comment]
@fastcodejava  nice find.

**Comment by fastcodejava** [comment]
Is it possible that I can submit a PR on this?

**Comment by fastcodejava** [comment]
I see that it is being done deliberately : https://github.com/apigee-127/swagger-tools/blob/master/middleware/helpers.js#L222.
If I do remove it will it cause any other problems?

**Comment by whitlockjc** [comment]
Yes, it would cause problems.  For query parameters or form parameters, this is working as designed.  So what we need to do is make sure we don't do this when the parameter type is body.  It's a simple fix but I won't be able to work on this project until the 31st.  Sorry for the delay.

**Comment by fastcodejava** [comment]
@whitlockjc Did you get a chance to look at this PR? Is it worth merging?

**Comment by whitlockjc** [comment]
This has been fixed.  Long story short, `middleware/helpers.js#convertValue` no longer converts `body` parameters _(or responses)_ to an `array` when the expected type is `array` but the provided body/response is not an `array`.
