### ISSUE TITLE
Using Async Functions in Controllers

### ISSUE THREAD

**Issue by Robbilie** [apigee-127/swagger-tools#443]
So I am currently rewriting my applications API to use swagger. 
doing that, i am reusing my code which is already using node v7 async/await. 

in general, that shouldnt be an issue, if the controller code would get the controller names from the YAML file instead of scanning the whole directory which possibly leads to overhead. Alternatively, not expecting objects in the export of a file would be an option. but sadly, my code exports classes, with static methods. so, reading a directory doesnt work unless both things fixed.

since static methods cant be async at the same time my static methods return async methods instead, no big thing, i had to create the controller object myself anyways so i could just call them and store the returned value in the object.

finally, i had my controller object with all names mapped properly and methods as values. should work, right?
no.
the functions are not functions, according to lodash. 
https://github.com/lodash-archive/lodash-compat/blob/master/lodash.js#L8867-L8872

looking a bit closer at that method (which seems to resolve bugs i never ran into…) i debugged and checked, the first part is true, the second isnt, weird, typeof returned "function".
turns out, async functions are, well, async functions: 
'[object AsyncFunction]'

i ended up wrapping another normal function around the async function.

took me about 3 hours now to resolve all these issues, finally seems to work, really ugly workarounds…

what im asking for? looking at the lodash-compat repo, i dont see it getting support for async functions, you might want to consider switching to a different piece of code, maybe one with a smaller footprint aswell, was kinda blown away by the dependencies of your project…

thanks nowadays for this useful project

**Comment by pospi** [comment]
I just use https://www.npmjs.com/package/express-async-wrap for this and it works great (;

**Comment by Robbilie** [comment]
no i use nodejs v7 and use native async...

**Comment by danielsiwiec** [comment]
I'm having a similar problem when using native asyncs. Has this been resolved?

**Comment by gedgaudasnikita** [comment]
What i'm doing right now is using redirect functions in fashion of

`
const controller = (req, res) => {
  controllerAsync(req,res).then();
};
`

Because the async/await is built on top of Promises. Not gonna lie, not the best looking workaround, so waiting to hear more

**Comment by skazska** [comment]
I also experience a problem when using native async function controllers. 
because _.isFunction(value)  gives false  for value is async function
while typeof value === 'function'
possibly latter version of lodash is would be better here

**Comment by whitlockjc** [comment]
I'll be updating dependencies and cutting a release soon, that _should_ fix the `_.isFunction` false negative.

**Comment by antonioasmoura** [comment]
I'm really waiting for this!

**Comment by nimamox** [comment]
Is it released yet? I get "Cannot resolve the configured swagger-router handler" for async routes on 0.10.1.

**Comment by whitlockjc** [comment]
I still haven't cut a release yet.  I apologize.

**Comment by nimamox** [comment]
Oh, that's OK. I was just trying to use the latest github code, but got the same error message:
```
$ npm install git+https://github.com/apigee-127/swagger-tools.git
mam@0.0.1 /Users/nima/WebstormProjects/mam
└─┬ swagger-tools@0.10.1  (git+https://github.com/apigee-127/swagger-tools.git#8a9e31a38f44ceeaab62259083f3cfd961564296)
```
```operationId: addNewFolder```

```module.exports.addNewFolder = async (req, res) => {...}```

```{'message': 'Cannot resolve the configured swagger-router handler: folder_addNewFolder'}```

**Comment by dooman87** [comment]
@whitlockjc Do you need any help with the release? Would be nice to have this guy fixed.

**Comment by thecodejunkie** [comment]
I also ran into this issue today

**Comment by whitlockjc** [comment]
@dooman87 I'm all for extra help.  I use to work on this at work but now that it's a personal project, a deprecated one _(See #335)_, I don't have as much time to make things happen as quickly.

**Comment by dtothefp** [comment]
same issue here after upgrading to node 8.5.0 and using babel-present-env with `"node": "current"`

this is quite funny when logging in the swagger router

```js
console.log(handlerId, _.isFunction(value), typeof value);

if (_.isFunction(value) && !handlerCache[handlerId]) {
    handlerCache[handlerId] = value;
}
```

```sh
server_1   | ****************** stage.controller_getStage true function
server_1   | ****************** stage.controller_singleStage true function
server_1   | ****************** stage.controller_getStatus true function
server_1   | ****************** stage.controller_getStatorByStage true function
server_1   | ****************** stage.controller_getInitialDatafields true function
server_1   | ****************** status.controller_getStatus true function
server_1   | ****************** status.controller_singleStatus true function
server_1   | ****************** user.controller_getUsers true function
server_1   | ****************** user.controller_createUser false function
server_1   | ****************** user.controller_updateUser false function
server_1   | ****************** user.controller_updateMultipleUser false function
server_1   | ****************** user.controller_singleUser false function
```

all `false` by lodash are indeed async functions

**Comment by ychetanreddy** [comment]
ran into same issue, has the fix been merged? Just curious!

**Comment by thecodejunkie** [comment]
It would be suuuuuuuuuuuuuuuuuuuper useful if I could get this fix merged and pushed out. Like really useful ❤️

**Comment by whitlockjc** [comment]
We started working on rolling a release yesterday.  I hope to have it done today but no promises.  Should be within the next day or so.

**Comment by thecodejunkie** [comment]
@whitlockjc awwww yeah!

**Comment by whitlockjc** [comment]
It should be fixed in `swagger-tools@0.10.2` that was just released.  Can you verify?  I upgraded `lodash` to latest and it _should_ fix this.

**Comment by thecodejunkie** [comment]
@whitlockjc Works like a charm, thanks!

**Comment by tforster** [comment]
I too am getting the same issue in a Swagger Node project. I have installed swagger-node https://github.com/swagger-api/swagger-node which seems to be using an old version of swagger-connect and other outdated dependencies. What would be the best way to update swagger-tools when it is depended several levels deeper than my project's package.json?

**Comment by whitlockjc** [comment]
As mentioned [here](https://github.com/apigee-127/swagger-tools/issues/443#issuecomment-336029507), this is fixed in `swagger-tools`.  For `swagger-node` to pick that up, they'd need to update their code to use the latest release of `swagger-tools`.

**Comment by LostCrew** [comment]
@tforster if you use yarn, you can get unstuck by [manually setting the resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) in your `package.json`: 

```js
"resolutions": {
  "swagger-tools": "0.10.3"
}
```

So far, it seems to be working great for me.
