### ISSUE TITLE
Swagger validator does not work with anchor variables

### ISSUE THREAD

**Issue by fastcodejava** [apigee-127/swagger-tools#446]
This is in continuation of a [previous issue](https://github.com/apigee-127/swagger-tools/issues/426). 
When I do `swagger-tools validate swagger.yaml` I get this error : 

`error: JS-YAML: unidentified alias "volosCacheSession" at line 28, column 36:
cache-session: *volosCacheSession
`

The swagger file is as shown below :

```
swagger: "2.0"
x-a127-config:
  schemes: &SCHEMES
  oauth2: &volosOAuth
  cache: &volosCache
  cache-session: &volosCacheSession

```

Although there are quite a few anchor variables without value it only complains about one `volosCacheSession`.
Is this a bug?

**Comment by whitlockjc** [comment]
I don't own the YAML parser but to me, if it complains it's an issue.  If you think it's something that _should_ work, you might want to file a bug here: https://github.com/nodeca/js-yaml

**Comment by fastcodejava** [comment]
Even though swagger-tools validate fails a127 still starts. It replaces anchor variables with values in the configuration files. Can swagger-tools validate work with configuration files as well?

**Comment by whitlockjc** [comment]
`a127` starts because it feeds the values into the Swagger document _prior_ to validating it, whereas the Swagger document on its own fails to validate because it's incomplete.  There is nothing `swagger-tools` can do.
