### ISSUE TITLE
discrepancy among, Swagger-CLI, Swagger editor and Swagger UI

### ISSUE THREAD

**Issue by simar15** [apigee-127/swagger-tools#447]
Hi,
I have created swagger-spec, and was trying to validate it using swagger-cli, the problem is swagger-cli throws errors which are not displayed in swagger-editor and swagger UI renders it perfectly.

Any ideas on that? Any help would be appreciated.

**Comment by chadxz** [comment]
1. what version of the swagger-cli are you using? 
2. what errors are you experiencing? 
3. would you be able to provide an example? maybe reduce the problem to a simple swagger spec that illustrates the issue you are experiencing?

**Comment by whitlockjc** [comment]
@chadxz Thanks for helping out, I really appreciate it.

**Comment by whitlockjc** [comment]
As for the answer, swagger-ui does not do any validation and will gladly render an invalid Swagger document as long as there is enough information there to render.

**Comment by whitlockjc** [comment]
Reopen if you have a specific recipe that you feel is valid but swagger-tools is reporting invalid.

**Comment by simar15** [comment]
@chadxz Thanks for the prompt reply, @whitlockjc

**Comment by simar15** [comment]
@chadxz , Thanks for the prompt reply, @whitlockjc, the doubt originates from responses in my swagger spec, I have something like this
responses: 
   200:
       $ref: something
       schema:
           $ref:  something else

Swagger editor gives me a warning saying extra json properties will be ignored, but swagger UI renders perfectly and pulls stuff from both references, when I tried to validate it through swaager-cli, the same problem came forward as error.

**Comment by whitlockjc** [comment]
Yup, that's no surprise.
