### ISSUE TITLE
open API 3.0 spec support

### ISSUE THREAD

**Issue by leslie-wang** [apigee-127/swagger-tools#475]
OpenAPI will release version 3.0 at Feb 28, 2017. https://www.openapis.org/blog/2017/01/24/a-new-year-a-new-specification. It would be useful if this tool can support 3.0 as well.

**Comment by whitlockjc** [comment]
`swagger-tools` is officially deprecated _(See #335)_ so any future OAI support will be done in [Sway](https://github.com/apigee-127/sway).  I realize sway doesn't have the middleware that `swagger-tools` does but the effort has started to bridge the gap here: https://github.com/whitlockjc/sway-connect

**Comment by leslie-wang** [comment]
Create new request at sway. https://github.com/apigee-127/sway/issues/128

**Comment by whitlockjc** [comment]
Thanks @leslie-wang.

**Comment by SalathielGenese** [comment]
Hi,

Please have the following displayed in bold in readme. How have I miss this ?

> swagger-tools is officially deprecated (See #335) so any future OAI support will be done in Sway.
