### ISSUE TITLE
how to submit a pull request

### ISSUE THREAD

**Issue by sbansal6** [apigee-127/swagger-tools#476]
i want to submit a pull request that allows to keep .test and .spec files next to corresponding controller files (one line change), i have created a branch out of master , how do i submit the changes for a merge approval.

I am getting Permission to apigee-127/swagger-tools.git denied to sbansal6 , if i try to push my branch to remote.

-Saurabh

**Comment by ckrooss** [comment]
The usual workflow is to fork the repo to your own github account, push your branch to your own fork and then create a PR from your repo to this repo.

**Comment by whitlockjc** [comment]
This project follows the typical GitHub flow.  For this repo, do your work, submit a PR.  The only caveat is you need to follow the short [Contributing Guidelines](https://github.com/apigee-127/swagger-tools#contributing).
