### ISSUE TITLE
Support for JSR-303 Custom ConstraintValidator

### ISSUE THREAD

**Issue by KITSKevinPerry** [apigee-127/swagger-tools#477]
I would like to be able to specify something in the Swagger definition of an object that allows code-generation to annotate the model with @MyConstraintValidator where MyConstraintValidator.java is an existing constraint validator defined something like the simple constraint definition defined here: [http://beanvalidation.org/1.0/spec/#example-definition-notnull](http://beanvalidation.org/1.0/spec/#example-definition-notnull)

**Comment by whitlockjc** [comment]
`swagger-tools` doesn't do any codegen.  You should look into [swagger-codegen](https://github.com/swagger-api/swagger-codegen).
