### ISSUE TITLE
middleware.swaggerRouter variable

### ISSUE THREAD

**Issue by ric79** [apigee-127/swagger-tools#485]
Hello,
I need to pass to controllers the MySQL pool variable.

I other apps I was used to do: 
```
var pool = require('./utils/mysql')().createPool(appl_config)
const routes = require('./controllers')(pool);
```

How I have to modify the code?

```
var options = {
  swaggerUi: '/swagger.json',
  controllers: './controllers',
  useStubs: process.env.NODE_ENV === 'development' ? true : false // Conditionally turn on stubs (mock mode)
};
...
// Initialize the Swagger middleware
swaggerTools.initializeMiddleware(swaggerDoc, function (middleware) {
...
  app.use(middleware.swaggerRouter(options));
...
);
```
Riccardo

**Comment by whitlockjc** [comment]
You could easily do this with middleware.  You could use a middleware that is _run_ prior to the router middleware and that would set a `req` property.

Since this isn't a bug, I'm going to close this but we can continue brainstorming a solution that works for you.
