### ISSUE TITLE
oauth hard coded parameters in index.html

### ISSUE THREAD

**Issue by frogburger** [apigee-127/swagger-tools#487]
there are had coded parameters in index.html:
              initOAuth({
                clientId: "your-client-id",
                clientSecret: "your-client-secret-if-required",
                realm: "your-realms",
                appName: "your-app-name",
                scopeSeparator: ",",
                additionalQueryStringParams: {}
              });
is there any plan to make this more deployment friendly by either adding parameter whne invoking the swaggerui middleware or by configuration file... and should the scopeSeparator be " " instead of ",", and finally waht about the audience property?

**Comment by whitlockjc** [comment]
This code is from `swagger-ui`.  Please file the bug with them if you think it's wrong, but between you and me I think it's just a placeholder.
