### ISSUE TITLE
'uri-js' NPM Package version is outdated fails Node Security checks.

### ISSUE THREAD

**Issue by SiddharthMishraPersonal** [apigee-127/swagger-tools#500]
We have setup Node Security check in our project which checks vulnerabilities for any NPM package against https://nodesecurity.io/. 

├─┬ swagger-tools@0.10.1 
│ ├── async@1.5.2 
│ ├─┬ body-parser@1.12.4 
│ │ ├── bytes@1.0.0 
│ │ ├── depd@1.0.1 
│ │ ├── iconv-lite@0.4.8 
│ │ ├─┬ on-finished@2.2.1 
│ │ │ └── ee-first@1.1.0 
│ │ ├── qs@2.4.2 
│ │ └─┬ raw-body@2.0.2 
│ │   └── bytes@2.1.0 
│ ├─┬ json-refs@2.1.6 
│ │ ├─┬ path-loader@1.0.2 
│ │ │ └── superagent@3.5.2 
│ │ ├── slash@1.0.0 
│ │ └── **uri-js@2.1.1** 

We found that 'url-js' package used by 'Swagger-Tools' through 'json-refs' is outdated and should be upgraded to > 3.0.0.
For more details, please go to the website given below:

https://nodesecurity.io/advisories/100

Please suggest how to fix it?

**Comment by whitlockjc** [comment]
https://github.com/whitlockjc/json-refs/issues/109#issuecomment-294241513

**Comment by mattgrande** [comment]
`json-refs` has officially updated to v2.1.7. Any update to this?

**Comment by SiddharthMishraPersonal** [comment]
It has been fixed with latest json-refs.
