### ISSUE TITLE
Generating sample response and curl request

### ISSUE THREAD

**Issue by avivash** [apigee-127/swagger-tools#508]
Hi, I'm wondering if there is a `swagger-tools` API method to populate a sample `curl` request for a swagger entrypoint or a sample response for an entrypoint? I'm looking through the API, but haven't found a way of doing this yet. I'd really appreciate any advice you can offer. 

Thanks

**Comment by whitlockjc** [comment]
There is no support for this right now but I can see the benefit in it.

**Comment by avivash** [comment]
Okay, thanks for the quick reply. Yeah, that functionality doesn't seem to be a part of any swagger resolving libraries I've seen...
