### ISSUE TITLE
Swagger UI loading very slowly

### ISSUE THREAD

**Issue by mustafamamun** [apigee-127/swagger-tools#509]
Swagger UI takes long time to load. Sometime it gets request time out. Most likely the issue is with swagger UI. Issue here  [https://github.com/swagger-api/swagger-ui/issues/1455](url)

![screenshot from 2017-05-19 12-48-36](https://cloud.githubusercontent.com/assets/8222890/26242727/19b69470-3c92-11e7-99f1-cf7edd77e324.png)

**Comment by whitlockjc** [comment]
Yeah, I've no idea how `swagger-tools` could be the culprit here.  I'm closing this but thanks for opening it so we can track this.

**Comment by mustafamamun** [comment]
Hello,
 I am using swagger-tools to represent the UI. I thought swagger tools use swagger UI to create the view. If that is not the case then swagger tool is loading the UI very slowly.

**Comment by whitlockjc** [comment]
`swagger-tools` just uses [node-static](https://github.com/cloudhead/node-static) to deliver the `swagger-ui` assets.  What are the chances that `swagger-ui` is loading slowly due to the complexity of your Swagger document?  I'm just shooting from the hip here, no idea myself.

**Comment by mustafamamun** [comment]
The document is complex but not big.
