### ISSUE TITLE
How can I hide the Topbar and set the language type of the API document？

### ISSUE THREAD

**Issue by Luncher** [apigee-127/swagger-tools#510]
![tmp29239786](https://cloud.githubusercontent.com/assets/5138977/26336042/ae5393c2-3fa2-11e7-9141-e7947a6a0539.png)

+1. I know that you can modify the index.html file to modify the language type, Is there any other way to modify the language type? For example, add a parameter to the swaggerUi interface?

+2. I dont know how to hide the Topbar

Who can give some advice? Thanks

**Comment by whitlockjc** [comment]
That would be more of a [swagger-ui](https://github.com/swagger-api/swagger-ui) question.
