### ISSUE TITLE
How does one initializemiddleware for multiple swagger documents?

### ISSUE THREAD

**Issue by amittapalli** [apigee-127/swagger-tools#513]

**Comment by whitlockjc** [comment]
The singular call to `swaggerTools.initializeMiddleware` *DOES NOT* support this.  You could do this by chaining your calls, so long as each document has a separate base URL and/or the paths do not collide.

**Comment by amittapalli** [comment]
Is there a good example in node that allows chaining of initialize calls.  I tried to do something like that but did not seem to work.  The first document that I use to call 'swaggerTools.initializeMiddleware(swaggerDoc, function (middleware)'
seems to take precedence regardless of how many other ones I initialized after it.

**Comment by whitlockjc** [comment]
It's just like any other callback-based API.  You can use something like [async](https://www.npmjs.com/package/async) or do it manually yourself:

```js
swaggerTools.initializeMiddleware(doc1, function (mw1) {
  // Do stuff with first middleware

  swaggerTools.initializeMiddleware(doc2, function (mw2) {
    // Do stuff with second middleware

    // Repeat...
  });
});
```
