### ISSUE TITLE
date-time validator ignores fractional seconds

### ISSUE THREAD

**Issue by hsgreen** [apigee-127/swagger-tools#520]
The current validator does not have support for the fractional seconds portion of the JSON date-time format. See https://tools.ietf.org/html/rfc3339#section-5.6  [time-secfrac]

When timestamps that include fractional seconds are parsed the fractional second is dropped in the resulting parameter object's value field.

Ex:
 ```
{
  path: Array(5),
  schema: Object,
  originalValue: '2017-07-24T14:38:19.900Z',
  value: 2017-07-24T14:38:19.000Z 
}
```

**Comment by whitlockjc** [comment]
Can you tell me more about what is going on?  Is there a validation error happening or something else?  It seems like maybe the time coercion from `String` to `Date` is dropping them but I cannot tell so I figured I'd ask.

**Comment by hsgreen** [comment]
After tracing through the code more it looks it might be something with the underlying javascript engine.
This seems to be where it happens:
https://github.com/apigee-127/swagger-tools/blob/b177225dd8241eefe7f2a5154be84814f3a29d84/middleware/helpers.js#L296
