### ISSUE TITLE
swagger-router handler works locally, but not on the server

### ISSUE THREAD

**Issue by noahm888** [apigee-127/swagger-tools#521]
When I run my swagger-node project locally, I get no issues routing to the controller, but when it is on the server, I get this error:

Cannot resolve the configured swagger-router handler: dfgl_save

An excerpt from the swagger.yaml:

```yaml
/DFGL:
    x-swagger-router-controller: dfgl
    post:
      description: saves submission
      # used as the method name of the controller
      operationId: save
      parameters:
        - name: submission
          in: body
          description: the submission json object
          required: true
          schema:
            $ref: "#/definitions/Submissions"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Submissions"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
```

And from my server code (generated from typescript):

```js
var DFGLController = (function () {
    function DFGLController () {
    }
    .... // does stuff here
   DFGLController.prototype.save = function (req, res, next) { 
    .... // does database stuff here
    }
})

var controller = new DFGLController();
exports.save = controller.save;
```

My x-swagger-router-controller matches my controller filename dfgl.js and the operationId matches the function name save.

This works with no issues when I run it locally, it only give the error when running on the server. Am I doing something wrong here?

**Comment by whitlockjc** [comment]
Run it with `DEBUG=swagger-tools*` and let me know what you see.

**Comment by noahm888** [comment]
Here is the output:

> root@ad9692c9a61f:/app/package# DEBUG=swagger-tools* swagger project start
Starting: /app/package/app.js...
  project started here: http://localhost:10010/
  project will restart on changes.
  to restart at any time, enter `rs`
  swagger-tools:middleware Initializing middleware +0ms
  swagger-tools:middleware   Identified Swagger version: 2.0 +3ms
(node:102) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
  swagger-tools:middleware   Validation: succeeded +63ms
  swagger-tools:middleware:router Initializing swagger-router middleware +11ms
  swagger-tools:middleware:router   Mock mode: disabled +0ms
  swagger-tools:middleware:router   Controllers: +1ms
  swagger-tools:middleware:validator Initializing swagger-validator middleware +1ms
  swagger-tools:middleware:validator   Response validation: enabled +0ms
  swagger-tools:middleware:security Initializing swagger-security middleware +5ms
  swagger-tools:middleware:security   Security handlers: 0 +0ms
  swagger-tools:middleware:metadata Initializing swagger-metadata middleware +81ms
  swagger-tools:middleware:metadata   Identified Swagger version: 2.0 +0ms
  swagger-tools:middleware:metadata   Found Path: /DFGL/{id} +2ms
  swagger-tools:middleware:metadata   Found Path: /DFGL +1ms
  swagger-tools:middleware:metadata   Found Path: /Mapping +0ms
  swagger-tools:middleware:metadata   Found Path: /swagger +0ms
  swagger-tools:middleware:metadata GET / +4s
  swagger-tools:middleware:metadata   Is a Swagger path: false +1ms
  swagger-tools:middleware:metadata POST /DFGL +12s
  swagger-tools:middleware:metadata   Is a Swagger path: true +0ms
  swagger-tools:middleware:metadata   Is a Swagger operation: true +1ms
  swagger-tools:middleware:metadata   Processing Parameters +1ms
  swagger-tools:middleware:metadata     submission +22ms
  swagger-tools:middleware:metadata       Type: object +0ms
  swagger-tools:middleware:metadata       Value provided: true +1ms
  swagger-tools:middleware:metadata       Value: [object Object] +0ms
  swagger-tools:middleware:security POST /DFGL +8ms
  swagger-tools:middleware:security   Will process: yes +0ms
  swagger-tools:middleware:validator POST /DFGL +1ms
  swagger-tools:middleware:validator   Will process: yes +0ms
  swagger-tools:middleware:validator   Request validation: +1ms
  swagger-tools:middleware:validator     Validation: succeeded +6ms
  swagger-tools:middleware:router POST /DFGL +1ms
  swagger-tools:middleware:router   Will process: yes +0ms
  swagger-tools:middleware:router   Route handler: dfgl_save +0ms
  swagger-tools:middleware:router     Missing: yes +0ms
  swagger-tools:middleware:router     Ignored: no +1ms
  swagger-tools:middleware:router     Using mock: no +0ms
  swagger-tools:middleware:router   Reason: Cannot resolve the configured swagger-router handler: dfgl_save +0ms
  swagger-tools:middleware:router   Stack: +1ms
  swagger-tools:middleware:router       at swaggerRouter (/app/package/node_modules/swagger-tools/middleware/swagger-router.js:414:18) +0ms
  swagger-tools:middleware:router       at swagger_router (/app/package/node_modules/swagger-node-runner/fittings/swagger_router.js:31:5) +0ms
  swagger-tools:middleware:router       at Runner.<anonymous> (/app/package/node_modules/bagpipes/lib/bagpipes.js:171:7) +0ms
  swagger-tools:middleware:router       at bound (domain.js:301:14) +0ms
  swagger-tools:middleware:router       at Runner.runBound (domain.js:314:12) +0ms
  swagger-tools:middleware:router       at Runner.pipeline (/app/package/node_modules/pipeworks/pipeworks.js:72:17) +0ms
  swagger-tools:middleware:router       at Runner.flow (/app/package/node_modules/pipeworks/pipeworks.js:223:19) +0ms
  swagger-tools:middleware:router       at Pipeworks.flow (/app/package/node_modules/pipeworks/pipeworks.js:135:17) +0ms
  swagger-tools:middleware:router       at Pipeworks.siphon (/app/package/node_modules/pipeworks/pipeworks.js:186:19) +0ms
  swagger-tools:middleware:router       at Runner.<anonymous> (/app/package/node_modules/bagpipes/lib/bagpipes.js:98:22) +0ms
  swagger-tools:middleware:router       at bound (domain.js:301:14) +0ms
  swagger-tools:middleware:router       at Runner.runBound (domain.js:314:12) +0ms
  swagger-tools:middleware:router       at Runner.<anonymous> (/app/package/node_modules/pipeworks/pipeworks.js:72:17) +0ms
  swagger-tools:middleware:router       at postFlight (/app/package/node_modules/bagpipes/lib/bagpipes.js:218:3) +0ms
  swagger-tools:middleware:router       at /app/package/node_modules/bagpipes/lib/bagpipes.js:174:9 +0ms
  swagger-tools:middleware:router       at expressCompatibility (/app/package/node_modules/swagger-node-runner/fittings/express_compatibility.js:41:3) +0ms
Error: Cannot resolve the configured swagger-router handler: dfgl_save
    at swaggerRouter (/app/package/node_modules/swagger-tools/middleware/swagger-router.js:414:18)
    at swagger_router (/app/package/node_modules/swagger-node-runner/fittings/swagger_router.js:31:5)
    at Runner.<anonymous> (/app/package/node_modules/bagpipes/lib/bagpipes.js:171:7)
    at bound (domain.js:301:14)
    at Runner.runBound (domain.js:314:12)
    at Runner.pipeline (/app/package/node_modules/pipeworks/pipeworks.js:72:17)
    at Runner.flow (/app/package/node_modules/pipeworks/pipeworks.js:223:19)
    at Pipeworks.flow (/app/package/node_modules/pipeworks/pipeworks.js:135:17)
    at Pipeworks.siphon (/app/package/node_modules/pipeworks/pipeworks.js:186:19)
    at Runner.<anonymous> (/app/package/node_modules/bagpipes/lib/bagpipes.js:98:22)
    at bound (domain.js:301:14)
    at Runner.runBound (domain.js:314:12)
    at Runner.<anonymous> (/app/package/node_modules/pipeworks/pipeworks.js:72:17)
    at postFlight (/app/package/node_modules/bagpipes/lib/bagpipes.js:218:3)
    at /app/package/node_modules/bagpipes/lib/bagpipes.js:174:9
    at expressCompatibility (/app/package/node_modules/swagger-node-runner/fittings/express_compatibility.js:41:3)

**Comment by noahm888** [comment]
The issue has been located. There was a problem with our docker container. Thanks for the quick reply and effort anyway. Closing now.
