### ISSUE TITLE
Cannot resolve the configured swagger-router handler: User_logoutUser

### ISSUE THREAD

**Issue by shraddha18** [apigee-127/swagger-tools#524]
I have defined a route as /v2/user/logout. A request to localhost:3000/v2/user/logout yields the following error: 
`Error: Cannot resolve the configured swagger-router handler: User_logoutUser
    at Object.swaggerRouter [as handle] (/Users/shraddha/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/swagger-tools/middleware/swagger-router.js:414:18)
    at next (/Users/shraddha/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at /Users/shraddha/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/swagger-tools/middleware/swagger-validator.js:352:30
    at /Users/shraddha/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:52:16
    at /Users/shraddha/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:361:13
    at /Users/shraddha/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:52:16
    at async.forEachOf.async.eachOf (/Users/shraddha/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:236:30)
    at _asyncMap (/Users/shraddha/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:355:9)
    at Object.map (/Users/shraddha/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:337:20)
    at Object.swaggerValidator [as handle] (/Users/shraddha/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/swagger-tools/middleware/swagger-validator.js:323:15)`

I have also tried specifying the x-swagger-router-controller, operationId and x-swagger-router-handle-subpaths but none of it seems too work. Here is a snippet of my swagger.yaml file 

```yaml
   /user/logout:
        get:
          tags:
          - "user"
          summary: "Logs out current logged in user session"
          operationId: "logoutUser"
          x-swagger-router-handle-subpaths: true
          produces:
          - "application/xml"
          - "application/json"
          parameters: []
          responses:
            default:
              description: "successful operation"
          x-swagger-router-controller: "User"
```

**Comment by whitlockjc** [comment]
What is the file and function name you expect to handle this request?  It should be a function named `logoutUser` in a file named `User.js`.

**Comment by shraddha18** [comment]
There is a function by the same name in User.js 

**User.js**
```javascript
module.exports.logoutUser = function logoutUser (req, res, next) {
  User.logoutUser(req.swagger.params, res, next);
};```

There's another auto-gen file by the name UserService.js which is defined as follows:
```javascript
exports.logoutUser = function(args, res, next) {
  /**
   * Logs out current logged in user session
   *
   *
   * no response value expected for this operation
   **/
   console.log('Hola User');
  res.end();
}```

**Comment by whitlockjc** [comment]
Can you start your server with `DEBUG=swagger-tools*`, make the problematic request and then post the pertinent output?  There is a ton of details output in debug mode.

**Comment by shraddha18** [comment]
So this is the output after I run the request:
`
swagger-tools:middleware:metadata GET /v2/user/logout +50s
  swagger-tools:middleware:metadata   Is a Swagger path: true +0ms
  swagger-tools:middleware:metadata   Is a Swagger operation: true +0ms
  swagger-tools:middleware:metadata   Processing Parameters +1ms
  swagger-tools:middleware:validator GET /v2/user/logout +2ms
  swagger-tools:middleware:validator   Will process: yes +0ms
  swagger-tools:middleware:validator   Request validation: +1ms
  swagger-tools:middleware:validator     Validation: succeeded +0ms
  swagger-tools:middleware:router GET /v2/user/logout +1ms
  swagger-tools:middleware:router   Will process: yes +0ms
  swagger-tools:middleware:router   Route handler: User_logoutUser +1ms
  swagger-tools:middleware:router     Missing: yes +0ms
  swagger-tools:middleware:router     Ignored: no +0ms
  swagger-tools:middleware:router     Using mock: no +0ms
  swagger-tools:middleware:router   Reason: Cannot resolve the configured swagger-router handler: User_logoutUser +1ms
  swagger-tools:middleware:router   Stack: +1ms
  swagger-tools:middleware:router       at Object.swaggerRouter [as handle] (/Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/swagger-tools/middleware/swagger-router.js:414:18) +0ms
  swagger-tools:middleware:router       at next (/Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/express/node_modules/connect/lib/proto.js:193:15) +0ms
  swagger-tools:middleware:router       at /Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/swagger-tools/middleware/swagger-validator.js:352:30 +0ms
  swagger-tools:middleware:router       at /Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:52:16 +0ms
  swagger-tools:middleware:router       at /Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:361:13 +0ms
  swagger-tools:middleware:router       at /Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:52:16 +0ms
  swagger-tools:middleware:router       at async.forEachOf.async.eachOf (/Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:236:30) +0ms
  swagger-tools:middleware:router       at _asyncMap (/Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:355:9) +0ms
  swagger-tools:middleware:router       at Object.map (/Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:337:20) +0ms
  swagger-tools:middleware:router       at Object.swaggerValidator [as handle] (/Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/swagger-tools/middleware/swagger-validator.js:323:15) +0ms
Error: Cannot resolve the configured swagger-router handler: User_logoutUser
    at Object.swaggerRouter [as handle] (/Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/swagger-tools/middleware/swagger-router.js:414:18)
    at next (/Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at /Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/swagger-tools/middleware/swagger-validator.js:352:30
    at /Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:52:16
    at /Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:361:13
    at /Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:52:16
    at async.forEachOf.async.eachOf (/Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:236:30)
    at _asyncMap (/Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:355:9)
    at Object.map (/Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:337:20)
    at Object.swaggerValidator [as handle] (/Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/swagger-tools/middleware/swagger-validator.js:323:15)
`

**Comment by whitlockjc** [comment]
During startup, it should show the processes where route handlers are attempting to be resolved.  Can you see where `User_logoutUser` isn't resolved, which file it's looking for?  Where is `User.js` located?

**Comment by shraddha18** [comment]
Fixed!
The middleware router routes to `UserService_logoutUser`. So in swagger.yaml, it must be ` x-swagger-router-controller: "UserService"` and NOT `x-swagger-router-controller: "User"` for it to work. The x-swagger-router-controller part in auto-generated code needs to be modified for it. 
Thank you for the help!

**Comment by whitlockjc** [comment]
:)

**Comment by dantovsky** [comment]
I had this problem.
My solution: I forgot to add the function at module.exports = {...}.
I hope this could help somebody.
