### ISSUE TITLE
Known vulnerabilities

### ISSUE THREAD

**Issue by Nepoxx** [apigee-127/swagger-tools#535]
This project has known vulnerabilities that can be fixed by updating some dependencies:

* Low severity vuln found in debug@2.2.0, introduced via swagger-tools@0.10.1
  * desc: Regular Expression Denial of Service (ReDoS)
  * info: https://snyk.io/vuln/npm:debug:20170905
  * from: swagger-tools@0.10.1 > body-parser@1.12.4 > debug@2.2.0

* Low severity vuln found in ms@0.7.1, introduced via swagger-tools@0.10.1
  * desc: Regular Expression Denial of Service (ReDoS)
  * info: https://snyk.io/vuln/npm:ms:20170412
  * from: swagger-tools@0.10.1 > body-parser@1.12.4 > debug@2.2.0 > ms@0.7.1

* Low severity vuln found in mime@1.3.4, introduced via swagger-tools@0.10.1
  * desc: Regular Expression Denial of Service (ReDoS)
  * info: https://snyk.io/vuln/npm:mime:20170907
  * from: swagger-tools@0.10.1 > superagent@1.8.5 > mime@1.3.4

* High severity vuln found in qs@4.0.0, introduced via swagger-tools@0.10.1
  * desc: Prototype Override Protection Bypass
  * info: https://snyk.io/vuln/npm:qs:20170213
  * from: swagger-tools@0.10.1 > qs@4.0.0

* High severity vuln found in qs@2.4.2, introduced via swagger-tools@0.10.1
  * desc: Prototype Override Protection Bypass
  * info: https://snyk.io/vuln/npm:qs:20170213
  * from: swagger-tools@0.10.1 > body-parser@1.12.4 > qs@2.4.2

* High severity vuln found in qs@2.3.3, introduced via swagger-tools@0.10.1
  * desc: Prototype Override Protection Bypass
  * info: https://snyk.io/vuln/npm:qs:20170213
  * from: swagger-tools@0.10.1 > superagent@1.8.5 > qs@2.3.3

* Medium severity vuln found in string@3.3.3, introduced via swagger-tools@0.10.1
  * desc: Regular Expression Denial of Service (ReDoS)
  * info: https://snyk.io/vuln/npm:string:20170907
  * from: swagger-tools@0.10.1 > string@3.3.3

* Low severity vuln found in superagent@1.8.5, introduced via swagger-tools@0.10.1
  * desc: Denial of Service (DoS)
  * info: https://snyk.io/vuln/npm:superagent:20170807
  * from: swagger-tools@0.10.1 > superagent@1.8.5

* Low severity vuln found in superagent@3.6.2, introduced via swagger-tools@0.10.1
  * desc: Denial of Service (DoS)
  * info: https://snyk.io/vuln/npm:superagent:20170807
  * from: swagger-tools@0.10.1 > json-refs@2.1.7 > path-loader@1.0.2 > superagent@3.6.2

**Comment by Nepoxx** [comment]
There are other known vulnerabilities:
* ms@0.7.1 https://snyk.io/vuln/npm:ms:20170412
* mime@1.3.4 https://snyk.io/vuln/npm:mime:20170907
* qs@4.0.0 https://snyk.io/vuln/npm:qs:20170213 (High severity)

**Comment by elankeeran** [comment]
#517  PR waiting for the merge to master but NO ETA from an owner.

**Comment by whitlockjc** [comment]
And as I've mentioned before, it's already out of date.  I'll get a security only fix out with a day or so.

**Comment by whitlockjc** [comment]
Owners have lives too, sorry for the delay.  You asked for an ETA and got one, gice me a day or two and I'll merge this and push a patch release.

**Comment by whitlockjc** [comment]
I've updated `json-refs` and `path-loader` for similar security issues and published those versions at `3.0.1` and `1.0.4` respectively.  I do see that `snyk` is finding more vulnerabilities than `nsp` is.  I'm actively working on this.

**Comment by elankeeran** [comment]
Are these changes push to www.npmjs.com because still, I'm able to see the difference in commit id npm register has 3d0a6075647c48f11edfed5eeb8ec32245eb68b7 and the last master GitHub has 0cea535b122265c6d01546e199e2e8fda4c0f5da
