### ISSUE TITLE
npm module string is listed under app dependencies but is a dev dependency

### ISSUE THREAD

**Issue by gobeyboy** [apigee-127/swagger-tools#538]
https://github.com/apigee-127/swagger-tools/blob/241e221914ca6161d73f93097b318a8f6662cff5/package.json#L82

`string` is a development dependency but is listed under general dependencies.

Thus, it is picked up by tools such as 'nsp' when swagger-tools is scanned string is currently failing [#536](https://nodesecurity.io/advisories/536)

Can it be removed from run-time dependencies and instead listed under devDependencies?

**Comment by whitlockjc** [comment]
`string` is a runtime dependency for the CLI: `bin/swagger-tools#L38`  I added an exception for https://nodesecurity.io/advisories/536 for `swagger-tools` for this reason alone.  I can possibly remove this dependency but the attack vector is low so I just threw in an exception.

**Comment by whitlockjc** [comment]
This isn't an issue.
