### ISSUE TITLE
0.10.2 too zealous in loading handlers

### ISSUE THREAD

**Issue by netsgnut** [apigee-127/swagger-tools#540]
(Might be related to #537 as well.)

We have an existing project that has a file structure like this:

```
controllers
 |- post
 |  |- getPost.js
 |  |- getPost.test.js
 |  |- getPosts.js
 |  |- getPosts.test.js
 |  |- createPost.js
 |  |- createPost.test.js
```

The unit test cases, hosted at `*.test.js` files, are powered by Mocha, and thus uses some of its defined functions like `before()` and `after()`.

When we upgrade this project to use v0.10.2 instead of v0.10.1, it is found that the tests are now required when we run `initializeMiddleware`, which understandably result in an error thrown `ReferenceError: before is not defined`.

---

Not sure if it is the root cause of the problem, but comparing `middleware/swagger-router.js` at [v0.10.1](https://github.com/apigee-127/swagger-tools/blob/v0.10.1/middleware/swagger-router.js#L61-L106) and [v0.10.2](https://github.com/apigee-127/swagger-tools/blob/v0.10.2/middleware/swagger-router.js#L66-L131), it seems `handlerCacheFromDir` is now `require`-ing in a more zealous manner. As a quick dirty fix we tried replacing that function alone with the original implementation of v0.10.1 and it worked for us here.

Any ideas?

**Comment by whitlockjc** [comment]
This is fixed in `swagger-tools@0.10.3`.
