### ISSUE TITLE
Validating self referring field not working.

### ISSUE THREAD

**Issue by JaekwanLee** [apigee-127/swagger-tools#546]
It seems the validator does not validate schema if it refers to other fields.
We have a tree like structure 
```
{

  "item" : {
     type: object
     required: [ id, content],
     properties: {
        id: { type: string },
        content: 
            $ref: "#/definition/connents"
     }
 }
  "definition": {
     content: {
       type: object,
       required: [ payload ]
       properties: {
          auth: { type string}
          payload: { type .......}
      }
  }
}
```
Validating http request with middleware.swaggerValidator() does not validate nested definition.

**Comment by whitlockjc** [comment]
Do you have a reproduction recipe?  There is very little to go on here.

**Comment by JaekwanLee** [comment]
Sorry, there was a flaw in the swagger.json I was using.
