### ISSUE TITLE
Is there a way to validate multiple swagger files using swagger-tools validate

### ISSUE THREAD

**Issue by skumar568** [apigee-127/swagger-tools#561]
Hi,

As per documentation, it states that we can validate multiple swagger file using `swagger-tools validate` but I am not able to see how. I tried `swagger-tools validate /path/to/swagger1.json /path/to/swagger2.json`, but it always validates 1st JSON.

Am I missing something?

Regards,
Sanjeev

**Comment by whitlockjc** [comment]
The documentation says that multiple documents are used for Swagger 1.x but for Swagger 2.x, it takes just one document.
