### ISSUE TITLE
how to do friendly base url for swagger 2.8.0

### ISSUE THREAD

**Issue by julyaTyrer** [apigee-127/swagger-tools#567]
Hi,

I'm trying to change base url for API documentation. The base url is "http://localhost:8080/swagger-ui.html".  I want to get something like "http://localhost:8080/myapi/swagger-ui.html".

I use Springfox 2.8.0 Swagger, Java 8, Spring Boot 2.0
The swagger configuration is:
```
@Configuration
@EnableSwagger2
public class SwaggerConfiguration {

    @Bean
    public Docket api(ServletContext servletContext) {
        return new Docket(DocumentationType.SWAGGER_2)
                .pathProvider(new RelativePathProvider(servletContext) {
                    @Override
                    public String getApplicationBasePath() {
                        return "/myapi";
                    }
                })
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(Predicates.not(PathSelectors.regex("/error")))
                .build()
                .useDefaultResponseMessages(false);
    }
}
```

Custom path provider had to help, but I still get access to api documentation by using url "http://localhost:8080/swagger-ui.html". If I use url "http://localhost:8080/myapi/swagger-ui.html", I get 404 error.
![screenshot_1](https://user-images.githubusercontent.com/38255325/38865648-196ad042-4247-11e8-8ac2-c207920ba2f8.jpeg)
Please, help to change the code.

**Comment by alexmoleiro** [comment]
See below what worked for us:

> @Configuration
@EnableSwagger2
public class SwaggerConfiguration {

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
            .select()
            .apis(RequestHandlerSelectors.any())
            .paths(PathSelectors.any())
            .build().pathProvider(new RelativePathProvider(null) {
                @Override
                public String getApplicationBasePath() {
                    return "/";
                }
            });
    }
}

**Comment by whitlockjc** [comment]
This has nothing to do with `swagger-tools` I'm afraid.

**Comment by VahanYeghyan** [comment]
alexmoleiro you saved my week)))
