### ISSUE TITLE
URI /api-docs  and /docs are mixed badly 

### ISSUE THREAD

**Issue by BulleSeeker** [apigee-127/swagger-tools#584]
The swagger UI server displays /api-docs on the left of the button "Explore" but sends to this same api home page  ?!   the same same for /docs  from browser ??!!??!!

Just under it the link /api-docs sends to Document where JSON tab is in fact a YAML file ??
Raw tab is in fact JSON file ?!?

Disappointing isn't it ?

**Comment by whitlockjc** [comment]
Disappointing is the way you explain your opinion on the matter.  I do not control how `swagger-ui` works but even if I did, do you think the way you've approached things is appropriate? Yeah...disappointing.

**Comment by BulleSeeker** [comment]
It s not an opinion. It is a fact that swagger tools generates a wrong swapper api page with wrong links on it ? Right ?It doesn t appear when a use swagger-ui on my own. May be the configuration made by swagger tools according to swagger-ui is poor



Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Jeremy Whitlock <notifications@github.com> Date : 07/08/2018  17:55  (GMT+01:00) À : apigee-127/swagger-tools <swagger-tools@noreply.github.com> Cc : BulleSeeker <romphima@gmail.com>, Author <author@noreply.github.com> Objet : Re: [apigee-127/swagger-tools] URI /api-docs and /docs are mixed badly (#584) 
Disappointing is the way you explain your opinion on the matter.  I do not control how swagger-ui works but even if I did, do you think the way you've approached things is appropriate? Yeah...disappointing.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/apigee-127/swagger-tools","title":"apigee-127/swagger-tools","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/apigee-127/swagger-tools"}},"updates":{"snippets":[{"icon":"PERSON","message":"@whitlockjc in #584: Disappointing is the way you explain your opinion on the matter.  I do not control how `swagger-ui` works but even if I did, do you think the way you've approached things is appropriate? Yeah...disappointing."}],"action":{"name":"View Issue","url":"https://github.com/apigee-127/swagger-tools/issues/584#issuecomment-411107335"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apigee-127/swagger-tools/issues/584#issuecomment-411107335",
"url": "https://github.com/apigee-127/swagger-tools/issues/584#issuecomment-411107335",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [apigee-127/swagger-tools] URI /api-docs  and /docs are mixed badly  (#584)",
"sections": [
{
"text": "",
"activityTitle": "**Jeremy Whitlock**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@whitlockjc",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"apigee-127/swagger-tools\",\n\"issueId\": 584,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"apigee-127/swagger-tools\",\n\"issueId\": 584\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/apigee-127/swagger-tools/issues/584#issuecomment-411107335"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 365467273\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by whitlockjc** [comment]
`swagger-tools` just includes `swagger-tools` and doesn't generate anything.  It passes the URL to `swagger-ui` and that's it.  Regardless, your approach was far from acceptable.  If you want help from anyone, try being less abrasive about it.

**Comment by BulleSeeker** [comment]
Ok your are right... swagger-tools is abrasive ....by giving such disappointing result. I wasted my time thinking this was a great tool.



Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Jeremy Whitlock <notifications@github.com> Date : 07/08/2018  18:03  (GMT+01:00) À : apigee-127/swagger-tools <swagger-tools@noreply.github.com> Cc : BulleSeeker <romphima@gmail.com>, Author <author@noreply.github.com> Objet : Re: [apigee-127/swagger-tools] URI /api-docs and /docs are mixed badly (#584) 
swagger-tools just includes swagger-tools and doesn't generate anything.  It passes the URL to swagger-ui and that's it.  Regardless, your approach was far from acceptable.  If you want help from anyone, try being less abrasive about it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/apigee-127/swagger-tools","title":"apigee-127/swagger-tools","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/apigee-127/swagger-tools"}},"updates":{"snippets":[{"icon":"PERSON","message":"@whitlockjc in #584: `swagger-tools` just includes `swagger-tools` and doesn't generate anything.  It passes the URL to `swagger-ui` and that's it.  Regardless, your approach was far from acceptable.  If you want help from anyone, try being less abrasive about it."}],"action":{"name":"View Issue","url":"https://github.com/apigee-127/swagger-tools/issues/584#issuecomment-411110242"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apigee-127/swagger-tools/issues/584#issuecomment-411110242",
"url": "https://github.com/apigee-127/swagger-tools/issues/584#issuecomment-411110242",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [apigee-127/swagger-tools] URI /api-docs  and /docs are mixed badly  (#584)",
"sections": [
{
"text": "",
"activityTitle": "**Jeremy Whitlock**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@whitlockjc",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"apigee-127/swagger-tools\",\n\"issueId\": 584,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"apigee-127/swagger-tools\",\n\"issueId\": 584\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/apigee-127/swagger-tools/issues/584#issuecomment-411110242"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 365467273\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by whitlockjc** [comment]
You are complaining about something that makes no sense.  Attached is a screenshot of `swagger-tools` and the `swagger-ui` it includes.  The URLs presented everywhere are as they should be.  What's your unmet expectation?  And why do you think talking to people like this is okay?  How do you ever expect to get help from people treating them like trash and bad mouthing the project you want help with?

<img width="1440" alt="screen shot 2018-08-07 at 10 21 40 am" src="https://user-images.githubusercontent.com/98899/43789089-5bce2460-9a2c-11e8-99ee-f0e0073467dc.png">

**Comment by BulleSeeker** [comment]
This will be my last message....Dont make software if you cannot handle reported issues.
I dont need this tools any more with those links that dont give the same results .... having a yaml file when i click on json tab ....thats great 
So long

Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Jeremy Whitlock <notifications@github.com> Date : 07/08/2018  18:26  (GMT+01:00) À : apigee-127/swagger-tools <swagger-tools@noreply.github.com> Cc : BulleSeeker <romphima@gmail.com>, Author <author@noreply.github.com> Objet : Re: [apigee-127/swagger-tools] URI /api-docs and /docs are mixed badly (#584) 
You are complaining about something that makes no sense.  Attached is a screenshot of swagger-tools and the swagger-ui it includes.  The URLs presented everywhere are as they should be.  What's your unmet expectation?  And why do you think talking to people like this is okay?  How do you ever expect to get help from people treating them like trash and bad mouthing the project you want help with?


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/apigee-127/swagger-tools","title":"apigee-127/swagger-tools","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/apigee-127/swagger-tools"}},"updates":{"snippets":[{"icon":"PERSON","message":"@whitlockjc in #584: You are complaining about something that makes no sense.  Attached is a screenshot of `swagger-tools` and the `swagger-ui` it includes.  The URLs presented everywhere are as they should be.  What's your unmet expectation?  And why do you think talking to people like this is okay?  How do you ever expect to get help from people treating them like trash and bad mouthing the project you want help with?\r\n\r\n\u003cimg width=\"1440\" alt=\"screen shot 2018-08-07 at 10 21 40 am\" src=\"https://user-images.githubusercontent.com/98899/43789089-5bce2460-9a2c-11e8-99ee-f0e0073467dc.png\"\u003e\r\n"}],"action":{"name":"View Issue","url":"https://github.com/apigee-127/swagger-tools/issues/584#issuecomment-411118049"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apigee-127/swagger-tools/issues/584#issuecomment-411118049",
"url": "https://github.com/apigee-127/swagger-tools/issues/584#issuecomment-411118049",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [apigee-127/swagger-tools] URI /api-docs  and /docs are mixed badly  (#584)",
"sections": [
{
"text": "",
"activityTitle": "**Jeremy Whitlock**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@whitlockjc",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"apigee-127/swagger-tools\",\n\"issueId\": 584,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"apigee-127/swagger-tools\",\n\"issueId\": 584\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/apigee-127/swagger-tools/issues/584#issuecomment-411118049"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 365467273\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by whitlockjc** [comment]
And this is my last message, I don't mind taking feedback.  But your approach needs work and is not one bit constructive.  And seeing that the `swagger-tools` middleware is *NEVER* handed a YAML file, how can it deliver a YAML file back?  `swaggerTools#initializeMiddleware` is given a JavaScript object so it makes sense to get back JSON.

**Comment by BulleSeeker** [comment]
It returns a yaml on json tab 


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Jeremy Whitlock <notifications@github.com> Date : 07/08/2018  18:42  (GMT+01:00) À : apigee-127/swagger-tools <swagger-tools@noreply.github.com> Cc : BulleSeeker <romphima@gmail.com>, Author <author@noreply.github.com> Objet : Re: [apigee-127/swagger-tools] URI /api-docs and /docs are mixed badly (#584) 
And this is my last message, I don't mind taking feedback.  But your approach needs work and is not one bit constructive.  And seeing that the swagger-tools middleware is NEVER handed a YAML file, how can it deliver a YAML file back?  swaggerTools#initializeMiddleware is given a JavaScript object so it makes sense to get back JSON.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/apigee-127/swagger-tools","title":"apigee-127/swagger-tools","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/apigee-127/swagger-tools"}},"updates":{"snippets":[{"icon":"PERSON","message":"@whitlockjc in #584: And this is my last message, I don't mind taking feedback.  But your approach needs work and is not one bit constructive.  And seeing that the `swagger-tools` middleware is *NEVER* handed a YAML file, how can it deliver a YAML file back?  `swaggerTools#initializeMiddleware` is given a JavaScript object so it makes sense to get back JSON."}],"action":{"name":"View Issue","url":"https://github.com/apigee-127/swagger-tools/issues/584#issuecomment-411122985"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apigee-127/swagger-tools/issues/584#issuecomment-411122985",
"url": "https://github.com/apigee-127/swagger-tools/issues/584#issuecomment-411122985",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [apigee-127/swagger-tools] URI /api-docs  and /docs are mixed badly  (#584)",
"sections": [
{
"text": "",
"activityTitle": "**Jeremy Whitlock**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@whitlockjc",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"apigee-127/swagger-tools\",\n\"issueId\": 584,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/apigee-127/swagger-tools/issues/584#issuecomment-411122985"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 365467273\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by whitlockjc** [comment]
So much for _"last message"_...  I do not own `swagger-ui`.  If you click any button on it and it doesn't work like you want, that's not the fault of `swagger-tools`.  I've said this already.  There is *NOTHING* in the `swagger-tools` middleware that will use YAML directly or generate YAML.  This is a `swagger-ui` issue.

**Comment by celalo** [comment]
@BulleSeeker you don't need to be a boorish. Not only the point @whitlockjc is accurate, the tragic way you convey your opinion makes you look like miserable. This project has been around for years, contributed by many and loved by thousands, please be respectful.
