### ISSUE TITLE
multipart parser files not in req.swagger.params

### ISSUE THREAD

**Issue by timomeh** [apigee-127/swagger-tools#60]
multipart parser like [connect-multiparty](https://github.com/andrewrk/connect-multiparty) or [multer](https://github.com/expressjs/multer) store the data for uploaded files in the `req.files` object, which is not included in `req.swagger.params`. They simply will be ignored.

As a workaround I extended the `req.body` with `req.files` in a middleware.
```javascript
app.use(function(req, res, next) {
   _.assign(req.body, req.files);
  next();
});
```
I'm not sure if this should be added into [`swag-metadata.js`](https://github.com/apigee-127/swagger-tools/blob/master/middleware/2.0/swagger-metadata.js) or if a workaround like mine is the appropriate solution, since responding to every request to support a specific middleware is no solution. But I struggled a few hours with this, so at least it's a note to everyone having this problem.

**Comment by whitlockjc** [comment]
Got a specific library/middleware that you'd like to see me use by default?  I'd like to knock this out but before I get started, I'd love to hear what you'd like to see me use.  Of course, the plan is to have a default implementation like I do with body/query string parsing and then allow you to use whatever you want as long as a particular `req.???` is available when the swagger-metadata middleware is ran.

**Comment by timomeh** [comment]
[multer](https://www.npmjs.com/package/multer) is more popular since it's done by expressjs itself. I think this would be the best approach.

**Comment by whitlockjc** [comment]
That's what I'll use then.  Thanks a lot.

**Comment by codeHatcher** [comment]
Agree with using whatever people would be most familiar with.Sent using CloudMagicOn Tue, Feb 10, 2015 at 8:49 AM,  Jeremy Whitlock <notifications@github.com> wrote:            That's what I'll use then.  Thanks a lot.

**Comment by whitlockjc** [comment]
@timomeh Since you've used multer before, for the built-in (provided) multer, do you have any suggestions on multer configuration?  I'll likely provide options for configuring this, and I should do the same for bodyParser as well, but a reasonable default is what I need.  Also, I'd love to avoid mucking with the filesystem to add this support.  _(I'd rather the consumer of `req.swagger.params` to write files to disk, parse them, ...)_

**Comment by timomeh** [comment]
The only configuration I use is `dest` as the destination of incoming/uploaded files. Often I'm using something simple like `dest: './uploads/'`. The `rename` config also sounds useful, but I never used it. The generated filenames from multer are pretty unique.

**Comment by whitlockjc** [comment]
Is there a way to do this without `dest`, say in memory or something?  I would like the API business logic to handle things like where files get saved, how they are renamed, etc. by default.  Of course, since it's configurable you can override the defaults.

**Comment by codeHatcher** [comment]
I think there is a way to do it in memory. That tends to be a lot faster although people unfamiliar may find it ever so slightly more confusing. It’s something like req.files.buffer or req.*.buffer. I don’t remember exactly.

**Comment by whitlockjc** [comment]
I just read that multer will always write to disk so by default, I'll set `dest` to a temp directory and when someone really wants to use this _their way_, they can pass in their own options.

**Comment by codeHatcher** [comment]
I'm pretty sure they have an option called inBuffer or inMemory which will bypass the write to disk and only put it in memory.Sent using CloudMagicOn Tue, Feb 10, 2015 at 10:23 AM,  Jeremy Whitlock <notifications@github.com> wrote:            I just read that multer will always write to disk so by default, I'll set dest to a temp directory and when someone really wants to use this their way, they can pass in their own options.

**Comment by whitlockjc** [comment]
That's what I thought, `inMemory`, but some sources say even that writes to disk and its purpose is to store the file in memory as well as on disk.  I'll do some digging.

**Comment by whitlockjc** [comment]
Seems like I found some old information or it was inaccurate.  The multer page has this to say about `inMemory`: _If the `inMemory` option is true, no data is written to disk but data is kept in a buffer accessible in the file object.

Problem solved.

**Comment by whitlockjc** [comment]
Sorry it took so long.  I'll document this and get a release out soon.  This work also resulted in better form parameter support as well.

**Comment by gone-phishing** [comment]
@whitlockjc Any update on this? Can you please point me to any working example for this as I'm struggling with the same issue?

**Comment by whitlockjc** [comment]
I'll need more information than that.  One thing I can tell you is that `swagger-tools` uses [multer](https://github.com/expressjs/multer) so once you define your Swagger parameters that are `type: file`, `req.swagger.params.{yourParamName}.value` will be a multer file object as described in their documentation.  As for the example you asked about, we have one in the test suite: https://github.com/apigee-127/swagger-tools/blob/master/test/2.0/test-middleware-swagger-metadata.js#L343

**Comment by chandwki** [comment]
So, what's the solution? I'm trying to figure out how to get file uploads working with express, swagger, and multer. Multer works but it fails swagger validation if I set the form-data parameter to be required still.

**Comment by whitlockjc** [comment]
Run with [debugging](https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swagger-middleware-debugging) to figure out why.

**Comment by taitelman** [comment]
for me : what did the trick with node v12 was adding this middleware code:
```
app.use(function (req, res, next) {
	if (req.file && !req.files) {
		req.files = [{...req.file}];
	}
	next();
});
```
