### ISSUE TITLE
Pattern to incorporate auth

### ISSUE THREAD

**Issue by avishaan** [apigee-127/swagger-tools#76]
Is there a recommended pattern to incorporate authentication? I usually use passportJS but more generally I just need to call another route before certain routes I have described in my swagger.json. I realize this isn't a question specifically for this library but it's something that might be handy for users switching over to this from vanilla express routes.

**Comment by Schoonology** [comment]
@codeHatcher, have we actually solved the problem by documenting the auth integration?

**Comment by codeHatcher** [comment]
I ended up using my own middleware on the securities object. I think at the time I couldn't find documentation on this. Can you point me to a working example so I can try and incorporate it into my project?

**Comment by Schoonology** [comment]
I can't, unfortunately. I wound up hacking something together that I'm not sure is entirely idiomatic.

**Comment by whitlockjc** [comment]
swagger-security currently has an open issue *(#203)* that makes auth a little harder to use than it should be.  I'm working on this soon.  If you have any needs, let me know there.
