### ISSUE TITLE
Change Weather Module for Example

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/swagger-tools#86]
It seems Microsoft's Weather API has been changed and this means we need to update the example application and Quick Start guide to use a new Weather module:

https://social.msdn.microsoft.com/Forums/en-US/030116bb-401f-4ef7-a21e-ad59d2113a56/microsoft-weather-api

**Comment by bebraw** [comment]
FYI, looks like [weather-js](https://www.npmjs.com/package/weather-js) has been updated to take this in count. The quick start works ok.

**Comment by whitlockjc** [comment]
Thanks for the heads up.
